Repository ansible/ansible-lint, pull requests merged in 2020-11, with the labels that each got.

#1087 Avoid reporting main role task files as unknown
  lib/ansiblelint/utils.py
Labels: bug

#1048 Avoid crash with None tasks
  examples/example.yml
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  lib/ansiblelint/rules/IncludeMissingFileRule.py
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
Labels: bug

#1089 Avoid 208 rule with unarchive module
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
Labels: bug

#1090 Avoid rule 208 with file module and recursive
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
Labels: bug

#1097 Bump linters
  .pre-commit-config.yaml
  .pylintrc
Labels: skip-changelog

#1104 Fix rotten github actions
  .github/workflows/tox.yml
  docs/conf.py
  setup.cfg
  tox.ini
Labels: skip-changelog, test
