Repository ansible/ansible-lint, pull requests merged in 2020-09, with the labels that each got.

#1024 Replace module should not trigger rule violation
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
Labels: bug

#1017 Refactor conftest.py
  conftest.py
Labels: skip-changelog

#1027 Replace a tmp RST document hack with a directive
  .gitignore
  docs/default_rules.rst
  docs/rules_table_generator_ext.py
Labels: documentation, enhancement, priority/medium, skip-changelog

#1033 Use NamedTemporaryFile for run_playbook
  lib/ansiblelint/testing/__init__.py
Labels: skip-changelog

#948 Use embedded rule testing for MetaTagValidRule
  lib/ansiblelint/rules/MetaTagValidRule.py
  pytest.ini
  test/TestMetaTagValid.py
Labels: enhancement, skip-changelog

#1034 Improve violation avoidance hints
  lib/ansiblelint/__main__.py
  lib/ansiblelint/color.py
Labels: enhancement

#1038 Fix improper syntax highlighting in README
  README.rst
Labels: documentation

#1036 Document packaging of custom rules
  README.rst
Labels: documentation, enhancement

#1039 Enable retries on IOErrors
  lib/ansiblelint/rules/__init__.py
  test/TestIncludeMissFileWithRole.py
Labels: enhancement

#1037 Ignore experimental violations for final result
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
Labels: enhancement, priority/high

#1043 Avoid failing build due to log upload
  .github/workflows/tox.yml
Labels: skip-changelog

#1044 E106: Don't use relative paths for meta/main.yml
  lib/ansiblelint/rules/RoleNames.py
  test/roles/valid-due-to-meta/tasks/debian/main.yml
Labels: bug

#945 Prefer pylint instead over unittest
  .pylintrc
  test/TestAlwaysRunRule.py
  test/TestBecomeUserWithoutBecome.py
  test/TestCliRolePaths.py
  test/TestCommandHasChangesCheck.py
  test/TestComparisonToEmptyString.py
  test/TestComparisonToLiteralBool.py
  test/TestDeprecatedModule.py
  test/TestEnvVarsInCommand.py
  test/TestFormatter.py
  test/TestLineTooLong.py
  test/TestLintRule.py
  test/TestMetaChangeFromDefault.py
  test/TestMetaMainHasInfo.py
  test/TestMetaVideoLinks.py
  test/TestNoFormattingInWhenRule.py
  test/TestOctalPermissions.py
  test/TestPackageIsNotLatest.py
  test/TestRoleHandlers.py
  test/TestRoleRelativePath.py
  test/TestShellWithoutPipefail.py
  test/TestSudoRule.py
  test/TestTaskHasName.py
  test/TestTaskNoLocalAction.py
  test/TestUseCommandInsteadOfShell.py
  test/TestUseHandlerRatherThanWhenChanged.py
  test/TestUsingBareVariablesIsDeprecated.py
  test/TestVariableHasSpaces.py
  test/TestWithSkipTagId.py
Labels: skip-changelog

#1053 Drop the GitHub code owners config
  .github/CODEOWNERS
Labels: help wanted, priority/high, skip-changelog

#1032 Document how to add a new rule
  docs/contributing.rst
Labels: documentation, enhancement

#1030 E208: Corrected file mode checking
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
  test/nomatchestest.yml
  test/unicode.yml
Labels: bug, priority/high
