Repository ansible/ansible-lint, pull requests merged in 2020-10, with the labels that each got.

#1068 Prevent rule 208 matche in nomaches example
  examples/nomatches.yml
Labels: documentation

#1055 Show severity in Github Workflow command message
  lib/ansiblelint/formatters/__init__.py
  test/TestCliRolePaths.py
Labels: incomplete

#1071 Fix typo in tests
  test/block.yml
Labels: skip-changelog

#1074 Ensure loading of collections and plugins
  lib/ansiblelint/utils.py
  test/TestLocalContent.py
  test/local-content/README.md
  test/local-content/collections/ansible_collections/testns/testcoll/galaxy.yml
  test/local-content/collections/ansible_collections/testns/testcoll/plugins/filter/test_filter.py
  test/local-content/collections/ansible_collections/testns/testcoll/plugins/modules/test_module_2.py
  test/local-content/test-collection.yml
  test/local-content/test-roles-failed-complete/roles/role1/library/test_module_1_failed_complete.py
  test/local-content/test-roles-failed-complete/roles/role1/tasks/main.yml
  test/local-content/test-roles-failed-complete/roles/role2/tasks/main.yml
  test/local-content/test-roles-failed-complete/roles/role2/test_plugins/b_failed_complete.py
  test/local-content/test-roles-failed-complete/roles/role3/library/test_module_3_failed_complete.py
  test/local-content/test-roles-failed-complete/roles/role3/tasks/main.yml
  test/local-content/test-roles-failed-complete/test.yml
  test/local-content/test-roles-failed/roles/role1/library/test_module_1_failed.py
  test/local-content/test-roles-failed/roles/role1/tasks/main.yml
  test/local-content/test-roles-failed/roles/role2/tasks/main.yml
  test/local-content/test-roles-failed/roles/role2/test_plugins/b_failed.py
  test/local-content/test-roles-failed/roles/role3/library/test_module_3_failed.py
  test/local-content/test-roles-failed/roles/role3/tasks/main.yml
  test/local-content/test-roles-failed/test.yml
  test/local-content/test-roles-success/roles/role1/library/test_module_1_success.py
  test/local-content/test-roles-success/roles/role1/tasks/main.yml
  test/local-content/test-roles-success/roles/role2/tasks/main.yml
  test/local-content/test-roles-success/roles/role2/test_plugins/b_success.py
  test/local-content/test-roles-success/roles/role3/library/test_module_3_success.py
  test/local-content/test-roles-success/roles/role3/tasks/main.yml
  test/local-content/test-roles-success/test.yml
Labels: bug

#1065 Add progressive mode
  .gitignore
  README.rst
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/errors.py
  lib/ansiblelint/file_utils.py
Labels: feature, feedback-needed
