Repository ansible/ansible-lint, pull requests merged in 2020-12, with the labels that each got.

#1116 Fixed outdated test dependencies
  .github/workflows/tox.yml
  docs/requirements.txt
  test-requirements.txt
  tox.ini
Labels: skip-changelog, test

#1115 Require ansible>=2.9 using extras to avoid direct dependency
  .github/workflows/tox.yml
  README.rst
  docs/requirements.in
  docs/requirements.txt
  lib/ansiblelint/__main__.py
  lib/ansiblelint/constants.py
  setup.cfg
  test/TestMissingFilePermissionsRule.py
  test/TestRoleRelativePath.py
  tox.ini
Labels: major

#1118 Consolidate packaging testing in single tox env
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#1117 Correct detection of Ansible library
  lib/ansiblelint/__init__.py
  lib/ansiblelint/__main__.py
  lib/ansiblelint/_prerun.py
  lib/ansiblelint/constants.py
  tools/check-missing-ansible.py
  tox.ini
Labels: bug

#1103 Add progressive to the merge_config function
  lib/ansiblelint/cli.py
Labels: bug

#1098 Improve documentation
  .gitignore
  README.rst
Labels: docs

#1077 Reduce ansible dependency a little bit
  lib/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py
  lib/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  lib/ansiblelint/utils.py
Labels: enhancement

#1113 Add documentation for lint rule 102
  lib/ansiblelint/rules/NoFormattingInWhenRule.py
Labels: documentation

#983 Make coverage report run only on full test runs
  pytest.ini
  tox.ini
Labels: skip-changelog

#956 Ease creation of MatchError from inside rules
  lib/ansiblelint/rules/__init__.py
Labels: skip-changelog

#1124 Update urls post transition
  .flake8
  .github/CONTRIBUTING.rst
  .pre-commit-hooks.yaml
  CHANGELOG.rst
  README.rst
  docs/README.md
  docs/contributing.rst
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/utils.py
  pytest.ini
  setup.cfg
  test/TestDeprecatedModule.py
  test/TestImportWithMalformed.py
Labels: skip-changelog

#1125 Remove always_run in _sanitize_task
  lib/ansiblelint/utils.py
  test/TestExamples.py
Labels: bug

#1123 Add RuntimeErrorRule internal rule
  lib/ansiblelint/_internal/__init__.py
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/errors.py
  lib/ansiblelint/rules/__init__.py
  test/TestRulesCollection.py
Labels: feature

#1127 Remove old ANSIBLE00.. tags
  lib/ansiblelint/rules/AlwaysRunRule.py
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  lib/ansiblelint/rules/CommandHasChangesCheckRule.py
  lib/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py
  lib/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  lib/ansiblelint/rules/EnvVarsInCommandRule.py
  lib/ansiblelint/rules/GitHasVersionRule.py
  lib/ansiblelint/rules/MercurialHasRevisionRule.py
  lib/ansiblelint/rules/NoFormattingInWhenRule.py
  lib/ansiblelint/rules/OctalPermissionsRule.py
  lib/ansiblelint/rules/PackageIsNotLatestRule.py
  lib/ansiblelint/rules/SudoRule.py
  lib/ansiblelint/rules/TaskHasNameRule.py
  lib/ansiblelint/rules/TrailingWhitespaceRule.py
  lib/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  lib/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py
  lib/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
  test/TestWithSkipTagId.py
Labels: major

#1128 E701: Match only on meta/main.yml
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
Labels: bug

#1126 Change deprecated tag to deprecations
  README.rst
  lib/ansiblelint/rules/AlwaysRunRule.py
  lib/ansiblelint/rules/DeprecatedModuleRule.py
  lib/ansiblelint/rules/NoFormattingInWhenRule.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/SudoRule.py
  lib/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
Labels: major

#1132 Reactivate release-drafter
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#1131 Add more type hints
  lib/ansiblelint/errors.py
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/utils.py
Labels: bug

#1135 Moved two path utils to file_utils
  .github/release-drafter.yml
  lib/ansiblelint/cli.py
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestUtils.py
Labels: refactoring

#1133 Move custom rule docs to standalone page
  README.rst
  docs/custom-rules.rst
  docs/index.rst
  docs/rules.rst
Labels: documentation

#1137 Rule docs fixes
  docs/custom-rules.rst
  docs/rules.rst
Labels: docs

#1138 Cleaned new issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#1136 Improved tags listing
  lib/ansiblelint/__main__.py
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  lib/ansiblelint/rules/__init__.py
Labels: enhancement

#1144 Consolidated test fixtures
  conftest.py
  lib/ansiblelint/testing/fixtures.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissFileWithRole.py
  test/TestIncludeMissingFileRule.py
  test/TestNestedJinjaRule.py
Labels: skip-changelog

#1145 Avoid exiting when Ansible fails to parse files
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/utils.py
  test/TestDeprecatedModule.py
  test/TestLocalContent.py
  test/TestRulesCollection.py
Labels: bug

#1146 Decouple `sys.argv` from the main CLI entrypoint
  lib/ansiblelint/__main__.py
  setup.cfg
Labels: enhancement, refactoring

#1130 warn_list: fix default handling and argument parsing
  README.rst
  docs/rules.rst
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
Labels: bug

#1088 Refactor ANSI implementation
  lib/ansiblelint/__main__.py
  lib/ansiblelint/color.py
  lib/ansiblelint/formatters/__init__.py
  test/TestFormatter.py
  test/TestRunner.py
Labels: enhancement, refactoring

#1148 Enable runner to detect meta files
  lib/ansiblelint/constants.py
  lib/ansiblelint/runner.py
  test/TestDependenciesInMeta.py
  test/dependency-in-meta/bitbucket.yml
  test/dependency-in-meta/galaxy.yml
  test/dependency-in-meta/github.yml
  test/dependency-in-meta/gitlab.yml
  test/dependency-in-meta/meta/main.yml
  test/dependency-in-meta/webserver.yml
Labels: enhancement

#1149 Refactor linting to use a Lintable object
  lib/ansiblelint/file_utils.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissFileWithRole.py
  test/TestIncludeMissingFileRule.py
  test/TestNestedJinjaRule.py
Labels: refactoring, skip-changelog

#1154 Consolidated use of matchyaml
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/PlaybookExtension.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/__init__.py
Labels: refactoring, skip-changelog

#1155 Escape rule messages before printing
  lib/ansiblelint/formatters/__init__.py
Labels: bug

#1156 Made test examples pass yamllint
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
  test/become.yml
  test/block.yml
  test/contains_secrets.yml
  test/playbook-import/playbook_imported.yml
Labels: skip-changelog

#1157 Avoid exception with YAML files which are just strings
  .flake8
  examples/plain_string.yml
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/LoadingFailureRule.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestExamples.py
  test/TestRulesCollection.py
Labels: bug

#1158 Corrected rich dependency
  setup.cfg
Labels: bug

#1159 Updated new issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#1160 Prevent exception when encountering None play item
  examples/tasks/x.yml
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/utils.py
Labels: bug

#1161 Assure failure to include file produce a violation
  lib/ansiblelint/rules/__init__.py
  test/TestRunner.py
  test/block.yml
Labels: enhancement

#1162 Avoid exception with null blocks
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
  test/TestRunner.py
  test/block-null.yml
Labels: bug

#1163 Allow use of colon after noqa
  lib/ansiblelint/skip_utils.py
  test/test_skiputils.py
Labels: bug

#1169 Made formatting easier to read
  lib/ansiblelint/errors.py
  lib/ansiblelint/formatters/__init__.py
  lib/ansiblelint/rules/__init__.py
  test/TestCliRolePaths.py
  test/TestUtils.py
Labels: enhancement

#1171 Improve pinning of test requirements
  .pre-commit-config.yaml
  docs/requirements.txt
  setup.py
  test-requirements.txt
  tox.ini
Labels: enhancement, test

#1170 Don't import collections from relative paths
  lib/ansiblelint/utils.py
Labels: bug

#1172 Refactored usage docs
  README.rst
  docs/usage.rst
Labels: docs

#1173 More docs refactoring
  README.rst
  docs/configuring.rst
  docs/installing.rst
Labels: docs, skip-changelog

#1174 Assure MatchError takes a rule instance
  lib/ansiblelint/errors.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestMatchError.py
Labels: refactoring

#1175 Assure that skipped tags do not endup being reported
  lib/ansiblelint/errors.py
  lib/ansiblelint/rules/__init__.py
Labels: bug

#1177 Enabled doc8 linting
  .pre-commit-config.yaml
  CHANGELOG.rst
  README.rst
  docs/configuring.rst
  docs/custom-rules.rst
  docs/index.rst
  docs/installing.rst
  docs/rules.rst
  docs/usage.rst
Labels: docs, skip-changelog

#1178 Make rules sortable
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/__init__.py
Labels: refactoring, skip-changelog

#1176 More type hints
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/testing/__init__.py
Labels: refactoring, skip-changelog

#1179 Remove leading newlines from test examples
  test/TestNestedJinjaRule.py
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
Labels: skip-changelog, test

#1180 More type hints
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/testing/fixtures.py
  test/TestAnsibleSyntax.py
  test/TestMissingFilePermissionsRule.py
  test/TestRunner.py
  test/TestWithSkipTagId.py
Labels: refactoring, skip-changelog

#955 Add rule violations from Yamllint
  .pre-commit-config.yaml
  .yamllint
  examples/example.yml
  lib/ansiblelint/rules/LineTooLongRule.py
  lib/ansiblelint/rules/TrailingWhitespaceRule.py
  lib/ansiblelint/rules/YamllintRule.py
  mypy.ini
  setup.cfg
  test/TestAnsibleSyntax.py
  test/TestExamples.py
  test/TestLineTooLong.py
  test/TestMissingFilePermissionsRule.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
  test/TestWithSkipTagId.py
  tox.ini
Labels: feature, major

#1181 Avoid testing modules moved out of core
  test/TestUsingBareVariablesIsDeprecated.py
  test/using-bare-variables-failure.yml
  test/using-bare-variables-success.yml
Labels: skip-changelog, test
