Repository ansible/ansible-lint, pull requests merged in 2020-06, with the labels that each got.

#825 🚑 Install amazon.aws from GitHub
  tox.ini
Labels: priority/high, type/bug

#827 Fix ansible-devel install
  tox.ini
Labels: priority/high, review

#822 Make testing ansible-2.10 compatible
  test/TestUtils.py
  test/package-check-success.yml
  tox.ini
Labels: skip-changelog

#821 Moved exit codes to constants
  lib/ansiblelint/cli.py
  lib/ansiblelint/constants.py
  lib/ansiblelint/utils.py
Labels: type/enhancement

#832 Moved initialize_logger
  lib/ansiblelint/__main__.py
  lib/ansiblelint/utils.py
  test/TestUtils.py
Labels: skip-changelog

#833 Remove dependency on ansible.utils.color
  lib/ansiblelint/color.py
  lib/ansiblelint/formatters/__init__.py
Labels: type/enhancement

#830 Remove azure-pipelines integration
  .azure-pipelines/tox.yml
  azure-pipelines.yml
Labels: skip-changelog

#836 Test against newer Pythons (3.9) in GHA
  .github/workflows/tox-tests.yml
Labels: priority/high, type/enhancement

#844 Increased coverage of type checks
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/errors.py
  lib/ansiblelint/generate_docs.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
  mypy.ini
  setup.cfg
Labels: type/enhancement

#847 Skip running always_run rule with ansible 2.10
  test/TestAlwaysRunRule.py
  test/TestDeprecatedModule.py
  test/__init__.py
Labels: skip-changelog

#840 Migrate publishing to PyPI from Travis CI to GHA
  .github/workflows/tox-tests.yml
  .travis.yml
Labels: type/enhancement

#848 Refactor jobs from github actions
  .github/action/readme.md
  .github/workflows/tox-linters.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#851 Remove Travis CI integration
  .github/CODEOWNERS
  .travis.yml
  README.rst
  ROADMAP.rst
  pyproject.toml
  setup.cfg
Labels: skip-changelog

#852 Remove Azure badge
  setup.cfg
Labels: skip-changelog

#854 Restore tox steps from publish action
  .github/workflows/tox.yml
Labels: review, skip-changelog

#853 Improve unjinja function
  lib/ansiblelint/rules/__init__.py
  test/TestAnsibleLintRule.py
Labels: review, type/bug

#846 Refactor MetaMainHasInfoRule
  .flake8
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
Labels: review, type/enhancement

#861 Add a shared docs build env dependencies location
  .readthedocs.yml
  docs/requirements.in
  tox.ini
Labels: documentation, type/enhancement

#869 Revert to using `{temp_dir}` substitution in tox.ini
  tox.ini
Labels: type/enhancement

#856 Replace custom theme with sphinx-ansible-theme
  .readthedocs.yml
  docs/_static/ansible-local.css
  docs/_static/basic.css
  docs/_static/bootstrap-dropdown.js
  docs/_static/bootstrap-scrollspy.js
  docs/_static/bootstrap-sphinx.css
  docs/_static/bootstrap.css
  docs/_static/default.css
  docs/_static/doctools.js
  docs/_static/favicon.ico
  docs/_static/file.png
  docs/_static/jquery.js
  docs/_static/minus.png
  docs/_static/opensearch.xml
  docs/_static/plus.png
  docs/_static/pygments.css
  docs/_static/searchtools.js
  docs/_static/sidebar.js
  docs/_static/solar.css
  docs/_static/solarized-dark.css
  docs/_static/subtle_dots.png
  docs/_static/underscore.js
  docs/_themes/sphinx_rtd_theme/__init__.py
  docs/_themes/sphinx_rtd_theme/breadcrumbs.html
  docs/_themes/sphinx_rtd_theme/footer.html
  docs/_themes/sphinx_rtd_theme/layout.html
  docs/_themes/sphinx_rtd_theme/search.html
  docs/_themes/sphinx_rtd_theme/searchbox.html
  docs/_themes/sphinx_rtd_theme/static/css/badge_only.css
  docs/_themes/sphinx_rtd_theme/static/css/theme.css
  docs/_themes/sphinx_rtd_theme/static/fonts/FontAwesome.otf
  docs/_themes/sphinx_rtd_theme/static/fonts/Inconsolata-Bold.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/Inconsolata-Regular.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/Lato-Bold.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/Lato-BoldItalic.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/Lato-Italic.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/Lato-Regular.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/RobotoSlab-Bold.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/RobotoSlab-Regular.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot
  docs/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg
  docs/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.ttf
  docs/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff
  docs/_themes/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff2
  docs/_themes/sphinx_rtd_theme/static/images/galaxy-logo-02.svg
  docs/_themes/sphinx_rtd_theme/static/images/galaxy-logo-03.svg
  docs/_themes/sphinx_rtd_theme/static/images/logo_invert.png
  docs/_themes/sphinx_rtd_theme/static/js/modernizr.min.js
  docs/_themes/sphinx_rtd_theme/static/js/theme.js
  docs/_themes/sphinx_rtd_theme/theme.conf
  docs/_themes/sphinx_rtd_theme/versions.html
  docs/requirements.in
  docs/rst/conf.py
  mypy.ini
Labels: documentation

#857 Prevent failing on duplicate pushes to TestPyPI @ GHA
  .github/workflows/tox.yml
Labels: skip-changelog

#870 Flatten docs structure
  .pre-commit-config.yaml
  .readthedocs.yml
  docs/_static/theme_overrides.css
  docs/conf.py
  docs/configuring.rst
  docs/default_rules.rst
  docs/index.rst
  docs/installing.rst
  docs/rst/configuring/index.rst
  docs/rst/installing/index.rst
  docs/rst/rules/index.rst
  docs/rst/usage/index.rst
  docs/rules.rst
  docs/usage.rst
  tox.ini
Labels: documentation
