Repository ansible/ansible-lint, pull requests merged in 2020-07, with the labels that each got.

#871 Clean-up leftovers from under docs
  docs/keyword_desc.yml
  docs/modules.js
  docs/variables.dot
  test/TestUtils.py
  test/fixtures/unknown-type.yml
Labels: documentation, type/enhancement

#872 Generate initial docs env lock file with pip-tools
  docs/requirements.txt
  tox.ini
Labels: documentation, type/enhancement

#875 Change documentation website to RTD
  README.rst
  docs/conf.py
  setup.cfg
Labels: documentation

#877 Move default rules table generator to Sphinx ext
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  docs/default_rules.rst
  docs/rules_table_generator_ext.py
  tox.ini
Labels: documentation

#879 Avoid sorting failure with matches without an id
  lib/ansiblelint/__main__.py
  lib/ansiblelint/formatters/__init__.py
Labels: gate, review, type/bug

#882 Adjust RTD config to follow tox setup
  .readthedocs.yml
Labels: gate

#883 Move normpath out of utils
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestUtils.py
Labels: review

#881 Improve MatchError class
  lib/ansiblelint/__main__.py
  lib/ansiblelint/errors.py
  test/TestMatchError.py
Labels: gate, review

#866 Add pylint to pre-commit
  .pre-commit-config.yaml
  .pylintrc
  lib/ansiblelint/__main__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
  test/TestIncludeMissFileWithRole.py
  test/TestRunner.py
  test/TestUtils.py
Labels: review, type/enhancement

#891 LRU Cache for frequently called functions
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
Labels: type/enhancement

#894 Allow backticks in shell commands
  lib/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  test/command-instead-of-shell-success.yml
Labels: priority/medium, type/enhancement, type/proposal

#896 Fix `MatchError` comparison fallback implementation
  lib/ansiblelint/errors.py
  test/TestMatchError.py
Labels: priority/high, type/bug

#897 Make import sections consistent
  docs/conf.py
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/errors.py
  lib/ansiblelint/formatters/__init__.py
  lib/ansiblelint/generate_docs.py
  lib/ansiblelint/rules/ComparisonToEmptyStringRule.py
  lib/ansiblelint/rules/ComparisonToLiteralBoolRule.py
  lib/ansiblelint/rules/EnvVarsInCommandRule.py
  lib/ansiblelint/rules/MetaVideoLinksRule.py
  lib/ansiblelint/rules/NestedJinjaRule.py
  lib/ansiblelint/rules/PlaybookExtension.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
  lib/ansiblelint/rules/VariableHasSpacesRule.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/skip_utils.py
Labels: type/enhancement

#878 Fix broken always_run rule on Ansible 2.10
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/utils.py
  test/TestAlwaysRunRule.py
Labels: gate, review, type/bug

#900 Constrain flake8 ignores to specific files
  .flake8
Labels: priority/high, type/enhancement

#899 Avoid failure with playbooks having tasks key a null value
  lib/ansiblelint/rules/IncludeMissingFileRule.py
  test/TestAnsibleSyntax.py
Labels: priority/medium, type/bug

#901 Fix spelling mistakes in documentation
  README.rst
Labels: documentation

#903 Refactor `_taskshandlers_children` complexity
  .flake8
  lib/ansiblelint/utils.py
Labels: status/in-progress, type/enhancement

#904 Add release-drafter config
  .github/release-drafter.yml
Labels: skip-changelog

#905 Include contributing inside docs
  README.rst
  docs/CONTRIBUTING.md
  docs/conf.py
  docs/index.rst
  docs/requirements.in
  docs/requirements.txt
Labels: bug, documentation

#817 Document module dependencies
  docs/CONTRIBUTING.md
  docs/conf.py
  docs/requirements.in
  docs/requirements.txt
Labels: documentation, enhancement

#913 Replace line attribute from Match with details
  lib/ansiblelint/errors.py
  lib/ansiblelint/formatters/__init__.py
  lib/ansiblelint/rules/__init__.py
  test/TestMatchError.py
Labels: review, skip-changelog

#887 Enable isort
  .isort.cfg
  .pre-commit-config.yaml
  docs/rules_table_generator_ext.py
  lib/ansiblelint/__init__.py
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/constants.py
  lib/ansiblelint/generate_docs.py
  lib/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py
  lib/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestImportIncludeRole.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissingFileRule.py
  test/TestLineNumber.py
  test/TestNestedJinjaRule.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
  test/__init__.py
Labels: enhancement, review

#912 Assure we do not produce duplicated matches
  lib/ansiblelint/__main__.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  test/TestExamples.py
  test/TestMetaMainHasInfo.py
Labels: enhancement

#888 Add ansible210 testing
  .github/workflows/tox.yml
  tox.ini
Labels: enhancement

#910 Enable annotations on failed tests
  .github/workflows/tox.yml
  pytest.ini
Labels: enhancement

#914 Add linter branding for docs
  docs/_static/ansible-lint.svg
  docs/_static/images/logo_invert.png
  docs/conf.py
Labels: enhancement

#915 Added more type information
  lib/ansiblelint/constants.py
  lib/ansiblelint/skip_utils.py
  lib/ansiblelint/utils.py
Labels: enhancement, gate

#919 Fix severity formatter wrong use of color
  lib/ansiblelint/color.py
  lib/ansiblelint/formatters/__init__.py
Labels: bug

#918 Avoid displaying Null with missing filenames
  lib/ansiblelint/formatters/__init__.py
Labels: bug

#924 Upgrade pre-commit linters
  .pre-commit-config.yaml
  tox.ini
Labels: merge-it, skip-changelog

#921 Add more type information
  lib/ansiblelint/__main__.py
  lib/ansiblelint/formatters/__init__.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/skip_utils.py
Labels: merge-it, skip-changelog

#902 Guard target tox interpreter presence in GHA
  .github/workflows/tox.yml
Labels: enhancement, skip-changelog

#927 Make run_ansible_lint reusable across tests
  test/TestCliRolePaths.py
  test/__init__.py
Labels: merge-it, skip-changelog

#929 Improve run_ansible_lint implementation
  test/__init__.py
Labels: skip-changelog

#928 Enable pytest-xdist
  pytest.ini
Labels: enhancement, skip-changelog
