Repository ansible/ansible-lint, pull requests merged in 2020-08, with the labels that each got.

#932 Make pre-commit hook use auto-detect mode
  .pre-commit-hooks.yaml
Labels: bug

#937 Add docstrings to TestUtils suite
  .flake8
  test/TestUtils.py
Labels: documentation, enhancement, merge-it, priority/high, review, skip-changelog

#933 Install pip if missing on zuul
  tools/test-setup.sh
Labels: skip-changelog

#943 Added MissingFilePermissionsRule
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
  test/conftest.py
  test/nomatchestest.yml
  test/unicode.yml
Labels: feature

#926 Enable github actions parsable format
  README.rst
  lib/ansiblelint/__main__.py
  lib/ansiblelint/formatters/__init__.py
  test/TestCliRolePaths.py
Labels: feature

#951 Refactored import_playbook tests
  test/TestImportPlaybook.py
  test/TestPretaskIncludePlaybook.py
  test/playbook-import/playbook_imported.yml
  test/playbook-import/playbook_parent.yml
  test/playbook-include/playbook_post.yml
  test/playbook-include/playbook_pre.yml
Labels: enhancement

#952 Add missing hosts to test files
  test/command-check-failure.yml
  test/command-check-success.yml
  test/command-instead-of-shell-failure.yml
  test/command-instead-of-shell-success.yml
  test/jinja2-when-success.yml
  test/package-check-failure.yml
  test/package-check-success.yml
  test/role-with-handler/main.yml
  test/test/always-run-success.yml
Labels: bug

#949 E208: Improve MissingFilePermissionsRule detection
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
Labels: bug, merge-it

#954 Reduce complexity of runner main loop
  lib/ansiblelint/runner.py
Labels: enhancement, merge-it

#931 refactor: reduce complexity in main function
  .flake8
  lib/ansiblelint/__main__.py
  lib/ansiblelint/formatters/__init__.py
Labels: enhancement, skip-changelog

#961 4.3.0 Release Notes
  CHANGELOG.rst
  ROADMAP.rst
Labels: skip-changelog

#964 E501: Add become_user and become inheritance
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  test/TestSkipInsideYaml.py
  test/become-user-without-become-failure.yml
  test/become-user-without-become-success.yml
Labels: bug

#962 Added bindep file
  bindep.txt
Labels: skip-changelog

#963 Update CHANGELOG.rst
  CHANGELOG.rst
Labels: documentation, skip-changelog

#970 Avoid exception with custom rule paths
  lib/ansiblelint/utils.py
  test/TestUtils.py
Labels: bug

#976 #975: ensure to use expand user and vars in paths
  lib/ansiblelint/cli.py
  test/TestCommandLineInvocationSameAsConfig.py
  test/fixtures/exclude-paths-with-expands.yml
Labels: bug

#972 E106: Role name should be the parent dir of tasks
  lib/ansiblelint/rules/RoleNames.py
Labels: bug, feedback-needed

#971 Indicate how to skip rules on failures
  lib/ansiblelint/__main__.py
  mypy.ini
  setup.cfg
Labels: enhancement, feedback-needed

#980 E106: Avoid false positives with old roles
  lib/ansiblelint/rules/RoleNames.py
  test/TestCliRolePaths.py
  test/roles/ansible-role-foo/tasks/main.yaml
  test/roles/invalid_due_to_meta/meta/main.yml
  test/roles/invalid_due_to_meta/tasks/main.yaml
  test/roles/valid-due-to-meta/meta/main.yml
  test/roles/valid-due-to-meta/tasks/main.yaml
Labels: bug

#984 Added type information to tests
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  mypy.ini
  test/__init__.py
  test/custom_rules/example_com/ExampleComRule.py
  test/custom_rules/example_inc/CustomAlwaysRunRule.py
  test/rules/EMatcherRule.py
  test/rules/UnsetVariableMatcherRule.py
Labels: skip-changelog

#996 E208: Improve detection logic for mode (permissions)
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
Labels: bug

#992 Avoid non parsable output on stdout
  lib/ansiblelint/__main__.py
Labels: bug

#999 Simplify merge_config
  lib/ansiblelint/cli.py
Labels: enhancement, skip-changelog

#989 Add ability to only warn about some rules
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
Labels: feature

#1003 Refactor run_ansible_lint test util
  test/TestCliRolePaths.py
  test/__init__.py
Labels: skip-changelog

#1006 E208: Avoid raise when action=file and state=file
  lib/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestMissingFilePermissionsRule.py
Labels: bug

#978 Made console rule listing rich
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/color.py
  lib/ansiblelint/generate_docs.py
  lib/ansiblelint/rules/__init__.py
  test/TestRulesCollection.py
Labels: feature

#1014 Avoid KeyError: 'skipped_rules' exception
  lib/ansiblelint/rules/IncludeMissingFileRule.py
  test/TestIncludeMissingFileRule.py
Labels: bug

#1010 Move test utils into ansiblelint.testing
  lib/ansiblelint/testing/__init__.py
  test/TestCliRolePaths.py
  test/TestComparisonToEmptyString.py
  test/TestComparisonToLiteralBool.py
  test/TestDeprecatedModule.py
  test/TestEnvVarsInCommand.py
  test/TestLineTooLong.py
  test/TestMetaChangeFromDefault.py
  test/TestMetaMainHasInfo.py
  test/TestMetaTagValid.py
  test/TestMetaVideoLinks.py
  test/TestOctalPermissions.py
  test/TestRoleRelativePath.py
  test/TestRulesCollection.py
  test/TestShellWithoutPipefail.py
  test/TestSudoRule.py
  test/TestTaskNoLocalAction.py
  test/TestUseHandlerRatherThanWhenChanged.py
  test/TestVariableHasSpaces.py
  test/__init__.py
  test/conftest.py
Labels: skip-changelog

#1011 Reorganize test requirements
  .github/dependabot.yml
  test-requirements.in
  test-requirements.txt
  tox.ini
Labels: skip-changelog

#1020 Allow use of file key inside include_tasks
  lib/ansiblelint/utils.py
  test/role-with-included-imported-tasks/tasks/main.yml
Labels: bug

#1022 Handle empty meta/main.yml in RoleNames rule
  lib/ansiblelint/rules/RoleNames.py
  test/TestRoleNames.py
Labels: bug
