Repository ansible/ansible-lint, pull requests merged in 2020-04, with the labels that each got.

#722 Resurrect support for editable mode installs
  .gitignore
  .pre-commit-config.yaml
  setup.py
Labels: type/enhancement

#723 Update virtualenv @ Travis CI to get new pip @ tox
  .travis.yml
Labels: priority/medium, status/in-progress, type/bug

#726 Make config loading failures visible
  lib/ansiblelint/cli.py
  test/TestCommandLineInvocationSameAsConfig.py
  test/fixtures/ansible-config-invalid.yml
Labels: status/in-progress, type/enhancement

#740 Migrate some test to pytest
  test/TestDependenciesInMeta.py
  test/TestImportIncludeRole.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissingFileRule.py
  test/TestPretaskIncludePlaybook.py
  test/TestRuleProperties.py
  test/TestRulesCollection.py
  test/TestRunner.py
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
  test/TestTaskIncludes.py
  test/conftest.py
Labels: status/in-progress, type/enhancement
