Repository ansible/ansible-lint, pull requests merged in 2021-04, with the labels that each got.

#1500 Add DebOps project to eco test pipeline
  playbooks/eco.yml
Labels: skip-changelog

#1516 Update dependencies
  docs/requirements.txt
  test-requirements.txt
Labels: skip-changelog, test

#1515 Fix meta-incorrect rule to report correctly
  src/ansiblelint/rules/MetaChangeFromDefaultRule.py
Labels: bug

#1503 Add ansible-role-bootstrap
  playbooks/eco.yml
Labels: skip-changelog

#1517 Retry prepare environment three times before failing
  .pre-commit-config.yaml
  docs/requirements.txt
  setup.cfg
  src/ansiblelint/prerun.py
  test-requirements.txt
Labels: enhancement

#1498 More type (3)
  mypy.ini
  src/ansiblelint/app.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#1490 Fix role name handling in prerun.py
  playbooks/eco.yml
  src/ansiblelint/prerun.py
Labels: bug

#1525 Fixed docs edit links
  .pre-commit-config.yaml
  docs/conf.py
  src/ansiblelint/utils.py
Labels: bug

#1522 Ensure that the role file is not a file
  src/ansiblelint/utils.py
Labels: bug

#1524 Ignore files from inside templates/
  .pre-commit-config.yaml
  examples/playbooks/templates/not-valid.yaml
  src/ansiblelint/config.py
Labels: bug

#1520 Mention pipx as alternative installer
  docs/installing.rst
Labels: enhancement

#1529 Update installing.rst
  docs/installing.rst
Labels: bug

#1521 Avoid duplicating molecule requirements.yml files
  src/ansiblelint/prerun.py
Labels: enhancement

#1535 change: add file: Lintable argument to <rule_class>.match{,task} methods
  examples/rules/TaskHasTag.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  src/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  src/ansiblelint/rules/ComparisonToLiteralBoolRule.py
  src/ansiblelint/rules/DeprecatedModuleRule.py
  src/ansiblelint/rules/EnvVarsInCommandRule.py
  src/ansiblelint/rules/GitHasVersionRule.py
  src/ansiblelint/rules/MercurialHasRevisionRule.py
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/rules/NestedJinjaRule.py
  src/ansiblelint/rules/NoFormattingInWhenRule.py
  src/ansiblelint/rules/NoTabsRule.py
  src/ansiblelint/rules/OctalPermissionsRule.py
  src/ansiblelint/rules/PackageIsNotLatestRule.py
  src/ansiblelint/rules/RoleRelativePath.py
  src/ansiblelint/rules/ShellWithoutPipefail.py
  src/ansiblelint/rules/TaskHasNameRule.py
  src/ansiblelint/rules/TaskNoLocalAction.py
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  src/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py
  src/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
  src/ansiblelint/rules/VariableHasSpacesRule.py
  src/ansiblelint/rules/__init__.py
Labels: enhancement

#1530 Utilize yamllint severity levels for rule severity
  src/ansiblelint/rules/YamllintRule.py
Labels: enhancement

#1536 Add a py.typed file
  setup.cfg
  src/ansiblelint/py.typed
Labels: enhancement

#1541 Fix eco pipeline
  playbooks/eco.yml
Labels: skip-changelog

#1537 Create CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#1534 Allow configurations for each rule stored in ansiblelint.config.options
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  test/TestAnsibleLintRule.py
Labels: enhancement
