Repository ansible/ansible-lint, pull requests merged in 2021-08, with the labels that each got.

#1683 Rename master branch to main
  .github/CONTRIBUTING.rst
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/release-drafter.yml
  .github/workflows/tox.yml
  README.rst
  docs/conf.py
  docs/contributing.rst
  setup.cfg
Labels: enhancement

#1684 Ensure hints are not displayed on quiet mode
  src/ansiblelint/__main__.py
Labels: bug

#1692 Fix flake8 D103 violation in tests
  .flake8
  src/ansiblelint/cli.py
  src/ansiblelint/utils.py
  test/TestAnsibleLintRule.py
  test/TestBaseFormatter.py
  test/TestCommandLineInvocationSameAsConfig.py
  test/TestDependenciesInMeta.py
  test/TestImportIncludeRole.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissFileWithRole.py
  test/TestNestedJinjaRule.py
  test/TestRuleProperties.py
  test/TestRulesCollection.py
  test/TestRunner.py
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
Labels: skip-changelog, enhancement, test

#1690 Drop flake8 ignores for non-existing files
  .flake8
Labels: skip-changelog, enhancement, test

#1689 Prefer "extend-" counterparts of flake8 options
  .flake8
Labels: skip-changelog, enhancement, test, refactoring

#1693 Add a Darglint config
  .darglint
Labels: skip-changelog, enhancement, test

#1695 Publish autogenerated private module dev API docs
  docs/conf.py
  docs/index.rst
  docs/pkg/.gitignore
  docs/requirements.in
  docs/requirements.txt
  src/ansiblelint/cli.py
  src/ansiblelint/skip_utils.py
Labels: skip-changelog, enhancement, test

#1696 Show all the Sphinx warnings in nitpick mode
  tox.ini
Labels: skip-changelog, enhancement, test

#1697 Fix the type of apidoc_excluded_paths in `conf.py`
  docs/conf.py
Labels: skip-changelog, bug, enhancement, test

#1699 Use pypa/build to produce dists in tox
  tox.ini
Labels: skip-changelog, enhancement, test

#1700 Make the dist metadata check strict
  tox.ini
Labels: skip-changelog, enhancement, test

#1704 Use force for ansible-galaxy install commands
  src/ansiblelint/prerun.py
Labels: bug

#1698 Continuously check for the broken links across the project
  .github/CONTRIBUTING.rst
  .github/SECURITY.rst
  .github/workflows/tox.yml
  docs/conf.py
  docs/usage.rst
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/RoleNames.py
  tox.ini
Labels: skip-changelog, enhancement, test

#1705 Fix flake8 PT009 violation in tests
  .flake8
  test/TestBecomeUserWithoutBecome.py
  test/TestCliRolePaths.py
  test/TestCommandHasChangesCheck.py
  test/TestComparisonToLiteralBool.py
  test/TestDeprecatedModule.py
  test/TestEnvVarsInCommand.py
  test/TestLineTooLong.py
  test/TestLintRule.py
  test/TestMetaChangeFromDefault.py
  test/TestMetaMainHasInfo.py
  test/TestMetaVideoLinks.py
  test/TestNoFormattingInWhenRule.py
  test/TestOctalPermissions.py
  test/TestPackageIsNotLatest.py
  test/TestRoleRelativePath.py
  test/TestShellWithoutPipefail.py
  test/TestTaskHasName.py
  test/TestTaskNoLocalAction.py
  test/TestUseHandlerRatherThanWhenChanged.py
  test/TestUsingBareVariablesIsDeprecated.py
  test/TestWithSkipTagId.py
Labels: skip-changelog

#1655 Refactor use of pip-compile
  .pre-commit-config.yaml
  constraints.txt
  docs/requirements.txt
  setup.cfg
  test-requirements.in
  tox.ini
Labels: skip-changelog
