Repository ansible/ansible-lint, pull requests merged in 2021-12, with the labels that each got.

#1767 Make exclude files work with progressive mode
  src/ansiblelint/__main__.py
Labels: bug

#1773 Configure root logger instead of package logger
  src/ansiblelint/__main__.py
  test/TestVerbosity.py
  test/fixtures/verbosity-tests/.yamllint
Labels: bug, patch, AAP

#1785 Make -q and -qq silence ANSIBLE_DEVEL_WARNING
  src/ansiblelint/prerun.py
Labels: enhancement

#1788 Add a check job to GHA testing workflow
  .github/workflows/tox.yml
Labels: skip-changelog, test

#1791 Instruct pytest to pre-load the `cov` plugin early
  tox.ini
Labels: new, skip-changelog, test
