Repository ansible/ansible-lint, pull requests merged in 2021-11, with the labels that each got.

#1759 Add HOME to safe env vars
  src/ansiblelint/testing/__init__.py
Labels: enhancement

#1760 Set a logo in the Sphinx docs
  docs/conf.py
Labels: enhancement

#1761 Minor tox fixes
  tox.ini
Labels: skip-changelog

#1768 Fix mypy failures on file_utils.py
  src/ansiblelint/file_utils.py
Labels: bug

#1764 docs: Add missing type and parameter in custom-rules.rst
  docs/custom-rules.rst
Labels: enhancement, documentation

#1762 Remove setup.py
  .pre-commit-config.yaml
  constraints.txt
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#1769 Move abspath() to file_utils
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  test/TestRunner.py
Labels: skip-changelog

#1770 Avoid errors processing symlinked files
  src/ansiblelint/file_utils.py
Labels: bug
