Repository ansible/ansible-lint, pull requests merged in 2021-05, with the labels that each got.

#1542 Validate rules objects loaded from plugin rule modules
  src/ansiblelint/rules/__init__.py
Labels: enhancement

#1540 Add new rule that detects use of blind ignore_errors: true
  src/ansiblelint/rules/IgnoreErrorsRule.py
  test/TestRulesCollection.py
  tox.ini
Labels: enhancement

#1543 Allow user to make yamllint rule mandatory
  .ansible-lint
  docs/requirements.in
  docs/requirements.txt
  src/ansiblelint/rules/YamllintRule.py
  test-requirements.txt
Labels: enhancement

#1544 Add support for acceptable command options
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  src/ansiblelint/utils.py
  test/TestSkipInsideYaml.py
Labels: enhancement

#1548 Add Ansible check mode exception to IgnoreErrorsRule
  src/ansiblelint/rules/IgnoreErrorsRule.py
Labels: bug

#1551 Bump linters
  .flake8
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
Labels: skip-changelog

#1553 Fix mypy issue with callable
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  src/ansiblelint/generate_docs.py
Labels: refactoring

#1552 Ignore empty env variable values when updating them
  src/ansiblelint/prerun.py
  test/test_prerun.py
Labels: bug

#1556 Ensure line and column numbers start with 1
  src/ansiblelint/errors.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/rules/__init__.py
  test/TestExamples.py
  test/TestUtils.py
Labels: bug

#1550 Rename get_yaml_files to discover_lintables
  src/ansiblelint/file_utils.py
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: refactoring

#1557 Improve file detection outside git repositories
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  test/TestUtils.py
Labels: bug

#1562 NoLogPasswordsRule: catch password_lock false positives and migrate tests
  examples/playbooks/no-log-passwords-failure.yml
  examples/playbooks/no-log-passwords-success.yml
  src/ansiblelint/rules/NoLogPasswordsRule.py
  test/TestNoLogPasswordsRule.py
Labels: bug

#1564 Add metadata tag to the role-name rule
  src/ansiblelint/rules/RoleNames.py
Labels: bug

#1568 Refactor MissingFilePermissionsRule testing
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/rules/NoLogPasswordsRule.py
  test/TestMissingFilePermissionsRule.py
Labels: refactoring

#1518 Add rule for variable naming
  .ansible-lint
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/VariableNamingRule.py
  test/TestRulesCollection.py
Labels: enhancement

#1567 Switch cache to user cache folder
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/prerun.py
Labels: bug

#1570 Fix exclude bug running outside git repos
  src/ansiblelint/file_utils.py
Labels: bug

#1572 Disable comments-indentation yamllint rule
  src/ansiblelint/rules/YamllintRule.py
Labels: bug

#1575 Enable xdist when running tests
  pytest.ini
  test-requirements.in
Labels: skip-changelog

#1576 Add more type hints
  .pre-commit-config.yaml
  mypy.ini
  test/TestAnsibleLintRule.py
  test/TestAnsibleSyntax.py
  test/TestBaseFormatter.py
  test/TestBecomeUserWithoutBecome.py
  test/TestCliRolePaths.py
  test/TestCodeclimateJSONFormatter.py
  test/TestCommandHasChangesCheck.py
  test/TestCommandLineInvocationSameAsConfig.py
  test/TestComparisonToLiteralBool.py
  test/TestDependenciesInMeta.py
  test/TestDeprecatedModule.py
  test/TestEnvVarsInCommand.py
  test/TestExamples.py
  test/TestFilePathEvaluation.py
  test/TestFormatter.py
  test/TestImportIncludeRole.py
  test/TestImportPlaybook.py
  test/TestImportWithMalformed.py
  test/TestIncludeMissFileWithRole.py
  test/TestIncludeMissingFileRule.py
  test/TestLineTooLong.py
  test/TestLintRule.py
  test/TestLocalContent.py
  test/TestMatchError.py
  test/TestMetaChangeFromDefault.py
  test/TestMetaMainHasInfo.py
  test/TestMetaVideoLinks.py
  test/TestNestedJinjaRule.py
  test/TestNoFormattingInWhenRule.py
  test/TestOctalPermissions.py
  test/TestPackageIsNotLatest.py
  test/TestRoleNames.py
  test/TestRoleRelativePath.py
  test/TestRuleProperties.py
  test/TestRulesCollection.py
  test/TestRunner.py
  test/TestShellWithoutPipefail.py
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
  test/TestTaskHasName.py
  test/TestTaskIncludes.py
  test/TestTaskNoLocalAction.py
  test/TestUseCommandInsteadOfShell.py
  test/TestUseHandlerRatherThanWhenChanged.py
  test/TestUsingBareVariablesIsDeprecated.py
  test/TestUtils.py
  test/test_boot.py
  test/test_prerun.py
  test/test_skiputils.py
Labels: skip-changelog

#1577 Run mypy in strict mode
  .pre-commit-config.yaml
  src/ansiblelint/config.py
  src/ansiblelint/prerun.py
  src/ansiblelint/rules/VariableNamingRule.py
  src/ansiblelint/rules/YamllintRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  test/TestMatchError.py
  test/TestUtils.py
Labels: skip-changelog

#1578 Fix 32 exclude paths limit
  src/ansiblelint/file_utils.py
Labels: bug

#1579 Fix type for rule_runner
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  src/ansiblelint/rules/IgnoreErrorsRule.py
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/rules/NoLogPasswordsRule.py
  src/ansiblelint/rules/VariableNamingRule.py
Labels: skip-changelog

#1580 Make command instead of shell rule recognize fqcn
  examples/playbooks/command-instead-of-shell-failure.yml
  examples/playbooks/command-instead-of-shell-success.yml
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  test/TestUseCommandInsteadOfShell.py
Labels: bug

#1581 Normalize action names using builtins
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
Labels: bug

#1582 Avoid false positive with no-handler
  examples/playbooks/rule-no-handler.yml
  examples/roles/a-role/tasks/main.yml
  src/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py
Labels: enhancement, refactoring

#1583 Fixes false positive with deprecated-bare-vars
  examples/playbooks/using-bare-variables-success.yml
  src/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
Labels: bug
