Repository ansible/ansible-lint, pull requests merged in 2021-02, with the labels that each got.

#1291 Remove exclusions from start
  src/ansiblelint/runner.py
Labels: bug

#1288 Assure we process all lintables
  src/ansiblelint/rules/YamllintRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  test/TestComparisonToLiteralBool.py
Labels: bug, skip-changelog

#1293 Fix typos, minor writing style improvements in docs
  docs/index.rst
Labels: docs

#1294 E203: Respect skip_ansible_lint
  src/ansiblelint/rules/NoTabsRule.py
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: bug

#1295 E206: Make us of matchtask
  examples/playbooks/206.yml
  src/ansiblelint/rules/VariableHasSpacesRule.py
Labels: bug

#1296 Recognize reno release notes
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: enhancement

#1297 Assure we publish on release
  .github/workflows/tox.yml
Labels: skip-changelog

#1300 E206: Avoid false positives with multilines
  examples/playbooks/206.yml
  src/ansiblelint/rules/VariableHasSpacesRule.py
Labels: bug

#1302 Recurse inside given folders
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/TestCliRolePaths.py
  test/TestRunner.py
  test/TestUtils.py
Labels: enhancement

#1304 Add ability to mock roles
  .ansible-lint
  docs/configuring.rst
  examples/playbooks/mocked_dependency.yml
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/testing/__init__.py
  test/TestCliRolePaths.py
  test/TestUtils.py
Labels: enhancement

#1303 Add optional rule to check for loop var prefix
  .ansible-lint
  docs/configuring.rst
  examples/playbooks/pass-loop-var-prefix.yml
  examples/roles/fail_loop_var_prefix/tasks/main.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/RoleLoopVarPrefix.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/text.py
Labels: enhancement

#1305 Drop E suffix when printing rule id
  src/ansiblelint/formatters/__init__.py
  test/TestUtils.py
Labels: enhancement

#1307 Spellcheck fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .pre-commit-config.yaml
  docs/custom-rules.rst
  docs/index.rst
  setup.cfg
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/TestRulesCollection.py
  tox.ini
Labels: skip-changelog

#1310 Avoid exceptions post syntax errors
  examples/playbooks/syntax-error-string.yml
  examples/playbooks/syntax-error.yml
  src/ansiblelint/runner.py
  test/TestExamples.py
Labels: bug

#1312 Move more test files inside examples
  examples/playbooks/always-run-success.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/playbook-parent.yml
  examples/roles/dependency-in-meta/meta/main.yml
  examples/roles/test-role/meta/requirements.yml
  test/TestDependenciesInMeta.py
  test/TestImportPlaybook.py
  test/TestUtils.py
  test/fixtures/config-with-relative-path.yml
  test/playbook-import/playbook_parent.yml
  test/use-as-default-roles-path/test-role/tasks/main.yml
Labels: skip-changelog

#1313 Fix exclude_paths regression
  src/ansiblelint/runner.py
  test/TestRunner.py
Labels: bug

#1314 More complexity reduction
  .flake8
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/utils.py
Labels: refactoring, skip-changelog

#1315 Avoid false positives with literal-compare
  playbook.yml
  src/ansiblelint/rules/ComparisonToLiteralBoolRule.py
Labels: bug

#1316 Add ability to mock modules from collections
  .ansible-lint
  examples/playbooks/mocked_dependency.yml
  src/ansiblelint/_prerun.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  tox.ini
Labels: feature

#1319 Add offline mode for skipping requirements installation
  .ansible-lint
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
Labels: feature

#1318 Add ability to mock roles from within collections
  .ansible-lint
  examples/playbooks/mocked_dependency.yml
  src/ansiblelint/_prerun.py
Labels: feature

#1320 Allow mocking of galaxy roles
  .ansible-lint
  src/ansiblelint/_prerun.py
Labels: enhancement

#1321 Avoid role-name errors with galaxy roles
  examples/roles/dependency_in_meta/meta/main.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/RoleNames.py
  test/TestDependenciesInMeta.py
Labels: bug

#1322 Cleanup release tagging rules
  .github/workflows/tox.yml
  pyproject.toml
Labels: skip-changelog

#1324 Assure we publish tags
  .github/workflows/tox.yml
Labels: skip-changelog

#1333 Publish to test.pypi.org only tags
  .github/workflows/tox.yml
Labels: bug, skip-changelog

#1332 Fix literal-compare test with when sequences
  src/ansiblelint/rules/ComparisonToLiteralBoolRule.py
  test/TestComparisonToLiteralBool.py
Labels: bug

#1335 Correct skip tag for yamllint
  src/ansiblelint/rules/YamllintRule.py
Labels: bug, docs

#1337 Assure only tags are published
  .github/workflows/tox.yml
Labels: skip-changelog

#1340 Fix parsing of unicode filenames reported by git ls-files (#1339)
  examples/playbooks/with-umlaut-ä.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/testing/__init__.py
  test/TestUtils.py
Labels: bug

#1346 Ensure that yamllint config ignore entries are used
  src/ansiblelint/rules/YamllintRule.py
  test/TestExamples.py
Labels: bug

#1347 Fix sentence in usage.rst
  docs/usage.rst
Labels: docs

#1352 Fix environment variable name check in for loop
  src/ansiblelint/config.py
Labels: bug

#1348 Avoid duplicates when injecting extra ansible lookup paths
  src/ansiblelint/_prerun.py
Labels: enhancement

#1342 support extra_vars in syntax check rule
  .ansible-lint
  examples/playbooks/custom_module.yml
  examples/playbooks/extra_vars.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/testing/fixtures.py
Labels: feature

#1355 Adds experimental stdin support
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  test/TestRunner.py
Labels: feature

#1360 Fix patterns used to identify var files
  examples/group_vars/all.yml
  examples/host_vars/localhost.yml
  examples/playbooks/vars/other.yml
  examples/playbooks/vars/subfolder/settings.yml
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: bug

#1361 Avoid overriding role paths defaults
  src/ansiblelint/_prerun.py
  src/ansiblelint/constants.py
  test/TestCliRolePaths.py
Labels: bug

#1362 Remove obsolete changelog
  CHANGELOG.rst
Labels: enhancement

#1363 Recognize standalone galaxy roles
  src/ansiblelint/_prerun.py
  src/ansiblelint/constants.py
  src/ansiblelint/loaders.py
Labels: bug

#1365 Fix gha tag pattern
  .github/workflows/tox.yml
Labels: skip-changelog

#1370 Avoid reporting runtime errors with unknown file types
  src/ansiblelint/skip_utils.py
Labels: bug

#1371 Recognize collections.yml files
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: bug

#1373 Avoid same false positives with no-tabs rule
  examples/playbooks/rule-no-tabs.yml
  src/ansiblelint/rules/ComparisonToLiteralBoolRule.py
  src/ansiblelint/rules/NoTabsRule.py
  src/ansiblelint/rules/VariableHasSpacesRule.py
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: bug

#1372 Fix file config extra_vars options loading
  src/ansiblelint/cli.py
  test/TestCommandLineInvocationSameAsConfig.py
  test/fixtures/config-with-extra-vars.yml
Labels: bug

#1374 Add ability to detect molecule base.yml configs
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: bug

#1377 Disable action validation with tasks by default
  .ansible-lint
  src/ansiblelint/config.py
  src/ansiblelint/utils.py
Labels: bug

#1381 Improve ansible version check
  src/ansiblelint/_prerun.py
Labels: bug

#1382 Update links to Ansible docs for new site layout
  src/ansiblelint/rules/DeprecatedModuleRule.py
  src/ansiblelint/rules/OctalPermissionsRule.py
Labels: docs

#1383 Rewrite ansible version checking
  src/ansiblelint/__main__.py
  src/ansiblelint/_prerun.py
Labels: bug

#1385 Add ability to install v1 requiremets.yml
  examples/reqs_v1/requirements.yml
  examples/reqs_v2/requirements.yml
  src/ansiblelint/_prerun.py
  src/ansiblelint/rules/RoleNames.py
  test/test_prerun.py
Labels: enhancement

#1395 Bump test dependencies
  docs/requirements.txt
  test-requirements.txt
  tox.ini
Labels: skip-changelog

#1396 Disable dependabot due to spammy nature
  .github/dependabot.yml
Labels: skip-changelog, test

#1397 Fix installation of standalone roles
  src/ansiblelint/_prerun.py
  test/test_prerun.py
Labels: bug

#1402 Refactored no-handler rule
  examples/playbooks/role-with-handler.yml
  examples/playbooks/rule-no-handler.yml
  examples/roles/a-role/handlers/main.yml
  examples/roles/a-role/tasks/main.yml
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py
  test/TestRoleHandlers.py
Labels: enhancement

#1401 Improve standalone role name computing
  src/ansiblelint/_prerun.py
Labels: bug

#1404 Made output formatting options more consistent
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/formatters/__init__.py
Labels: enhancement

#1405 Generalize processing of tasks lintable kind
  src/ansiblelint/constants.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
Labels: refactoring

#1407 Recognize requirements inside molecule scenarios
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: bug

#1413 Remove exceptions from unnamed-task rule
  examples/playbooks/example.yml
  examples/playbooks/task-has-name-failure.yml
  examples/playbooks/task-has-name-success.yml
  src/ansiblelint/rules/TaskHasNameRule.py
  test/TestExamples.py
  test/TestTaskHasName.py
Labels: bug
