Repository ansible/ansible-lint, pull requests merged in 2021-03, with the labels that each got.

#1415 Improve tasks detection patterns
  src/ansiblelint/config.py
  test/TestUtils.py
Labels: bug

#1417 Fix ansible-core version detection
  src/ansiblelint/_prerun.py
  src/ansiblelint/config.py
Labels: enhancement

#1416 Removed test dead code
  test/TestCommandLineInvocationSameAsConfig.py
Labels: skip-changelog

#1420 Disable xdist when -k is present
  conftest.py
Labels: skip-changelog

#1419 Avoid creating .cache directory in cwd
  docs/usage.rst
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  test/TestCliRolePaths.py
  test/TestCommandLineInvocationSameAsConfig.py
Labels: bug

#1425 Add support for excluding file globs
  src/ansiblelint/runner.py
  test/TestRunner.py
Labels: enhancement

#1426 Fixed detection of git project dir
  src/ansiblelint/file_utils.py
Labels: bug

#1427 Install collections before linting
  src/ansiblelint/_prerun.py
Labels: bug

#1428 Replace truthy value
  docs/rules.rst
Labels: docs

#1431 Add retries to flaky galaxy tasks
  .pre-commit-config.yaml
  docs/requirements.txt
  mypy.ini
  pytest.ini
  test-requirements.in
  test-requirements.txt
  test/test_prerun.py
  tox.ini
Labels: skip-changelog

#1430 Add more type info
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/logger.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#1433 Add workaround for GHA macos networking issues
  .github/workflows/tox.yml
Labels: skip-changelog

#1432 Expose useful vscode extensions
  .vscode/extensions.json
Labels: skip-changelog

#1435 Improve ctrl-c exit
  src/ansiblelint/__main__.py
  src/ansiblelint/constants.py
Labels: enhancement

#1436 Avoid looking for config file outside current git repo
  docs/configuring.rst
  src/ansiblelint/cli.py
Labels: bug

#1437 Shorten name of labels workflow
  .github/workflows/labels.yml
Labels: skip-changelog

#1438 Avoid failure to determine kind with relative paths
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  test/TestUtils.py
Labels: bug

#1439 Avoid exception with empty galaxy files
  src/ansiblelint/_prerun.py
Labels: bug

#1440 Avoid reporting matcherrors against cwd
  docs/usage.rst
  src/ansiblelint/errors.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/MetaMainHasInfoRule.py
  src/ansiblelint/runner.py
Labels: bug

#1441 Avoid two builds on prereleases
  .github/workflows/tox.yml
Labels: skip-changelog

#1443 Avoid reporting loading errors with vaulted files
  examples/playbooks/vars/not_decryptable.yml
  src/ansiblelint/rules/__init__.py
  test/TestExamples.py
Labels: bug

#1434 Add downstream testing pipeline
  .github/workflows/tox.yml
  playbooks/eco.yml
  tox.ini
Labels: enhancement

#1451 Allow user to specify namespace for standalone roles
  src/ansiblelint/_prerun.py
Labels: enhancement

#1450 Add optional rule that check for no-same-owner
  .ansible-lint
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/NoSameOwnerRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/testing/fixtures.py
  test/TestRulesCollection.py
Labels: enhancement

#1452 Undeprecate numeric rule tags
  src/ansiblelint/__main__.py
Labels: bug

#1453 Improve risky-shell-pipe rule matching
  src/ansiblelint/rules/ShellWithoutPipefail.py
  test/TestShellWithoutPipefail.py
Labels: enhancement

#1459 Avoid pre-run errors when role-name is disabled
  .ansible-lint
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
Labels: enhancement

#1458 Make use of newer sphinx programoutput extension
  docs/conf.py
  docs/requirements.in
  docs/requirements.txt
  docs/usage.rst
  test-requirements.txt
  tox.ini
Labels: enhancement

#1461 Add ability to recognize base file types
  examples/galaxy.yml
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/YamllintRule.py
  test/TestUtils.py
Labels: enhancement

#1466 Fix typo in configuration filename
  src/ansiblelint/cli.py
Labels: bug

#1469 Updated docs on communication channels
  .github/CONTRIBUTING.rst
Labels: bug

#1470 Fixed matching patterns used for mocking
  .ansible-lint
  src/ansiblelint/_prerun.py
Labels: bug

#1472 fix: flake8 error on mocked modules
  src/ansiblelint/constants.py
Labels: bug

#1473 Allow user to extend kinds without overriding defaults
  .ansible-lint
  examples/other/some.yaml-too
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  test/TestExamples.py
  test/TestUtils.py
Labels: bug

#1474 Asure matchtasks is runs on supported file kinds
  src/ansiblelint/rules/__init__.py
Labels: bug

#1475 Avoid warnings when not running inside git repos
  src/ansiblelint/file_utils.py
  test/TestUtils.py
Labels: bug

#1478 Clarify that verbosity can be incremented
  src/ansiblelint/cli.py
Labels: enhancement

#1477 Remove one false positive on pipe-fail rule
  src/ansiblelint/rules/ShellWithoutPipefail.py
  test/TestShellWithoutPipefail.py
Labels: bug

#1480 Improve empty-string-compare rule
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  test/TestComparisonToEmptyString.py
Labels: bug

#1460 Add zuul-jobs and tripleo-ansible repos to eco pipeline
  playbooks/eco.yml
Labels: skip-changelog, test

#1482 Assure project_dir is always valid
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
Labels: bug

#1483 Make prerun module public
  src/ansiblelint/__main__.py
  src/ansiblelint/prerun.py
  src/ansiblelint/testing/__init__.py
Labels: enhancement

#1484 Fix install galaxy role warning message
  src/ansiblelint/prerun.py
Labels: bug

#1486 Fix prerun role-name message
  src/ansiblelint/prerun.py
Labels: bug

#1488 Enable prepare_environment to be used without cli
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/prerun.py
Labels: enhancement

#1493 Fix MetaMainHasInfoRule when running from meta dir
  src/ansiblelint/rules/MetaMainHasInfoRule.py
Labels: bug

#1494 Add ability to ignore jinja2 templates
  .pre-commit-config.yaml
  examples/other/some.j2.yaml
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/utils.py
  test/TestExamples.py
  test/TestUtils.py
Labels: bug

#1496 More type
  .pre-commit-config.yaml
  conftest.py
  docs/rules_table_generator_ext.py
  mypy.ini
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/color.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/rules/NoSameOwnerRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#1497 More type (2)
  .pre-commit-config.yaml
  mypy.ini
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/YamllintRule.py
  src/ansiblelint/utils.py
Labels: skip-changelog
