Repository ansible/ansible-lint, pull requests merged in 2021-07, with the labels that each got.

#1650 fix: improve git file discovery with untracked and removed files
  src/ansiblelint/file_utils.py
  test/TestUtils.py
Labels: bug

#1656 Remove unused intersphinx mappings
  docs/conf.py
Labels: skip-changelog

#1657 Upgrade pip-compile
  .github/workflows/tox.yml
  docs/requirements.txt
  test-requirements.txt
  tox.ini
Labels: skip-changelog

#1658 Improve pre-commit output
  tox.ini
Labels: skip-changelog

#1659 Run pip-compile as a hook
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog, test

#1661 fix: guess project root dir with git, config file and cwd
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
Labels: bug

#1667 Assure variable naming rule always use a pattern
  src/ansiblelint/cli.py
  src/ansiblelint/rules/VariableNamingRule.py
Labels: bug

#1668 Bump test dependencies
  .pre-commit-config.yaml
  docs/requirements.txt
  test-requirements.txt
Labels: skip-changelog

#1675 Fix execution outside git repositories
  src/ansiblelint/file_utils.py
  test/TestUtils.py
  test/conftest.py
Labels: bug

#1672 var-spacing: fix multiline nested JSON false positive
  examples/playbooks/var-spacing.yml
  src/ansiblelint/rules/VariableHasSpacesRule.py
Labels: bug

#1676 Fix the spelling of pitfalls
  docs/index.rst
Labels: skip-changelog
