Repository ansible/ansible-lint, pull requests merged in 2021-01, with the labels that each got.

#1152 Allow linting of roles in the current directory
  lib/ansiblelint/utils.py
  test/TestCliRolePaths.py
  test/use-as-default-roles-path/test-role/tasks/main.yml
Labels: bug

#1182 Make Runner use lintables
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  lib/ansiblelint/constants.py
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/testing/fixtures.py
  lib/ansiblelint/utils.py
  test/TestRunner.py
  test/TestUtils.py
  test/TestWithSkipTagId.py
Labels: refactoring

#1183 Avoid undesirable highlighting with apostrophes
  lib/ansiblelint/__main__.py
Labels: bug

#1184 Minor test sample fixes
  test/TestSkipInsideYaml.py
  test/using-bare-variables-failure.yml
  test/using-bare-variables-success.yml
Labels: skip-changelog, test

#1185 Add ability to report column position
  lib/ansiblelint/errors.py
  lib/ansiblelint/formatters/__init__.py
Labels: enhancement

#1186 Made matchyaml() use lintables
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/PlaybookExtension.py
  lib/ansiblelint/rules/RoleNames.py
  lib/ansiblelint/rules/YamllintRule.py
  lib/ansiblelint/rules/__init__.py
  test/TestIncludeMissingFileRule.py
  test/TestLineNumber.py
  test/TestRunner.py
Labels: major, refactoring

#1187 Add column to MatchError hash calculation
  lib/ansiblelint/errors.py
  test/TestMatchError.py
Labels: bug

#1190 Refactor custom rule tests
  examples/playbooks/bracketsmatchtest.yml
  examples/playbooks/ematcher-rule.yml
  test/TestLintRule.py
  test/TestRulesCollection.py
  test/brackets-do-not-match-test.yml
  test/ematchtest.yml
  test/rules/EMatcherRule.py
Labels: refactoring, skip-changelog

#1191 Made matchplay() use lintables
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  lib/ansiblelint/rules/IncludeMissingFileRule.py
  lib/ansiblelint/rules/MetaChangeFromDefaultRule.py
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
  lib/ansiblelint/rules/MetaTagValidRule.py
  lib/ansiblelint/rules/MetaVideoLinksRule.py
  lib/ansiblelint/rules/NoFormattingInWhenRule.py
  lib/ansiblelint/rules/SudoRule.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/skip_utils.py
  test/TestIncludeMissingFileRule.py
  test/become-user-without-become-failure.yml
  test/become-user-without-become-success.yml
Labels: major, refactoring

#1192 Made match_tasks() use lintable
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/__init__.py
Labels: major, refactoring

#1193 Make matchlines() use lintable
  lib/ansiblelint/_internal/rules.py
  lib/ansiblelint/rules/__init__.py
  test/TestLintRule.py
Labels: major, refactoring

#1194 Made RulesCollection.run() use lintable
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  test/TestRoleNames.py
  test/TestRulesCollection.py
  test/TestTaskIncludes.py
Labels: refactoring, skip-changelog

#1196 Handle spaces in git output command
  lib/ansiblelint/utils.py
Labels: bug

#1199 More use of lintables
  lib/ansiblelint/utils.py
Labels: refactoring, skip-changelog

#1201 More use of lintables (2)
  examples/rules/TaskHasTag.py
  lib/ansiblelint/rules/MetaChangeFromDefaultRule.py
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
  lib/ansiblelint/rules/MetaTagValidRule.py
  lib/ansiblelint/rules/MetaVideoLinksRule.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/utils.py
  test/TestRunner.py
Labels: refactoring, skip-changelog

#1202 Enable MatchError to accept lintables
  lib/ansiblelint/errors.py
  lib/ansiblelint/rules/MetaMainHasInfoRule.py
  lib/ansiblelint/rules/__init__.py
  lib/ansiblelint/runner.py
  test/TestRunner.py
Labels: refactoring, skip-changelog

#1203 Remove always_run rule
  .flake8
  examples/example.yml
  lib/ansiblelint/rules/AlwaysRunRule.py
  lib/ansiblelint/utils.py
  test/TestAlwaysRunRule.py
  test/TestCliRolePaths.py
  test/TestExamples.py
  test/TestMatchError.py
  test/always-run-failure.yml
  test/always-run-success.yml
  test/custom_rules/example_com/ExampleComRule.py
  test/custom_rules/example_inc/CustomRule.py
Labels: major, refactoring

#1204 Remove SudoRule
  .flake8
  lib/ansiblelint/rules/SudoRule.py
  test/TestLineNumber.py
  test/TestSudoRule.py
Labels: major, refactoring

#1205 Avoid highlighting github formatting
  lib/ansiblelint/__main__.py
  test/TestCliRolePaths.py
Labels: bug

#1206 Remove tests that do not pass Ansible own syntax check
  test/TestLocalContent.py
  test/TestRunner.py
  test/TestSkipInsideYaml.py
  test/block-null.yml
  test/emptytags.yml
  test/local-content/test-roles-failed-complete/test.yml
  test/local-content/test-roles-success/test.yml
Labels: refactoring, skip-changelog

#1208 Remove retries on IOErrors
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/__init__.py
  test/TestIncludeMissFileWithRole.py
Labels: bug

#1209 Refactored inclusion test
  examples/playbooks/common-include-1.yml
  examples/playbooks/common-include-2.yml
  examples/playbooks/tasks/included-with-lint.yml
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  test/TestRunner.py
  test/common-include-1.yml
  test/common-include-2.yml
  test/included-with-lint.yml
Labels: refactoring, skip-changelog

#1210 Moved kind detection inside lintable
  lib/ansiblelint/file_utils.py
  lib/ansiblelint/rules/IncludeMissingFileRule.py
  lib/ansiblelint/runner.py
Labels: refactoring

#1200 E304: environment variable with shell is allowed
  lib/ansiblelint/rules/EnvVarsInCommandRule.py
Labels: bug

#1211 Refactor inclusion tests
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/include-import-tasks-in-role.yml
  examples/playbooks/include-in-block.yml
  examples/playbooks/taskimports.yml
  examples/playbooks/taskincludes.yml
  examples/playbooks/tasks/directory with spaces/main.yml
  examples/playbooks/tasks/include-in-block-inner.yml
  examples/playbooks/tasks/nestedincludes.yml
  examples/playbooks/tasks/simpletask.yml
  test/TestTaskIncludes.py
  test/blockincludes.yml
  test/blockincludes2.yml
  test/directory with spaces/main.yml
  test/include-in-block-inner.yml
  test/include-in-block.yml
  test/nestedincludes.yml
  test/simpletask.yml
  test/taskincludes.yml
  test/taskincludes_2_4_style.yml
Labels: refactoring

#1212 Make inclusion tests syntax check compatible
  examples/playbooks/README.md
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/conflicting_action.yml
  examples/playbooks/include-import-tasks-in-role.yml
  examples/playbooks/roles
  examples/playbooks/taskimports.yml
  examples/playbooks/taskincludes.yml
  examples/roles/role_with_task_inclusions/meta/main.yml
  examples/roles/role_with_task_inclusions/tasks/imported_tasks.yml
  examples/roles/role_with_task_inclusions/tasks/included_tasks.yml
  examples/roles/role_with_task_inclusions/tasks/main.yml
  test/TestTaskIncludes.py
  test/role-with-included-imported-tasks/tasks/imported_tasks.yml
  test/role-with-included-imported-tasks/tasks/included_tasks.yml
Labels: refactoring, skip-changelog

#1213 Clarify licensing
  README.rst
  setup.cfg
Labels: docs

#950 E911: Added AnsibleSyntaxCheckRule for running ansible syntax check
  lib/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  lib/ansiblelint/runner.py
  lib/ansiblelint/text.py
  test/TestExamples.py
  test/TestImportIncludeRole.py
  test/TestImportWithMalformed.py
Labels: feature, major

#1215 Enable pytest coloring on github
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog, test

#1214 Avoid checking the same files more than once
  lib/ansiblelint/runner.py
  test/TestRunner.py
Labels: bug

#1216 Avoid using extras from git
  docs/installing.rst
  setup.cfg
  tox.ini
Labels: bug

#1217 Improve packaging checks
  pyproject.toml
  tools/check-missing-ansible.py
  tox.ini
Labels: packaging, skip-changelog

#1218 Remove local scheme hack from gha
  .github/workflows/tox.yml
Labels: skip-changelog

#1219 Improve error message when syntax check fails
  lib/ansiblelint/rules/AnsibleSyntaxCheckRule.py
Labels: enhancement

#1220 Add logging of syntax check durations
  lib/ansiblelint/logger.py
  lib/ansiblelint/rules/AnsibleSyntaxCheckRule.py
Labels: enhancement

#1225 Make pre-commit hook install all extras
  .pre-commit-hooks.yaml
Labels: enhancement

#1226 Auto-detect modules from collection layouts
  examples/playbooks/custom_module.yml
  lib/ansiblelint/_prerun.py
  plugins/modules/fake_module.py
  test-requirements.txt
  test/TestExamples.py
Labels: enhancement

#1228 Avoid mypy error on multiple values (console)
  lib/ansiblelint/color.py
Labels: skip-changelog

#1227 Refactor ANSI enablement logic
  .pre-commit-config.yaml
  lib/ansiblelint/__main__.py
  lib/ansiblelint/cli.py
  setup.cfg
  test/TestCliRolePaths.py
Labels: enhancement

#1229 Auto-detect roles from collection layouts
  lib/ansiblelint/_prerun.py
  test/TestCliRolePaths.py
Labels: enhancement

#1230 E911: Included details about empty playbooks
  examples/playbooks/empty_playbook.yml
  lib/ansiblelint/rules/AnsibleSyntaxCheckRule.py
Labels: enhancement

#1231 Auto install requirements into temp directory
  .pre-commit-config.yaml
  docs/requirements.txt
  lib/ansiblelint/_prerun.py
  test-requirements.txt
Labels: enhancement

#1234 Removed deprecated export
  src/ansiblelint/__init__.py
Labels: major, refactoring

#1236 Refactor module initialization
  .pre-commit-config.yaml
  src/ansiblelint/__init__.py
  src/ansiblelint/__main__.py
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/color.py
  src/ansiblelint/runner.py
  src/ansiblelint/testing/__init__.py
  test/test_boot.py
Labels: refactoring

#1243 Addressed few pylint rule violations
  .pre-commit-config.yaml
  .pylintrc
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/local-content/collections/ansible_collections/testns/testcoll/plugins/filter/test_filter.py
Labels: skip-changelog, test

#1244 Less pylint exceptions
  .pylintrc
  docs/conf.py
  src/ansiblelint/__main__.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/TestAnsibleLintRule.py
  test/TestCliRolePaths.py
Labels: skip-changelog, test

#1246 Refactor 206 rule tests
  examples/playbooks/206.yml
  src/ansiblelint/rules/VariableHasSpacesRule.py
  test/TestVariableHasSpaces.py
Labels: refactoring, test

#1247 Consolidate signature of matchtask()
  docs/custom-rules.rst
  examples/rules/TaskHasTag.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  src/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
  src/ansiblelint/rules/DeprecatedModuleRule.py
  src/ansiblelint/rules/EnvVarsInCommandRule.py
  src/ansiblelint/rules/GitHasVersionRule.py
  src/ansiblelint/rules/MercurialHasRevisionRule.py
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/rules/NestedJinjaRule.py
  src/ansiblelint/rules/NoFormattingInWhenRule.py
  src/ansiblelint/rules/OctalPermissionsRule.py
  src/ansiblelint/rules/PackageIsNotLatestRule.py
  src/ansiblelint/rules/RoleRelativePath.py
  src/ansiblelint/rules/ShellWithoutPipefail.py
  src/ansiblelint/rules/TaskHasNameRule.py
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  src/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py
  src/ansiblelint/rules/UsingBareVariablesIsDeprecatedRule.py
  src/ansiblelint/rules/VariableHasSpacesRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/utils.py
Labels: major, refactoring

#1248 Add type to matchplay() data argument
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  src/ansiblelint/rules/IncludeMissingFileRule.py
  src/ansiblelint/rules/MetaChangeFromDefaultRule.py
  src/ansiblelint/rules/MetaMainHasInfoRule.py
  src/ansiblelint/rules/MetaTagValidRule.py
  src/ansiblelint/rules/MetaVideoLinksRule.py
  src/ansiblelint/rules/NoFormattingInWhenRule.py
Labels: refactoring, skip-changelog

#1252 Run Ansible syntax check only on playbooks
  pytest.ini
  src/ansiblelint/runner.py
  test/TestImportPlaybook.py
  test/TestLocalContent.py
  test/TestRunner.py
  test/TestTaskIncludes.py
Labels: skip-changelog, test

#1253 Improve lintable.kind detection
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: enhancement

#1255 Improve documentation of project goals
  docs/index.rst
Labels: enhancement

#1257 Improve detection of molecule playbooks
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: enhancement

#1268 Separate standalone test examples from code
  .pre-commit-config.yaml
  examples/playbooks/become-user-without-become-failure.yml
  examples/playbooks/become-user-without-become-success.yml
  examples/playbooks/become.yml
  examples/playbooks/block.yml
  examples/playbooks/command-check-failure.yml
  examples/playbooks/command-check-success.yml
  examples/playbooks/command-instead-of-shell-failure.yml
  examples/playbooks/command-instead-of-shell-success.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/handlers/included-handlers.yml
  examples/playbooks/jinja2-when-failure.yml
  examples/playbooks/jinja2-when-success.yml
  examples/playbooks/multiline-brackets-do-not-match-test.yml
  examples/playbooks/multiline-bracketsmatchtest.yml
  examples/playbooks/nomatchestest.yml
  examples/playbooks/norole.yml
  examples/playbooks/norole2.yml
  examples/playbooks/package-check-failure.yml
  examples/playbooks/package-check-success.yml
  examples/playbooks/role-with-handler.yml
  examples/playbooks/skiptasks.yml
  examples/playbooks/task-has-name-failure.yml
  examples/playbooks/task-has-name-success.yml
  examples/playbooks/tasks/varset.yml
  examples/playbooks/tasks/varunset.yml
  examples/playbooks/unicode.yml
  examples/playbooks/using-bare-variables-failure.yml
  examples/playbooks/using-bare-variables-success.yml
  examples/playbooks/with-skip-tag-id.yml
  examples/roles/a-role/handlers/main.yml
  examples/roles/ansible-role-foo/tasks/main.yaml
  examples/roles/invalid-name/tasks/main.yaml
  examples/roles/invalid_due_to_meta/meta/main.yml
  examples/roles/invalid_due_to_meta/tasks/main.yaml
  examples/roles/test-role/molecule/default/include-import-role.yml
  examples/roles/test-role/tasks/main.yml
  examples/roles/test-role/tasks/world.yml
  examples/roles/valid-due-to-meta/meta/main.yml
  examples/roles/valid-due-to-meta/tasks/debian/main.yml
  examples/roles/valid-due-to-meta/tasks/main.yaml
  examples/testproject/roles/test-role/tasks/main.yml
  test/TestBecomeUserWithoutBecome.py
  test/TestCliRolePaths.py
  test/TestCommandHasChangesCheck.py
  test/TestNoFormattingInWhenRule.py
  test/TestPackageIsNotLatest.py
  test/TestRoleHandlers.py
  test/TestRunner.py
  test/TestTaskHasName.py
  test/TestUseCommandInsteadOfShell.py
  test/TestUsingBareVariablesIsDeprecated.py
  test/TestUtils.py
  test/TestWithSkipTagId.py
  test/includedoesnotexist.yml
  test/roles/test-role/tasks/main.yml
Labels: refactoring, skip-changelog

#1269 Identify requirements.yml files
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  test/TestUtils.py
  test/test-role/meta/requirements.yml
Labels: refactoring

#1271 Store configured options inside a module
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
Labels: refactoring, skip-changelog

#1272 Consolidate test examples
  .pre-commit-config.yaml
  .yamllint
  docs/usage.rst
  examples/playbooks/example.yml
  examples/playbooks/plain_string.yml
  examples/playbooks/play.yml
  examples/playbooks/unicode.yml
  examples/unicode.yml
  test/TestCliRolePaths.py
  test/TestExamples.py
Labels: refactoring, skip-changelog

#1273 Refactored file kind detection
  .pre-commit-config.yaml
  mypy.ini
  setup.cfg
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: major, refactoring

#1275 Use Runner.run to loop over all files
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/TestExamples.py
  test/TestImportWithMalformed.py
Labels: refactoring

#1281 Run syntax check in parallel
  src/ansiblelint/runner.py
  test/TestUtils.py
Labels: enhancement

#1283 Lookup for config file in parent folders
  src/ansiblelint/cli.py
Labels: enhancement

#1282 Allow mocking of ansible modules
  .ansible-lint
  docs/configuring.rst
  examples/playbooks/mocked_module.yml
  src/ansiblelint/_prerun.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  test/TestUtils.py
Labels: feature

#1286 Avoid running rule methods on folders
  src/ansiblelint/_internal/rules.py
Labels: bug, skip-changelog

#1287 E205: Assure extension is checked only for playbooks
  src/ansiblelint/rules/PlaybookExtension.py
Labels: bug, skip-changelog

#1289 Avoid printing internals with task_to_str
  src/ansiblelint/utils.py
Labels: enhancement

#1290 Finish example consolidation
  docs/usage.rst
  examples/playbooks/handlers/y.yml
  examples/playbooks/include.yml
  examples/playbooks/lots_of_warnings.yml
  examples/playbooks/nomatches.yml
  examples/playbooks/tasks/x.yml
  test/TestRunner.py
Labels: refactoring, skip-changelog
