Repository ansible/ansible-lint, pull requests merged in 2021-09, with the labels that each got.

#1719 Minor fixes on documentation pages
  docs/installing.rst
  docs/usage.rst
Labels: bug

#1706 no-changed-when: improve testing and documentation
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
Labels: bug

#1724 improve grammar
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/NoSameOwnerRule.py
Labels: bug

#1725 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#1726 Recommend the `redhat.ansible` extension for development
  .vscode/extensions.json
Labels: skip-changelog

#1720 Make core extra use ansible-core
  .pre-commit-config.yaml
  docs/installing.rst
  docs/requirements.in
  docs/requirements.txt
  examples/roles/dependency_in_meta/meta/main.yml
  setup.cfg
  tox.ini
Labels: new, enhancement

#1731 Avoid testing with ansible devel on py36/py37
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog
