Repository ansible/ansible-lint, pull requests merged in 2021-06, with the labels that each got.

#1599 Remove include missing file rule
  src/ansiblelint/rules/IncludeMissingFileRule.py
  test/TestIncludeMissingFileRule.py
  test/TestRulesCollection.py
Labels: bug

#1600 Fixed typo in .ansible-lint
  .ansible-lint
Labels: bug

#1601 Bumped test deps
  docs/requirements.txt
  test-requirements.txt
Labels: skip-changelog, test

#1604 Allow use of ansible debug mode
  src/ansiblelint/config.py
Labels: bug

#1590 Fail NoLogPassword only when loops are used
  src/ansiblelint/rules/NoLogPasswordsRule.py
Labels: bug

#1606 Document syntax-check as unskippable
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
Labels: bug

#1616 Update doc to reference with revision information
  docs/configuring.rst
Labels: bug

#1617 Fix parseable severity
  src/ansiblelint/app.py
Labels: bug

#1618 Update irc server
  .github/CONTRIBUTING.rst
Labels: bug

#1614 Add opt-in rule to check whether FQCN is used for builtins
  src/ansiblelint/rules/EnvVarsInCommandRule.py
  src/ansiblelint/rules/FQCNBuiltinsRule.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
Labels: feature

#1620 Make no-log-password rule an opt-in
  .ansible-lint
  src/ansiblelint/rules/NoLogPasswordsRule.py
  test/TestRulesCollection.py
Labels: bug

#1624 Tag fresh issues with a new label
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#1628 Configure publish job to use release environment
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#1625 Avoid false positive for async commands without changed_when
  examples/playbooks/command-check-failure.yml
  examples/playbooks/command-check-success.yml
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  test/TestCommandHasChangesCheck.py
Labels: bug

#1627 Add require_collection method
  src/ansiblelint/prerun.py
  test/test_prerun.py
Labels: enhancement

#1623 Fix lookup paths in templates
  examples/roles/template_lookup/files/a_file
  examples/roles/template_lookup/tasks/main.yml
  examples/roles/template_lookup_missing/tasks/main.yml
  src/ansiblelint/utils.py
  test/TestUtils.py
Labels: bug

#1631 Make ansible-lint recognize inventory.yml files
  examples/inventory.yml
  src/ansiblelint/config.py
Labels: bug

#1633 Add ability to auto-install required collections
  src/ansiblelint/prerun.py
  test/test_prerun.py
Labels: feature

#1635 Constrain inventory file location
  examples/inventory/inventory.yml
  src/ansiblelint/config.py
Labels: bug

#1636 Revert "Avoid false positive for async commands without changed_when …
  examples/playbooks/command-check-failure.yml
  examples/playbooks/command-check-success.yml
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  test/TestCommandHasChangesCheck.py
Labels: bug, skip-changelog

#1637 Improve install_collection implementation
  src/ansiblelint/config.py
  src/ansiblelint/prerun.py
Labels: bug
