Repository ansible/ansible-lint, pull requests merged in 2022-09, with the labels that each got.

#2378 latest: include filename on rule match
  src/ansiblelint/rules/latest.py
Labels: bug

#2375 jinja[spacing]: use black for formatting
  .config/dictionary.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/playbooks/jinja-spacing.yml
  examples/playbooks/vars/jinja-spacing.yml
  setup.cfg
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/jinja.py
Labels: bug

#2379 refactored runner.is_exclude and MatchError to use Lintable
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_formatter.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_matcherrror.py
Labels: bug

#2380 Correct example of selecting profile from cli
  src/ansiblelint/generate_docs.py
Labels: bug

#2388 docs: replace wrong occurrences of ignore_list with skip_list in rules
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/syntax_check.md
Labels: bug

#2395 Do not parse excluded files
  src/ansiblelint/runner.py
Labels: bug

#2369 Suspend git output in progressive mode
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  test/test_progressive.py
Labels: bug

#2410 Update schemas
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
Labels: bug

#2407 Update test dependencies
  .pre-commit-config.yaml
  requirements.txt
Labels: skip-changelog

#2408 no-jinja-when: add documentation
  src/ansiblelint/rules/no_jinja_when.md
Labels: bug

#2411 Update schemas
  examples/roles/meta_noqa/meta/main.yml
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/meta.json
  test/rules/test_meta_change_from_default.py
Labels: bug

#2409 no-log-password: add documentation
  src/ansiblelint/rules/no_log_password.md
  src/ansiblelint/rules/no_log_password.py
Labels: bug

#2412 fqcn-builtins: add documentation
  src/ansiblelint/rules/fqcn_builtins.md
Labels: bug

#2419 schema: meta/main.yml now requires a version field
  examples/roles/dependency_in_meta/meta/main.yml
  examples/roles/invalid_meta_schema/meta/main.yml
  examples/roles/meta_noqa/meta/main.yml
  examples/roles/role_with_task_inclusions/meta/main.yml
  examples/roles/valid-due-to-meta/meta/main.yml
  src/ansiblelint/schemas/meta.json
  test/test_task_includes.py
Labels: enhancement

#2418 Docs: Minor edits to rule docs
  src/ansiblelint/rules/deprecated_module.md
  src/ansiblelint/rules/no_log_password.md
Labels: bug

#2417 no-changed-when: add documentation
  src/ansiblelint/rules/no_changed_when.md
Labels: bug

#2424 Change ansible-lint logo to bracket-dot from codicons
  docs/_static/ansible-lint.svg
  docs/_static/images/ansible-lint-512.png
  docs/_static/images/favicon.ico
  docs/_static/images/logo_invert.png
  docs/conf.py
Labels: bug

#2425 Clean-up documentation theme
  docs/_static/theme_overrides.css
  docs/conf.py
  requirements.txt
  setup.cfg
Labels: bug

#2416 Document metadata rules
  src/ansiblelint/rules/meta_incorrect.md
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.md
  src/ansiblelint/rules/meta_no_tags.md
  src/ansiblelint/rules/meta_video_links.md
Labels: bug

#2414 Docs: inline env var rule
  src/ansiblelint/rules/inline_env_var.md
Labels: bug

#2383 Add rule to verify that galaxy.yml collection version is present and >= 1.0.0
  .github/workflows/tox.yml
  examples/meta/galaxy.yml
  src/ansiblelint/rules/galaxy.md
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_rules_collection.py
Labels: enhancement

#2415 Docs: literal compare rule
  src/ansiblelint/rules/literal_compare.md
Labels: bug

#2430 Docs: Update the fqcn builtin rule docs for legacy shell
  src/ansiblelint/rules/fqcn_builtins.md
Labels: bug

#2398 Fix include load in blocks
  examples/playbooks/test_include_inplace.yml
  examples/playbooks/test_include_relative.yml
  examples/roles/include_in_the_place/tasks/included_file.yml
  examples/roles/include_relative/tasks/included_file.yml
  examples/roles/include_relative/tasks/main.yml
  src/ansiblelint/rules/literal_compare.md
  src/ansiblelint/utils.py
  test/test_include_miss_file_with_role.py
Labels: bug

#2432 Make links to rule docs relative
  README.md
  docs/conf.py
  setup.cfg
  src/ansiblelint/constants.py
  src/ansiblelint/generate_docs.py
Labels: bug

#2346 Create template_instead_of_copy.py
  .github/workflows/tox.yml
  examples/playbooks/rule-template-instead-of-copy-failure.yml
  examples/playbooks/rule-template-instead-of-copy-success.yml
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/template-instead-of-copy.md
  src/ansiblelint/rules/template_instead_of_copy.py
  test/test_rules_collection.py
Labels: enhancement

#2431 Docs: updates to schema rule
  src/ansiblelint/rules/schema.md
Labels: bug

#2406 Docs: no handler rule
  examples/playbooks/rule-no-handler-fail.yml
  examples/playbooks/rule-no-handler-pass.yml
  src/ansiblelint/rules/no_handler.md
  src/ansiblelint/rules/no_handler.py
Labels: bug

#2300 Fix identification of inline noqa skips
  .ansible-lint
  examples/playbooks/test_skip_inside_yaml.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/yaml_utils.py
  test/test_skip_inside_yaml.py
Labels: bug

#2435 Update meta schema to require standalone property
  examples/roles/dependency_in_meta/meta/main.yml
  examples/roles/invalid_due_to_meta/meta/main.yml
  examples/roles/invalid_meta_schema/meta/main.yml
  examples/roles/meta_noqa/meta/main.yml
  examples/roles/valid-due-to-meta/meta/main.yml
  src/ansiblelint/rules/schema.md
  src/ansiblelint/schemas/meta.json
Labels: bug

#2437 Fix bug in skip_list parsing with lists of integers
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/yaml_rule.py
Labels: bug

#2438 Fix bug parsing inline skips with tags: <int>
  src/ansiblelint/rules/yaml_rule.py
Labels: bug

#2436 Replace no-jinja-nesting with jinja[invalid]
  .github/workflows/tox.yml
  examples/playbooks/rule-jinja-invalid.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/no_jinja_nesting.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/utils.py
  test/rules/test_nested_jinja_rule.py
  test/test_rules_collection.py
  test/test_utils.py
Labels: enhancement

#2439 Update schemas
  src/ansiblelint/schemas/meta.json
Labels: bug

#2440 Improve noqa comment detection
  examples/galaxy.yml
  src/ansiblelint/errors.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
Labels: bug

#2441 Mark galaxy rule as required only for shared profile
  src/ansiblelint/__main__.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/galaxy.py
  test/test_profiles.py
  test/test_rules_collection.py
Labels: bug

#2445 api: enable matchtask() to return list[MatchError]
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/name.py
Labels: bug

#2448 Fix bug with user action
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
Labels: bug

#2446 Docs: no handler rule doc update
  src/ansiblelint/rules/no_handler.md
Labels: bug

#2449 Refactor internal skipped_rules to use private prefix
  src/ansiblelint/constants.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_skiputils.py
Labels: skip-changelog, bug

#2451 Refactor some constants into specific module
  src/ansiblelint/constants.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/utils.py
Labels: refactoring

#2452 Refactor: remove obsolete odict class alias
  .config/dictionary.txt
  docs/conf.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/var_naming.py
Labels: refactoring

#2453 Refactor: remove use of typing Optional
  docs/custom-rules.md
  examples/rules/task_has_tag.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_command_syntax.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/latest.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_loop_var_prefix.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/testing/__init__.py
Labels: skip-changelog

#2450 Docs: yamllint rule
  src/ansiblelint/rules/yaml.md
Labels: bug

#2467 Update schemas
  src/ansiblelint/schemas/meta.json
Labels: bug

#2465 Fix jinja[invalid] false positive
  .config/dictionary.txt
  .github/workflows/tox.yml
  conftest.py
  examples/playbooks/rule-jinja-invalid.yml
  examples/playbooks/rule-jinja-valid.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2471 schema: correct documentation
  src/ansiblelint/rules/schema.py
Labels: bug

#2472 meta: allow empty meta schema files
  src/ansiblelint/schemas/meta.json
Labels: bug

#2481 Document No hosts matched the subscripted pattern
  src/ansiblelint/_internal/internal_error.md
Labels: bug

#2476 Ensure that symlinked arguments are resolved
  .github/workflows/tox.yml
  .pylintrc
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: bug

#2484 schema: allow listen key on handlers
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
Labels: bug

#2486 Change rich markdown theme/colors
  docs/_static/theme_overrides.css
  docs/conf.py
  src/ansiblelint/color.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/no_jinja_when.md
  src/ansiblelint/rules/risky_file_permissions.py
Labels: bug

#2466 fix: use ansible-compat to install collections
  .github/workflows/tox.yml
  examples/collection/galaxy.yml
  requirements.txt
  setup.cfg
  src/ansiblelint/_mockings.py
  src/ansiblelint/app.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/schema.py
  test/fixtures/invalid-mocking/galaxy.yml
  test/test_mockings.py
Labels: bug

#2483 name[template]: recommend to use templating as suffix on names
  .github/workflows/tox.yml
  examples/playbooks/name-templated.yml
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
Labels: enhancement

#2492 Ensure we do not return relative paths outside the project
  src/ansiblelint/file_utils.py
Labels: bug

#2454 key-order: now sorts block/rescue/always to the bottom
  .github/workflows/tox.yml
  examples/playbooks/rule-key-order-fail.yml
  examples/playbooks/test_skip_inside_yaml.yml
  src/ansiblelint/rules/key_order.md
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/testing/__init__.py
Labels: bug

#2470 Refactor no-loop-var-prefix rule
  examples/roles/fail_loop_var_prefix/tasks/main.yml
  examples/roles/loop_var_prefix/tasks/fail.yml
  examples/roles/loop_var_prefix/tasks/pass.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/loop_var_prefix.md
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: bug

#2497 Fixed few profile rule errors
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/errors.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/jinja.py
Labels: bug

#2498 Avoid implicit templating if not play/task
  .github/workflows/tox.yml
  examples/playbooks/vars/rule_jinja_vars.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2499 Fix project_dir detect with .config configs
  src/ansiblelint/file_utils.py
Labels: bug

#2500 Fix exception with vars_prompt
  examples/playbooks/no-prompting.yml
  src/ansiblelint/rules/no_prompting.py
Labels: bug

#2503 Document risky-file-permissions
  .github/workflows/tox.yml
  conftest.py
  examples/playbooks/rule-risky-file-permissions-fail.yml
  examples/playbooks/rule-risky-file-permissions-pass.yml
  requirements.yml
  src/ansiblelint/rules/risky_file_permissions.md
  src/ansiblelint/rules/risky_file_permissions.py
Labels: bug

#2510 Fix rich exception with tasks containing square brackets
  src/ansiblelint/formatters/__init__.py
  test/test_formatter.py
Labels: bug

#2496 var-naming: also recognize vars with set_fact module
  .github/workflows/tox.yml
  examples/playbooks/rule-var-naming-fail.yml
  examples/roles/var_naming_pattern/.ansible-lint
  examples/roles/var_naming_pattern/tasks/main.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#2505 Upgrade fqcn-builtins rule into fqcn
  examples/playbooks/custom_module.yml
  examples/playbooks/nomatchestest.transformed.yml
  examples/playbooks/nomatchestest.yml
  examples/playbooks/rule-risky-file-permissions-fail.yml
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/fqcn.md
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/fqcn_builtins.md
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_eco.py
  test/test_file_path_evaluation.py
  test/test_import_include_role.py
Labels: enhancement

#2511 key-order: Add extra documentation
  src/ansiblelint/rules/key_order.md
Labels: bug

#2514 Increase lock timeout to 180s
  src/ansiblelint/__main__.py
Labels: skip-changelog

#2515 Fix path expansion when outside user home
  .github/workflows/tox.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/syntax_check.py
  test/test_file_utils.py
Labels: bug

#2495 Adds summary stats about found violations
  .flake8
  playbook.yml
  src/ansiblelint/app.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/stats.py
Labels: enhancement

#2512 Replace template-instead-of-copy with avoid-implicit[copy-content]
  examples/playbooks/rule-avoid-implicit-fail.yml
  examples/playbooks/rule-avoid-implicit-pass.yml
  src/ansiblelint/config.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/avoid_implicit.md
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/template-instead-of-copy.md
Labels: bug

#2517 Update schemas
  examples/collection/galaxy.yml
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/playbook.json
Labels: bug

#2518 Allow file attribute with ansible.builtin.include_tasks
  examples/roles/bobbins/tasks/imported_tasks.yml
  examples/roles/bobbins/tasks/main.yml
  src/ansiblelint/utils.py
Labels: bug

#2519 Document lack of module_defaults support
  src/ansiblelint/rules/risky_file_permissions.md
Labels: bug

#2523 Resolved documentation redirects
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
  docs/contributing.md
  docs/installing.md
  docs/usage.md
  src/ansiblelint/rules/command_instead_of_module.md
  src/ansiblelint/rules/schema.md
  src/ansiblelint/yaml_utils.py
  tox.ini
Labels: bug

#2524 Display failure details if collection install fails during testing
  conftest.py
Labels: skip-changelog

#2521 Create codeql.yml
  .config/dictionary.txt
  .github/workflows/codeql.yml
Labels: skip-changelog

#2526 Fix bug which prevented run of rules on tasks doing imports
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/common-include-1.yml
  examples/playbooks/include-in-block.yml
  examples/playbooks/taskimports.yml
  examples/playbooks/tasks/include-in-block-inner.yml
  examples/playbooks/tasks/nestedincludes.yml
  examples/roles/include_in_the_place/tasks/main.yml
  examples/roles/include_miss/tasks/main.yml
  examples/roles/include_relative/tasks/main.yml
  examples/roles/role_with_task_inclusions/tasks/main.yml
  playbook.yml
  src/ansiblelint/utils.py
  test/test_file_path_evaluation.py
  test/test_task_includes.py
  test/test_yaml_utils.py
Labels: bug

#2528 Allow var_files to be null, string and list of strings
  src/ansiblelint/schemas/playbook.json
Labels: bug
