Repository ansible/ansible-lint, pull requests merged in 2022-08, with the labels that each got.

#2257 Update test-dependencies
  .pre-commit-config.yaml
  docs/rules_table_generator_ext.py
  requirements.txt
Labels: skip-changelog

#2258 Upgrade jsonschema to 4.9.0
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: skip-changelog

#2261 Fix: Progressive mode has no effect
  src/ansiblelint/file_utils.py
Labels: bug

#2259 Rename var-spacing rule to jinja[spacing]
  docs/rules.md
  examples/playbooks/var-spacing.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/var_spacing.md
  src/ansiblelint/skip_utils.py
  src/ansiblelint/yaml_utils.py
  test/test_skip_inside_yaml.py
  test/test_yaml_utils.py
Labels: enhancement

#2262 Improve errors with invalid galaxy.yml files
  .github/workflows/tox.yml
  src/ansiblelint/_mockings.py
  test/fixtures/invalid-mocking/galaxy.yml
  test/test_mockings.py
Labels: bug

#2267 Use newer jinja[spacing] tag in tests
  .ansible-lint
  examples/playbooks/jinja-spacing.yml
  examples/playbooks/vars/jinja-spacing.yml
  src/ansiblelint/rules/jinja.py
Labels: skip-changelog

#2268 Avoid occasional role symlink failures during mocking
  mypy.ini
  src/ansiblelint/_mockings.py
Labels: skip-changelog

#2270 Implement file locking on cache directory
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
  src/ansiblelint/__main__.py
Labels: bug

#2264 Improve documentation building
  docs/conf.py
  docs/contributing.md
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  tox.ini
Labels: skip-changelog

#2263 Reimplement unamed-task rule as name[missing]
  examples/playbooks/task-has-name-failure.yml
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/unnamed_task.py
  test/rules/test_unnamed_task.py
  test/test_import_playbook.py
  test/test_skip_inside_yaml.py
  test/test_skiputils.py
  tox.ini
Labels: bug

#2273 Replacing os.system with subprocess functions
  src/ansiblelint/__main__.py
Labels: bug

#2278 Prevent finding playbooks inside tasks folders
  .github/workflows/tox.yml
  src/ansiblelint/config.py
  test/test_file_utils.py
Labels: bug

#2284 Ensure rules are checked in specific order
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/yaml.py
Labels: bug

#2277 Standardize task MatchError enrichment
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/name.py
Labels: bug, refactoring

#2286 Refactor yaml data loading
  .pylintrc
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2290 Add ability to process multi-document YAML files
  .github/workflows/tox.yml
  examples/yamllint/multi-document.yaml
  src/ansiblelint/rules/yaml.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
Labels: enhancement

#2291 Prevent occasional FileNotFoundError when removing the .lock file
  src/ansiblelint/__main__.py
Labels: bug

#2292 Allow single letter role names
  src/ansiblelint/rules/role_name.py
Labels: bug

#2293 Prevent duplicate warnings about deprecated tags
  src/ansiblelint/skip_utils.py
Labels: bug

#2287 Prevent other rules from running on invalid yaml files
  .pre-commit-config.yaml
  examples/broken/yaml-with-tabs/invalid-due-tabs.yaml
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
Labels: bug

#2294 Ensure eco pipeline cloning works with submodules
  test/test_eco.py
Labels: skip-changelog

#2297 Implement PEP-563
  examples/rules/task_has_tag.py
  pyproject.toml
  src/ansiblelint/__init__.py
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/app.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_command_syntax.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/git_latest.py
  src/ansiblelint/rules/hg_latest.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_nesting.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_loop_var_prefix.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/testing/__init__.py
  test/conftest.py
  test/test_skiputils.py
Labels: skip-changelog

#2298 Minor linting fixes
  .flake8
  .pre-commit-config.yaml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/yaml_utils.py
  test/test_runner.py
Labels: skip-changelog

#2299 Make ruamel.yaml annotation implicit for yaml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#2296 Change meta rules to use matchyaml instead of matchplay
  examples/roles/meta_noqa/meta/main.yml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  test/test_skip_inside_yaml.py
Labels: bug

#2302 Prepare fixtures for upcoming name[play] rule
  examples/playbooks/become.transformed.yml
  examples/playbooks/become.yml
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/common-include-1.yml
  examples/playbooks/common-include-2.yml
  examples/playbooks/contains_secrets.transformed.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/custom_module.yml
  examples/playbooks/example.yml
  examples/playbooks/include-import-tasks-in-role.yml
  examples/playbooks/include-in-block.yml
  examples/playbooks/lots_of_warnings.transformed.yml
  examples/playbooks/lots_of_warnings.yml
  examples/playbooks/nomatchestest.transformed.yml
  examples/playbooks/nomatchestest.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/rule-only-builtins.yml
  examples/playbooks/task-has-name-success.yml
  examples/playbooks/task-name-lowercase.yml
  examples/playbooks/taskimports.yml
  examples/playbooks/taskincludes.yml
  examples/playbooks/unicode.transformed.yml
  examples/playbooks/unicode.yml
  examples/playbooks/valid_with_alt_extension.yaml
  src/ansiblelint/rules/command_instead_of_shell.py
  test/rules/test_nested_jinja_rule.py
  test/test_ansiblesyntax.py
  test/test_import_include_role.py
  test/test_include_miss_file_with_role.py
  test/test_skip_import_playbook.py
  test/test_skip_inside_yaml.py
  test/test_skip_playbook_items.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2303 Fix ansible-lint pre-commit hook
  .github/workflows/tox.yml
  .pre-commit-hooks.yaml
  examples/playbooks/valid.yml
  tox.ini
Labels: bug

#2307 Remove pytest from default dependencies
  .readthedocs.yml
  setup.cfg
  tox.ini
Labels: bug

#2308 Avoid early of splitting shorthand string
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/utils.py
Labels: bug

#2309 Update configuration schema
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: skip-changelog

#2310 Avoid erroring with empty vars files
  .github/workflows/tox.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: bug

#2311 Allow use of jinja with no_log
  src/ansiblelint/rules/no_log_password.py
Labels: bug

#2306 Reimplement jinja[spacing] to avoid use of regex
  .config/dictionary.txt
  .github/workflows/tox.yml
  examples/playbooks/jinja-spacing.yml
  examples/playbooks/vars/jinja-spacing.yml
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/jinja.py
  test/rules/test_nested_jinja_rule.py
Labels: bug

#2315 Enable flake9-future-annotations
  .pre-commit-config.yaml
  docs/conf.py
  docs/rules_table_generator_ext.py
  requirements.txt
  setup.cfg
  src/ansiblelint/_mockings.py
  src/ansiblelint/cli.py
  src/ansiblelint/color.py
  src/ansiblelint/config.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/fqcn_builtins.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/text.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/rules/fixtures/raw_task.py
  test/rules/test_role_names.py
  test/test_ansiblelintrule.py
  test/test_cli_role_paths.py
  test/test_commandline_invocations_same_as_config.py
  test/test_file_path_evaluation.py
  test/test_file_utils.py
  test/test_formatter_base.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_import_include_role.py
  test/test_runner.py
  test/test_transform_mixin.py
  test/test_transformer.py
  test/test_utils.py
  test/test_verbosity.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2295 Add name[play] rule that checks for names on plays
  .github/workflows/tox.yml
  examples/playbooks/play-name-missing.yml
  examples/playbooks/task-has-name-failure.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
  test/test_skiputils.py
Labels: bug, enhancement

#2319 Fix subprocess.run for progressive mode
  src/ansiblelint/__main__.py
Labels: bug

#2326 Ignore failures to upload codecov results
  .github/workflows/tox.yml
Labels: skip-changelog

#2327 command-instead-of-module: allow `systemctl --version`
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#2328 jinja[spacing]: fix negative numbers inside arrays
  .github/workflows/tox.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2329 jinja[spacing]: Avoid evaluating noqa comments
  src/ansiblelint/yaml_utils.py
Labels: bug

#2331 jinja[spacing] Ensure ~ is correctly spaced
  .github/workflows/tox.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2332 Pass codecov token to action
  .github/workflows/tox.yml
Labels: skip-changelog

#2334 jinja[spacing] recognize keywords with implicit templating
  .github/workflows/tox.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2336 jinja[spacing]: Include in default warn_list until it matures
  src/ansiblelint/config.py
Labels: bug

#2341 Removed internal test fixture
  examples/playbooks/play_miss_include.yml
  examples/playbooks/tasks/conflicting-action-statements.yml
  examples/playbooks/tasks/malformed.yml
  examples/playbooks/test_import_with_conflicting_action_statements.yml
  examples/playbooks/test_import_with_malformed.yml
  examples/playbooks/test_include_inplace.yml
  examples/playbooks/test_include_relative.yml
  examples/roles/include_in_the_place/tasks/included_file.yml
  examples/roles/include_in_the_place/tasks/main.yml
  examples/roles/include_miss/tasks/main.yml
  examples/roles/include_relative/tasks/included_file.yml
  examples/roles/include_relative/tasks/main.yml
  src/ansiblelint/testing/fixtures.py
  test/test_import_tasks.py
  test/test_import_with_malformed.py
  test/test_include_miss_file_with_role.py
Labels: skip-changelog

#2342 Prefer running tests with offline mode
  src/ansiblelint/testing/__init__.py
Labels: skip-changelog

#2339 Avoid importing fixtures as plugins
  conftest.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/conftest.py
  src/ansiblelint/rules/no_changed_when.py
  test/conftest.py
Labels: skip-changelog

#2344 Replace pytest-cov with coverage.py
  .config/dictionary.txt
  .coveragerc
  .github/workflows/tox.yml
  conftest.py
  pyproject.toml
  requirements.txt
  setup.cfg
  tox.ini
Labels: skip-changelog

#2347 name[casing]: now applies only to scripts supporting uppercase
  examples/playbooks/task-name-lowercase.yml
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
Labels: bug

#2348 Refactor some test fixtures out of the source
  .github/workflows/tox.yml
  examples/playbooks/test_skip_inside_yaml.yml
  test/test_skip_inside_yaml.py
Labels: skip-changelog

#2349 Ensure libyaml presence during testing
  .config/dictionary.txt
  .github/workflows/tox.yml
  conftest.py
  tools/test-setup.sh
Labels: skip-changelog

#2350 Make use of libyaml when possible
  src/ansiblelint/cli.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/schema.py
Labels: bug

#2351 Add documentation for syntax-check rule
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/syntax_check.md
  src/ansiblelint/rules/syntax_check.py
Labels: skip-changelog

#2352 Documentation refactoring
  .gitignore
  .readthedocs.yml
  docs/conf.py
  docs/contributing.md
  docs/custom-rules.md
  docs/default_rules.md
  docs/index.md
  docs/philosophy.md
  docs/profiles.md
  docs/rules.md
  docs/rules/.gitignore
  docs/rules_table_generator_ext.py
  docs/usage.md
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/cli.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/deprecated_bare_vars.md
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/syntax_check.md
  src/ansiblelint/rules/yaml.md
  tox.ini
Labels: skip-changelog

#2353 Include links to documentation for default output
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
Labels: bug

#2354 key-order: improve documentation
  src/ansiblelint/rules/key_order.md
Labels: bug

#2355 command-instead-of-module: improve documentation
  src/ansiblelint/rules/command_instead_of_module.md
Labels: bug

#2356 command-instead-of-module: improve documentation
  src/ansiblelint/rules/command_instead_of_shell.md
Labels: bug

#2360 deprecated-command: add documentation
  src/ansiblelint/rules/deprecated_command_syntax.md
Labels: bug, deprecated

#2361 deprecated-local-action: add documentation
  src/ansiblelint/rules/deprecated_local_action.md
Labels: bug

#2359 name[play]: now also correctly works with import_playbook blocks
  src/ansiblelint/rules/name.py
  test/test_skip_import_playbook.py
Labels: bug

#2364 Handle FileNotFoundError caused by processing new file in progressive mode
  src/ansiblelint/file_utils.py
Labels: bug

#2362 Refactor rule loading so we can correctly load markdown help files
  docs/index.md
  src/ansiblelint/_internal/internal_error.md
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/constants.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/deprecated_command_syntax.md
  test/rules/fixtures/raw_task.md
  test/rules/fixtures/raw_task.py
  test/test_lint_rule.py
  test/test_rules_collection.py
  test/test_verbosity.py
Labels: bug

#2323 Add a 60s timeout for lock.aquire()
  src/ansiblelint/__main__.py
  src/ansiblelint/constants.py
Labels: bug

#2367 Move ansible-lint config schema inside our repo
  src/ansiblelint/config.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: bug

#2370 Increase lock timeout to 120s
  src/ansiblelint/__main__.py
Labels: bug

#2366 Replace git-latest and hg-latest with latest rule
  .ansible-lint
  examples/playbooks/noqa.yml
  examples/playbooks/skiptasks.yml
  examples/playbooks/test_skip_inside_yaml.yml
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/git_latest.py
  src/ansiblelint/rules/hg_latest.py
  src/ansiblelint/rules/latest.md
  src/ansiblelint/rules/latest.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_rules_collection.py
  test/test_skip_inside_yaml.py
  test/test_skip_playbook_items.py
  test/test_skiputils.py
Labels: bug

#2371 Use lockfile feature only when not in offline mode
  src/ansiblelint/__main__.py
Labels: bug

#2365 Avoid resource leak warning with multiprocessing Semaphore
  src/ansiblelint/runner.py
Labels: bug

#2372 Allow us to manage documentation redirects
  .github/workflows/redirects.yml
  docs/conf.py
  docs/redirects.yml
  tox.ini
Labels: skip-changelog

#2373 Correct documentation icons
  docs/conf.py
Labels: bug
