Repository ansible/ansible-lint, pull requests merged in 2022-02, with the labels that each got.

#1841 Correcting formatting of sample .ansible-lint config
  .ansible-lint
Labels: bug

#1837 Strip ./ from discover_lintables results
  src/ansiblelint/file_utils.py
Labels: bug

#1821 Neuter min space requirement for inline comments
  src/ansiblelint/rules/YamllintRule.py
Labels: enhancement

#1845 Fix for pip-tools 6.5.0
  constraints.txt
  docs/requirements.txt
  tox.ini
Labels: skip-changelog

#1844 Add json schema validator for workflows
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#1848 ci: simplify job names
  .github/workflows/tox.yml
Labels: skip-changelog

#1849 ci: upgrade test deps
  .pre-commit-config.yaml
  constraints.txt
  docs/requirements.in
  docs/requirements.txt
  setup.cfg
  tox.ini
Labels: skip-changelog

#1843 Enable testing using WSL1
  .github/workflows/tox.yml
  tools/test-setup.sh
Labels: skip-changelog

#1852 Fix broken documentation theme
  docs/requirements.in
  docs/requirements.txt
Labels: skip-changelog

#1856 test: correct codecov config
  codecov.yml
Labels: skip-changelog

#1858 Move `__main__.report_outcome()` to `App.report_outcome()`
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
Labels: skip-changelog

#1859 Avoid false positive with git lfs command
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
Labels: bug

#1857 test: replace eco playbook with pytest tests
  .pre-commit-config.yaml
  playbooks/eco.yml
  pytest.ini
  test/eco/bootstrap.result
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/tripleo-ansible.result
  test/eco/zuul-jobs.result
  test/test_eco.py
  tox.ini
Labels: skip-changelog

#1868 Simplify use of check_ansible_presence
  src/ansiblelint/__main__.py
Labels: skip-changelog

#1870 Avoid running code on ansiblelint.config import
  src/ansiblelint/config.py
  src/ansiblelint/prerun.py
Labels: bug

#1860 Allow use without activation of virtualenv
  src/ansiblelint/__main__.py
  test/test_main.py
Labels: bug

#1873 Move tests for file_utils out of generic TestUtils file
  test/TestUtils.py
  test/test_file_utils.py
Labels: skip-changelog

#1874 Upgrade mypy
  .pre-commit-config.yaml
  src/ansiblelint/errors.py
  src/ansiblelint/prerun.py
Labels: skip-changelog

#1864 Simplify `App.report_outcome()`
  src/ansiblelint/app.py
Labels: skip-changelog

#1850 Remove support for py36 and py37
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: major

#1883 Spellcheck fixes
  docs/custom-rules.rst
  examples/playbooks/example.yml
  examples/playbooks/lots_of_warnings.yml
  src/ansiblelint/errors.py
  src/ansiblelint/prerun.py
  src/ansiblelint/rules/MetaMainHasInfoRule.py
  src/ansiblelint/rules/NoLogPasswordsRule.py
  src/ansiblelint/runner.py
  test/TestMatchError.py
  test/TestSkipInsideYaml.py
  test/TestUseHandlerRatherThanWhenChanged.py
  test/__init__.py
  test/conftest.py
Labels: bug

#1881 Made yamllint a direct dependency
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  constraints.txt
  docs/installing.rst
  docs/requirements.txt
  setup.cfg
  src/ansiblelint/rules/YamllintRule.py
  tox.ini
Labels: major

#1886 Spellcheck fixes
  .flake8
  .github/CONTRIBUTING.rst
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/tox.yml
  README.rst
  examples/playbooks/example.yml
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  examples/roles/role_with_task_inclusions/tasks/main.yml
  pytest.ini
  setup.cfg
  src/ansiblelint/cli.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/PackageIsNotLatestRule.py
  src/ansiblelint/rules/ShellWithoutPipefail.py
  src/ansiblelint/utils.py
  test/TestLineTooLong.py
  test/TestLintRule.py
  test/TestMetaVideoLinks.py
  test/test_prerun.py
  test/test_skiputils.py
Labels: skip-changelog

#1889 Remove outdated ruamel-yaml version constraints
  constraints.txt
  docs/requirements.txt
  setup.cfg
Labels: bug

#1891 Remove deprecated pytest hook
  conftest.py
  tox.ini
Labels: skip-changelog

#1890 Bump test dependencies
  constraints.txt
  docs/requirements.txt
  tox.ini
Labels: skip-changelog

#1888 Made ansible-core a direct dependency
  .github/workflows/tox.yml
  constraints.txt
  docs/installing.rst
  setup.cfg
  tools/check-missing-ansible.py
  tox.ini
Labels: major

#1892 Consolidate docs building into a single job
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#1893 More spell checks
  examples/playbooks/include.yml
  examples/roles/more_complex/handlers/main.yml
  examples/roles/more_complex/tasks/main.yml
  test/local-content/collections/ansible_collections/testns/test_collection/galaxy.yml
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/modules/test_module_2.py
  test/local-content/test-collection.yml
  test/test_file_utils.py
Labels: skip-changelog

#1902 More spell-checking
  .flake8
  examples/playbooks/block.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/unicode.yml
  examples/playbooks/var-spacing.yml
  examples/roles/dependency_in_meta/meta/main.yml
  pytest.ini
  src/ansiblelint/cli.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  src/ansiblelint/rules/DeprecatedModuleRule.py
  src/ansiblelint/rules/FQCNBuiltinsRule.py
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  src/ansiblelint/rules/VariableHasSpacesRule.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog

#1901 Remove outdated bindep.txt
  bindep.txt
Labels: skip-changelog

#1898 Removed --parseable-severity feature
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/VariableNamingRule.py
Labels: major

#1906 Remove tenacity dependency
  .pre-commit-config.yaml
  constraints.txt
  docs/requirements.txt
  setup.cfg
  src/ansiblelint/prerun.py
Labels: skip-changelog, enhancement

#1887 Enable cspell
  .config/dictionary.txt
  .pre-commit-config.yaml
  cspell.config.yaml
Labels: skip-changelog

#1884 Enable Lintables to be modified
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: feature

#1909 Moved some pytest options to tox
  pytest.ini
  tox.ini
Labels: skip-changelog

#1912 Do not force pytest to always run all tests
  pytest.ini
Labels: skip-changelog

#1915 Add .idea to gitignore
  .gitignore
Labels: skip-changelog

#1913 Use pathlib methods instead of `open()` in Lintable
  src/ansiblelint/file_utils.py
Labels: skip-changelog

#1914 Fix test integration with IDEs
  .config/dictionary.txt
  pytest.ini
  tox.ini
Labels: bug

#1917 Adapted tests to follow fqcn-builtins rule
  examples/playbooks/become-user-without-become-failure.yml
  examples/playbooks/become-user-without-become-success.yml
  examples/playbooks/become.yml
  examples/playbooks/block.yml
  examples/playbooks/command-check-failure.yml
  examples/playbooks/command-check-success.yml
  examples/playbooks/common-include-2.yml
  examples/playbooks/conflicting_action.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/ematcher-rule.yml
  examples/playbooks/example.yml
  examples/playbooks/include.yml
  examples/playbooks/jinja2-when-failure.yml
  examples/playbooks/jinja2-when-success.yml
  examples/playbooks/lots_of_warnings.yml
  examples/playbooks/multiline-brackets-do-not-match-test.yml
  examples/playbooks/multiline-bracketsmatchtest.yml
  examples/playbooks/nomatches.yml
  examples/playbooks/nomatchestest.yml
  examples/playbooks/package-check-failure.yml
  examples/playbooks/package-check-success.yml
  examples/playbooks/pass-loop-var-prefix.yml
  examples/playbooks/play.yml
  examples/playbooks/rule-no-tabs.yml
  examples/playbooks/skiptasks.yml
  examples/playbooks/syntax-error.yml
  examples/playbooks/task-has-name-failure.yml
  examples/playbooks/task-has-name-success.yml
  examples/playbooks/unicode.yml
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  test/TestFilePathEvaluation.py
  test/TestNestedJinjaRule.py
Labels: skip-changelog

#1918 Removed unused VALID_KEYS
  src/ansiblelint/utils.py
Labels: skip-changelog

#1854 Make FQCN import tasks include their relevant files for checking
  examples/playbooks/taskimports.yml
  examples/playbooks/taskincludes.yml
  examples/playbooks/tasks/passing_task.yml
  src/ansiblelint/utils.py
  test/TestTaskIncludes.py
Labels: bug

#1916 Improve contributor experience
  .gitignore
  conftest.py
  constraints.txt
  setup.cfg
Labels: skip-changelog, enhancement

#1920 Finalize removal of ansible code pre-2.12
  setup.cfg
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/prerun.py
  src/ansiblelint/utils.py
Labels: skip-changelog, bug

#1921 Normalize format of non-test yaml files
  .github/ISSUE_TEMPLATE/config.yml
  .github/dependabot.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  .prettierignore
  .readthedocs.yml
Labels: skip-changelog

#1922 Normalize format of yaml fixtures
  .pre-commit-config.yaml
  test/fixtures/ansible-config.yml
  test/fixtures/config-with-relative-path.yml
  test/fixtures/exclude-paths-with-expands.yml
  test/fixtures/exclude-paths.yml
  test/fixtures/parseable.yml
  test/fixtures/quiet.yml
  test/fixtures/rulesdir-defaults.yml
  test/fixtures/rulesdir.yml
  test/fixtures/show-abspath.yml
  test/fixtures/show-relpath.yml
  test/fixtures/skip-tags.yml
  test/fixtures/tags.yml
  test/fixtures/verbosity.yml
Labels: skip-changelog

#1924 Normalize format of yaml examples
  .pre-commit-config.yaml
  examples/galaxy.yml
  examples/lineno.yml
  examples/playbooks/become-user-without-become-failure.yml
  examples/playbooks/become-user-without-become-success.yml
  examples/playbooks/become.yml
  examples/playbooks/block.yml
  examples/playbooks/command-check-failure.yml
  examples/playbooks/command-check-success.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/include.yml
  examples/playbooks/lots_of_warnings.yml
  examples/playbooks/norole.yml
  examples/playbooks/package-check-failure.yml
  examples/playbooks/package-check-success.yml
  examples/playbooks/play.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/skiptasks.yml
  examples/playbooks/task-has-name-failure.yml
  examples/playbooks/task-has-name-success.yml
  examples/playbooks/tasks/include-in-block-inner.yml
  examples/playbooks/tasks/x.yml
  examples/playbooks/using-bare-variables-success.yml
  examples/playbooks/valid_with_alt_extension.yaml
  examples/playbooks/var-spacing.yml
  examples/roles/dependency_in_meta/meta/main.yml
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
Labels: skip-changelog

#1925 Enable prettier for all supported formats
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .pre-commit-config.yaml
  .vscode/extensions.json
  DCO_1_1.md
  docs/_static/theme_overrides.css
Labels: skip-changelog

#1926 Add `--write` option for upcoming reformat/transform features
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/transformer.py
Labels: feature

#1930 Enable TOML formatting
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#1931 Improve version handling
  .gitignore
  pyproject.toml
  src/ansiblelint/version.py
Labels: enhancement

#1932 Adopted more ansible.builtin.
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/common-include-1.yml
  examples/playbooks/include-in-block.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/playbook-parent.yml
  examples/playbooks/tasks/directory with spaces/main.yml
  examples/playbooks/tasks/included-with-lint.yml
  examples/playbooks/tasks/passing_task.yml
  examples/playbooks/tasks/simple_task.yml
  examples/playbooks/var-spacing.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  examples/roles/role_with_task_inclusions/tasks/imported_tasks.yml
  examples/roles/role_with_task_inclusions/tasks/included_tasks.yml
  src/ansiblelint/rules/UseCommandInsteadOfShellRule.py
  test/TestSkipImportPlaybook.py
  test/TestSkipInsideYaml.py
  test/TestSkipPlaybookItems.py
  test/test_skiputils.py
Labels: skip-changelog

#1934 Add formatting fixtures
  .config/dictionary.txt
  .gitignore
  .pre-commit-config.yaml
  .prettierrc
  test/fixtures/formatting-after/fmt-1.yml
  test/fixtures/formatting-before/fmt-1.yml
Labels: skip-changelog

#1935 Prevent KeyError[0] exception with ansible.builtin.include_tasks
  src/ansiblelint/utils.py
Labels: bug

#1648 Use packit to produce rpms for fedora-35
  .config/ansible-lint.spec
  .gitignore
  .packit.yaml
  mypy.ini
  setup.cfg
  src/ansiblelint/version.py
  tools/get-version.sh
  tools/update-version.sh
Labels: feature, AAP

#1939 Avoid type errors with older sphinx
  .pre-commit-config.yaml
  docs/rules_table_generator_ext.py
Labels: skip-changelog

#1942 Add json alias for codeclimate formatter
  docs/usage.rst
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
Labels: enhancement

#1944 Copy files for Transformer tests without any changes
  examples/playbooks/become.transformed.yml
  examples/playbooks/contains_secrets.transformed.yml
  examples/playbooks/lots_of_warnings.transformed.yml
  examples/playbooks/nomatchestest.transformed.yml
  examples/playbooks/unicode.transformed.yml
Labels: skip-changelog

#1875 Restore WSL1 testing with windows-2019
  .github/workflows/tox.yml
Labels: skip-changelog
