Repository ansible/ansible-lint, pull requests merged in 2022-05, with the labels that each got.

#2077 Relax the yamllint rules on spaces inside braces for flow mappings
  .flake8
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-1.yml
  test/fixtures/formatting-before/fmt-1.yml
  test/fixtures/formatting-prettier/fmt-1.yml
  test/test_yaml_utils.py
Labels: bug

#2095 updating cspell config
  .config/ansible-lint.spec
  cspell.config.yaml
  docs/conf.py
Labels: skip-changelog

#2092 --write: Do not rewrite zero 0 as octal 00
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-2.yml
  test/fixtures/formatting-before/fmt-2.yml
  test/fixtures/formatting-prettier/fmt-2.yml
Labels: bug

#2089 remove superfluous flake8 rule ignores
  .flake8
Labels: skip-changelog

#2096 Ensure tags are escaped when printed
  .github/workflows/tox.yml
  src/ansiblelint/formatters/__init__.py
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/zuul-jobs.result
  test/test_utils.py
Labels: bug

#2093 Add no-prompting rule as experimental
  .github/workflows/tox.yml
  examples/playbooks/no-prompting.yml
  src/ansiblelint/rules/no_prompting.py
Labels: enhancement

#2081 chore: improve output of github actions
  .github/workflows/tox.yml
Labels: skip-changelog

#2099 Improve cli argument handling
  .github/workflows/tox.yml
  docs/rules.rst
  src/ansiblelint/cli.py
  src/ansiblelint/rules/__init__.py
  test/fixtures/list-rules-tests/.yamllint
  test/test_list_rules.py
Labels: enhancement

#2031 Make sure all tasks get evaluated by matchtask including block/always/rescue and nested tasks
  .github/workflows/tox.yml
  src/ansiblelint/rules/unnamed_task.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/utils.py
  test/eco/colsystem.result
  test/test_utils.py
Labels: bug

#2107 Fix support for block tasks in unnamed-task rule
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  src/ansiblelint/rules/unnamed_task.py
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/zuul-jobs.result
  test/test_task_includes.py
Labels: bug

#2114 Bump test dependencies
  requirements.txt
Labels: skip-changelog

#2035 Implement JSON Schema verification for several known file types
  .config/dictionary.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  conftest.py
  cspell.config.yaml
  examples/galaxy.yml
  examples/playbooks/command-check-failure.yml
  examples/playbooks/json-schema-fail.yml
  examples/playbooks/schema-error-string.yml
  examples/playbooks/syntax-error-string.yml
  examples/playbooks/vars/invalid_vars_schema.yml
  examples/roles/dependency_in_meta/meta/main.yml
  examples/roles/invalid_due_to_meta/meta/main.yml
  examples/roles/invalid_meta_schema/meta/main.yml
  examples/roles/invalid_requirements_schema/meta/requirements.yml
  examples/roles/invalud_meta_schema
  examples/roles/valid-due-to-meta/meta/main.yml
  requirements.txt
  setup.cfg
  src/ansiblelint/config.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  src/ansiblelint/schemas/execution-environment.json
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/inventory.json
  src/ansiblelint/schemas/meta-runtime.json
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/requirements.json
  src/ansiblelint/schemas/vars.json
  test/eco/bootstrap.result
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/zuul-jobs.result
  test/test_examples.py
  test/test_rules_collection.py
  test/test_skip_inside_yaml.py
  test/test_utils.py
Labels: skip-changelog, feature, enhancement

#2119 Allow use of empty files as valid config files
  src/ansiblelint/cli.py
Labels: bug

#2122 Run schema update as a separated command
  conftest.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/ansible-navigator-config.json
  src/ansiblelint/schemas/meta.json
  test/eco/debops.result
  tox.ini
Labels: skip-changelog

#2115 Fix offline mode
  .pre-commit-config.yaml
  examples/playbooks/rule-only-builtins.yml
  setup.cfg
  src/ansiblelint/__main__.py
  src/ansiblelint/_mockings.py
  src/ansiblelint/app.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/eco/zuul-jobs.result
Labels: bug

#2108 Add rule to check key order
  .github/workflows/tox.yml
  src/ansiblelint/rules/key_order.py
  test/eco/zuul-jobs.result
  test/test_rules_collection.py
Labels: enhancement

#2125 schema: add ability to recognize meta/runtime.yml files
  .github/workflows/tox.yml
  examples/broken_collection_meta_runtime/meta/runtime.yml
  examples/meta/runtime.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.py
Labels: enhancement

#2126 schema: add ability to recognize yaml inventory files
  .github/workflows/tox.yml
  examples/inventory/broken_dev_inventory.yml
  examples/inventory/production.yml
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/inventory.json
Labels: enhancement

#2127 schema: add ability to recognize ansible-lint config files
  .github/workflows/tox.yml
  examples/.config/ansible-lint.yml
  examples/broken/.ansible-lint
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.py
Labels: enhancement

#2128 schema: add support for ansible-navigator config files
  .github/workflows/tox.yml
  examples/ansible-navigator.yml
  examples/broken/ansible-navigator.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.py
Labels: enhancement

#2129 Avoid altering PATH when not needed
  src/ansiblelint/__main__.py
Labels: bug

#2131 schema: add validation of argument_specs.yml files
  .github/workflows/tox.yml
  examples/roles/broken_argument_specs/meta/argument_specs.yml
  examples/roles/hello/meta/argument_specs.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/arg_specs.json
Labels: enhancement

#2133 schema: enable validation of playbook and tasks files
  examples/playbooks/example.yml
  src/ansiblelint/config.py
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/zuul-jobs.result
  test/test_examples.py
Labels: enhancement

#2136 Notify eco repository owners when needed
  .github/workflows/tox.yml
  .gitignore
  test/eco/CODENOTIFY
Labels: skip-changelog

#2138 Update JSON Schemas
  src/ansiblelint/schemas/arg_specs.json
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/inventory.json
  src/ansiblelint/schemas/meta-runtime.json
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/requirements.json
  src/ansiblelint/schemas/tasks.json
Labels: bug

#2139 Change custom yamllint config logging to debug
  .github/workflows/tox.yml
  src/ansiblelint/yaml_utils.py
  test/eco/bootstrap.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/zuul-jobs.result
  test/test_verbosity.py
Labels: bug

#2137 Convert documentation to markdown
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING.rst
  docs/conf.py
  docs/configuring.md
  docs/configuring.rst
  docs/contributing.md
  docs/contributing.rst
  docs/custom-rules.md
  docs/custom-rules.rst
  docs/index.md
  docs/installing.md
  docs/installing.rst
  docs/philosophy.md
  docs/rules.md
  docs/rules.rst
  docs/usage.md
Labels: bug

#2143 Avoid failing check job when codenotify fails
  .github/workflows/tox.yml
Labels: skip-changelog

#2146 Update schemas
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: bug

#2147 Recognize tower requirements.txt files
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: bug

#2144 Convert rules documentation to markdown
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/SECURITY.rst
  docs/conf.py
  docs/contributing.md
  docs/default_rules.md
  docs/default_rules.rst
  docs/rules.md
  docs/rules_table_generator_ext.py
  docs/usage.md
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/schema.py
  test/eco/hardening.result
  test/test_list_rules.py
Labels: enhancement

#2150 Avoid myst-parser bug on directives
  docs/rules.md
  docs/usage.md
Labels: skip-changelog

#2152 Properly raise load-failure when utf-8 decoding fails
  .github/workflows/tox.yml
  examples/broken/encoding.j2
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  test/eco/colsystem.result
  test/eco/hardening.result
  test/test_load_failure.py
Labels: bug

#2148 Improve yamllint messages and documentation
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/playbooks/with-skip-tag-id.yml
  examples/yamllint/invalid.yml
  examples/yamllint/valid.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/rules/yaml.py
  test/eco/colsystem.result
  test/eco/hardening.result
  test/test_with_skip_tagid.py
Labels: enhancement

#2158 Updated schemas
  src/ansiblelint/schemas/arg_specs.json
  test/eco/docker-rootless.result
  test/eco/hardening.result
Labels: bug

#2156 Avoid using meta schema on ansible-test integration tests
  src/ansiblelint/config.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#2160 Update schemas
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/eco/debops.result
  test/eco/zuul-jobs.result
Labels: bug

#2162 Fix duplicated is_nested_task()
  .github/workflows/tox.yml
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#2167 Avoid runtime warnings from ansible-playbook --syntax-check
  src/ansiblelint/rules/syntax_check.py
Labels: bug

#2177 Updated JSON Schemas
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/eco/debops.result
Labels: bug

#2176 Accept `shell` when `executable` is set
  src/ansiblelint/rules/command_instead_of_shell.py
Labels: bug
