Repository ansible/ansible-lint, pull requests merged in 2022-03, with the labels that each got.

#1946 Manage YAML comment indentation
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-3.yml
  test/fixtures/formatting-before/fmt-3.yml
  test/fixtures/formatting-prettier/fmt-3.yml
Labels: skip-changelog

#1947 Configure FormattedYAML using YamllintConfig
  docs/conf.py
  src/ansiblelint/rules/YamllintRule.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#1950 Standardize yaml quotes
  .ansible-lint
  .pre-commit-config.yaml
  examples/galaxy.yml
  examples/playbooks/become.yml
  examples/playbooks/block.yml
  examples/playbooks/blockincludes.yml
  examples/playbooks/blockincludes2.yml
  examples/playbooks/example.yml
  examples/playbooks/multiline-brackets-do-not-match-test.yml
  examples/playbooks/multiline-bracketsmatchtest.yml
  examples/playbooks/rule-no-tabs.yml
  examples/playbooks/syntax-error.yml
  examples/playbooks/task-has-name-failure.yml
  examples/playbooks/taskimports.yml
  examples/playbooks/taskincludes.yml
  examples/playbooks/using-bare-variables-success.yml
  examples/playbooks/valid_with_alt_extension.yaml
  examples/playbooks/var-spacing.yml
  examples/playbooks/with-skip-tag-id.yml
  examples/roles/dependency_in_meta/meta/main.yml
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  test/fixtures/skip-tags.yml
Labels: skip-changelog

#1952 Misc YAML formatting fixes
  examples/playbooks/with-skip-tag-id.yml
  examples/playbooks/with-umlaut-ä.yml
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-3.yml
  test/fixtures/formatting-before/fmt-3.yml
  test/fixtures/formatting-prettier/fmt-3.yml
Labels: skip-changelog

#1943 Add support for reformatting YAML files
  docs/conf.py
  examples/playbooks/become.transformed.yml
  examples/playbooks/vars/empty_vars.transformed.yml
  examples/playbooks/vars/empty_vars.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/transformer.py
  test/test_transformer.py
Labels: feature

#1953 Made empty-string-compare rule opt-in
  .ansible-lint
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  test/TestRulesCollection.py
Labels: bug

#1822 Add ability to load .config/ansible-lint.yml
  docs/configuring.rst
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  test/TestExamples.py
  test/TestUtils.py
Labels: enhancement

#1949 Apply MissingFilePermissionsRule to get_url module
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  test/TestSkipInsideYaml.py
Labels: bug

#1961 Add test case that shows how FormattedYAML breaks some strings
  .gitignore
  examples/playbooks/vars/strings.transformed.yml
  examples/playbooks/vars/strings.yml
  test/test_transformer.py
Labels: skip-changelog

#1958 Start using ansible-compat
  .config/dictionary.txt
  .pre-commit-config.yaml
  constraints.txt
  docs/requirements.txt
  setup.cfg
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
Labels: bug

#1956 Better protect strings with '#' when dumping YAML
  .gitignore
  docs/conf.py
  examples/playbooks/vars/strings.transformed.yml
  setup.cfg
  src/ansiblelint/transformer.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#1967 Refactor: Avoid redefining NESTED_TASK_KEYS and PLAYBOOK_TASK_KEYWORDS in multiple places
  src/ansiblelint/constants.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#1965 Add MatchError.match_type to record how the error was generated
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
Labels: skip-changelog

#1964 Refactor root sequence detection in FormattedEmitter
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#1963 packit: build SRPM in Copr
  .config/dictionary.txt
  .packit.yaml
Labels: skip-changelog

#1666 Adopt ansible-compat runtime
  src/ansiblelint/__init__.py
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/testing/__init__.py
  test/TestCliRolePaths.py
  test/TestVerbosity.py
Labels: skip-changelog, major

#1971 Remove unused code from prerun submodule
  src/ansiblelint/constants.py
  src/ansiblelint/prerun.py
  test/test_prerun.py
Labels: major

#1972 Rename prerun submodule to _mockings
  src/ansiblelint/_mockings.py
  src/ansiblelint/app.py
Labels: major

#1974 Partial fix for pylint invalid-name
  .flake8
  test/rules/__init__.py
  test/rules/fixtures/EMatcherRule.py
  test/rules/fixtures/RawTaskRule.py
  test/rules/fixtures/UnsetVariableMatcherRule.py
  test/rules/fixtures/__init__.py
  test/rules/test_become_user_without_become.py
  test/rules/test_comparison_to_literal_bool.py
  test/rules/test_deprecated_module.py
  test/rules/test_env_vars_in_command.py
  test/rules/test_line_too_long.py
  test/rules/test_meta_change_from_default.py
  test/rules/test_meta_main_has_info.py
  test/rules/test_meta_video_links.py
  test/rules/test_nested_jinja_rule.py
  test/rules/test_no_formatting_in_when_rule.py
  test/rules/test_octal_permissions.py
  test/rules/test_package_is_not_latest.py
  test/rules/test_role_names.py
  test/rules/test_role_relative_path.py
  test/rules/test_rule_command_has_changes_check.py
  test/rules/test_shell_without_pipefail.py
  test/rules/test_task_has_name.py
  test/rules/test_task_no_local_action.py
  test/rules/test_use_bare_variables.py
  test/rules/test_use_handler_rather_than_when_changed.py
  test/test_ansiblelintrule.py
  test/test_ansiblesyntax.py
  test/test_cli_role_paths.py
  test/test_commandline_invocations_same_as_config.py
  test/test_dependencies_in_meta.py
  test/test_examples.py
  test/test_file_path_evaluation.py
  test/test_formatter.py
  test/test_formatter_base.py
  test/test_formatter_json.py
  test/test_import_include_role.py
  test/test_import_playbook.py
  test/test_import_with_malformed.py
  test/test_include_miss_file_with_role.py
  test/test_lint_rule.py
  test/test_local_content.py
  test/test_matcherrror.py
  test/test_rule_properties.py
  test/test_rules_collection.py
  test/test_runner.py
  test/test_skip_import_playbook.py
  test/test_skip_inside_yaml.py
  test/test_skip_playbook_items.py
  test/test_task_includes.py
  test/test_utils.py
  test/test_verbosity.py
  test/test_with_skip_tagid.py
Labels: skip-changelog

#1975 More fixes for pylint invalid-name rule
  .pylintrc
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/AnsibleSyntaxCheckRule.py
  src/ansiblelint/rules/YamllintRule.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/local-content/test-roles-failed-complete/roles/role2/test_plugins/b_failed_complete.py
  test/local-content/test-roles-failed/roles/role2/test_plugins/b_failed.py
  test/local-content/test-roles-success/roles/role2/test_plugins/b_success.py
  test/rules/test_nested_jinja_rule.py
  test/test_skiputils.py
Labels: skip-changelog

#1976 More pylint invalid-name fixes
  .pylintrc
  docs/conf.py
  src/ansiblelint/__main__.py
  src/ansiblelint/_mockings.py
  src/ansiblelint/color.py
  src/ansiblelint/constants.py
  test/test_yaml_utils.py
Labels: skip-changelog

#1978 Load rule classes from any modules
  .config/dictionary.txt
  src/ansiblelint/rules/__init__.py
Labels: enhancement

#1979 Use latest release of pylint
  .pre-commit-config.yaml
  .pylintrc
  src/ansiblelint/color.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/modules/test_module_2.py
  test/local-content/test-roles-failed-complete/roles/role1/library/test_module_1_failed_complete.py
  test/local-content/test-roles-failed-complete/roles/role3/library/test_module_3_failed_complete.py
  test/local-content/test-roles-failed/roles/role1/library/test_module_1_failed.py
  test/local-content/test-roles-failed/roles/role3/library/test_module_3_failed.py
  test/local-content/test-roles-success/roles/role1/library/test_module_1_success.py
  test/local-content/test-roles-success/roles/role3/library/test_module_3_success.py
  test/test_ansiblelintrule.py
  test/test_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#1977 More pylint invalid-name fixes
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_command_syntax.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/fqcn_builtins.py
  src/ansiblelint/rules/git_latest.py
  src/ansiblelint/rules/hg_latest.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_nesting.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_loop_var_prefix.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/unnamed_task.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/var_spacing.py
  src/ansiblelint/rules/yaml.py
  src/ansiblelint/runner.py
  test/rules/test_become_user_without_become.py
  test/rules/test_comparison_to_literal_bool.py
  test/rules/test_deprecated_module.py
  test/rules/test_env_vars_in_command.py
  test/rules/test_line_too_long.py
  test/rules/test_meta_change_from_default.py
  test/rules/test_meta_main_has_info.py
  test/rules/test_meta_video_links.py
  test/rules/test_no_formatting_in_when_rule.py
  test/rules/test_octal_permissions.py
  test/rules/test_package_is_not_latest.py
  test/rules/test_role_names.py
  test/rules/test_role_relative_path.py
  test/rules/test_rule_command_has_changes_check.py
  test/rules/test_shell_without_pipefail.py
  test/rules/test_task_has_name.py
  test/rules/test_task_no_local_action.py
  test/rules/test_use_bare_variables.py
  test/rules/test_use_handler_rather_than_when_changed.py
  test/test_matcherrror.py
  test/test_with_skip_tagid.py
Labels: skip-changelog

#1980 Address pylint invalid-name rule
  .pylintrc
  docs/contributing.rst
  examples/rules/task_has_tag.py
  src/ansiblelint/testing/fixtures.py
  test/custom_rules/example_com/example_com_rule.py
  test/custom_rules/example_inc/custom_rule.py
  test/rules/fixtures/__init__.py
  test/rules/fixtures/ematcher.py
  test/rules/fixtures/raw_task.py
  test/rules/fixtures/unset_variable_matcher.py
  test/test_lint_rule.py
Labels: skip-changelog

#1982 Enable pylint broad-except rule
  .pylintrc
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/utils.py
  src/ansiblelint/version.py
Labels: skip-changelog

#1983 Address pylint redefined-outer-name
  .pylintrc
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/color.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/var_spacing.py
  src/ansiblelint/runner.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
  test/rules/test_role_names.py
  test/test_commandline_invocations_same_as_config.py
  test/test_file_utils.py
  test/test_import_include_role.py
  test/test_lint_rule.py
  test/test_rules_collection.py
  test/test_skip_import_playbook.py
  test/test_transformer.py
  test/test_yaml_utils.py
Labels: skip-changelog

#1984 Address pylint raise-missing-from
  .pylintrc
  src/ansiblelint/__main__.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#1985 Address pytest preferred-module for unittest 1/2
  test/rules/test_deprecated_local_action.py
  test/rules/test_meta_main_has_info.py
  test/rules/test_meta_no_info.py
  test/rules/test_meta_video_links.py
  test/rules/test_no_changed_when.py
  test/rules/test_no_formatting_in_when_rule.py
  test/rules/test_no_jinja_when.py
  test/rules/test_no_relative_paths.py
  test/rules/test_octal_permissions.py
  test/rules/test_package_is_not_latest.py
  test/rules/test_package_latest.py
  test/rules/test_risky_shell_pipe.py
  test/rules/test_rule_command_has_changes_check.py
  test/rules/test_task_has_name.py
  test/rules/test_task_no_local_action.py
  test/rules/test_unnamed_task.py
  test/rules/test_use_bare_variables.py
  test/rules/test_use_handler_rather_than_when_changed.py
  test/test_cli_role_paths.py
Labels: skip-changelog

#1986 Address pytest preferred-module for unittest 2/2
  src/ansiblelint/testing/__init__.py
  test/rules/test_become_user_without_become.py
  test/rules/test_comparison_to_literal_bool.py
  test/rules/test_deprecated_module.py
  test/rules/test_inline_env_var.py
  test/rules/test_line_too_long.py
  test/rules/test_literal_compare.py
  test/rules/test_meta_change_from_default.py
  test/test_formatter.py
  test/test_with_skip_tagid.py
Labels: skip-changelog

#1988 Update var-naming to allow names containing jinja2 templates
  src/ansiblelint/rules/var_naming.py
Labels: bug

#1987 Avoid accidental skip of tests
  .config/dictionary.txt
  .github/workflows/tox.yml
  constraints.txt
  pytest.ini
  setup.cfg
  tox.ini
Labels: skip-changelog

#1989 Address pylint bad-continuation
  .pylintrc
Labels: skip-changelog

#1990 Address pylint no-self-use
  .pylintrc
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/var_naming.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/local-content/test-roles-failed-complete/roles/role2/test_plugins/b_failed_complete.py
  test/local-content/test-roles-failed/roles/role2/test_plugins/b_failed.py
  test/local-content/test-roles-success/roles/role2/test_plugins/b_success.py
  test/test_matcherrror.py
Labels: skip-changelog

#1991 Address pylint inconsistent-return-statements
  .pylintrc
  src/ansiblelint/app.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#1992 Address pylint unspecified-encoding
  .pylintrc
  src/ansiblelint/_mockings.py
  src/ansiblelint/cli.py
  src/ansiblelint/loaders.py
  src/ansiblelint/testing/__init__.py
Labels: skip-changelog

#1994 Changed rules to use docstring as shortdesc
  docs/custom-rules.rst
  examples/rules/task_has_tag.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_command_syntax.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/fqcn_builtins.py
  src/ansiblelint/rules/git_latest.py
  src/ansiblelint/rules/hg_latest.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_nesting.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_loop_var_prefix.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/unnamed_task.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/var_spacing.py
  src/ansiblelint/rules/yaml.py
  test/rules/fixtures/ematcher.py
  test/rules/fixtures/unset_variable_matcher.py
Labels: enhancement

#1995 Minor documentation improvements
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/role_name.py
Labels: enhancement

#1996 Address pylint missing-class-docstring
  .pylintrc
  src/ansiblelint/cli.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  test/test_matcherrror.py
Labels: skip-changelog

#1998 Address pylint missing-function-docstring
  .pylintrc
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/risky_octal.py
Labels: skip-changelog, bug

#1999 Address pylint too-few-public-methods
  .pylintrc
  src/ansiblelint/transformer.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/local-content/test-roles-failed-complete/roles/role2/test_plugins/b_failed_complete.py
  test/local-content/test-roles-failed/roles/role2/test_plugins/b_failed.py
  test/local-content/test-roles-success/roles/role2/test_plugins/b_success.py
Labels: skip-changelog

#2000 Minor mypy improvements
  .pre-commit-config.yaml
  docs/conf.py
  mypy.ini
  plugins/modules/fake_module.py
Labels: skip-changelog

#1981 Remove html extension from documentation
  .config/dictionary.txt
  .readthedocs.yml
  README.rst
  docs/contributing.rst
  docs/default_rules.rst
Labels: enhancement

#2001 Address pytest too-many-* rules
  .pylintrc
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#2003 Address pylint no-member
  .config/dictionary.txt
  .pylintrc
  test/test_transformer.py
Labels: skip-changelog

#2004 More pylint fixes
  .pylintrc
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/utils.py
  test/rules/test_octal_permissions.py
  test/test_examples.py
  test/test_file_utils.py
  test/test_include_miss_file_with_role.py
  test/test_rules_collection.py
  test/test_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2005 Change invalid config return code to 3
  src/ansiblelint/app.py
  src/ansiblelint/constants.py
  test/test_commandline_invocations_same_as_config.py
  test/test_utils.py
Labels: major

#2006 Address pylint fixme
  .pylintrc
  src/ansiblelint/cli.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#2007 Address pylint protected-access
  .pylintrc
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_formatter_base.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2008 Address pylint dangerous-default-value
  .pylintrc
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
Labels: skip-changelog

#2009 Address pylint consider-using-f-string
  .pylintrc
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/rules/test_octal_permissions.py
  test/test_matcherrror.py
Labels: skip-changelog

#2012 Rename constraints.txt to requirements.txt
  .pre-commit-config.yaml
  cspell.config.yaml
  requirements.txt
  tox.ini
Labels: skip-changelog

#2016 Use only ansible-compat cache directory
  .pre-commit-config.yaml
  docs/requirements.txt
  requirements.txt
  setup.cfg
  src/ansiblelint/__main__.py
Labels: bug

#2018 Allow import_playbook from collections
  examples/playbooks/playbook-parent.yml
  requirements.yml
  src/ansiblelint/utils.py
Labels: bug

#2013 Fix eco job output
  .pre-commit-config.yaml
  docs/requirements.txt
  requirements.txt
  setup.cfg
  test/eco/bootstrap.result
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/tripleo-ansible.result
  test/eco/zuul-jobs.result
  test/test_eco.py
  tox.ini
Labels: skip-changelog, bug

#2019 Recognize import_tasks with file key
  examples/playbooks/common-include-1.yml
  examples/playbooks/playbook-parent.yml
  src/ansiblelint/utils.py
Labels: bug

#1970 Add YAML path (to play/task) discovery utils for Transforms to use
  .github/workflows/tox.yml
  examples/playbooks/tasks/empty_blocks.yml
  examples/playbooks/tasks/x.yml
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2021 Avoid processing files under templates
  .config/dictionary.txt
  examples/templates/playbooks/playbook.yml
  src/ansiblelint/config.py
Labels: bug

#2023 --write: Introduce TransformMixin for Rules
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/transformer.py
Labels: feature

#2022 --write: Avoid line-wrapping YAML flow objects
  src/ansiblelint/yaml_utils.py
Labels: enhancement

#2025 `--write`: Add `MatchError.yaml_path` for transforms
  .github/workflows/tox.yml
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/transformer.py
  test/test_transform_mixin.py
Labels: enhancement

#2029 Fix eco pipeline
  test/eco/debops.result
  test/eco/docker-rootless.result
Labels: skip-changelog

#2026 Remove ref to archived toolbox image from docs
  docs/installing.rst
Labels: bug

#2028 Allow normpath accept empty strings
  .github/workflows/tox.yml
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: bug

#2033 Fix eco pipeline
  test/eco/hardening.result
Labels: skip-changelog, bug

#2032 Adds more yamllint configuration paths
  src/ansiblelint/rules/yaml.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#2034 Recognize import_role and import_role when using fqcn
  .github/workflows/tox.yml
  src/ansiblelint/utils.py
  test/include-import-role.yml
  test/test_import_include_role.py
Labels: bug

#2049 Update eco colsystem test
  test/eco/colsystem.result
Labels: skip-changelog

#2044 Update IRC channel in CONTRIBUTING.rst and add matrix
  .github/CONTRIBUTING.rst
  docs/conf.py
Labels: skip-changelog, documentation

#2041 --write: Allow Transforms to mark MatchErrors as fixed
  src/ansiblelint/app.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
Labels: enhancement

#2053 Resolve click+black incompatibility
  .pre-commit-config.yaml
Labels: skip-changelog

#2054 Update pre-commit hooks
  .pre-commit-config.yaml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/skip_utils.py
Labels: skip-changelog

#2051 --write: Optionally pass rule names to --write in cli
  .ansible-lint
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/transformer.py
  test/fixtures/config-with-write-all.yml
  test/fixtures/config-with-write-none.yml
  test/fixtures/config-with-write-subset.yml
  test/test_commandline_invocations_same_as_config.py
  test/test_transformer.py
Labels: enhancement

#2055 update colsystem eco test
  test/eco/colsystem.result
Labels: skip-changelog
