Repository ansible/ansible-lint, pull requests merged in 2022-07, with the labels that each got.

#2223 Update schemas
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/eco/bootstrap.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
Labels: bug

#2227 chore: fix wsl pipeline
  .github/workflows/tox.yml
Labels: skip-changelog

#2218 Refactor no_loop_var_prefix rule to condense methods into matchtask()
  examples/roles/loop_var_prefix/tasks/fail.yml
  src/ansiblelint/rules/no_loop_var_prefix.py
Labels: bug

#2233 no-same-owner: refactor to use matchtask()
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  src/ansiblelint/rules/no_same_owner.py
Labels: bug

#2238 deprecated-local-action: refactor to use matchtask()
  .github/workflows/tox.yml
  src/ansiblelint/rules/deprecated_local_action.py
Labels: bug, deprecated, refactoring

#2243 Avoid testing ansible-core@devel with py38
  .github/workflows/tox.yml
Labels: bug

#2244 Refactor eco testing
  .gitignore
  test/eco/CODENOTIFY
  test/eco/bootstrap.result
  test/eco/cisco.nxos.result
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/tripleo-ansible.result
  test/eco/zuul-jobs.result
  test/test_eco.py
  tox.ini
Labels: skip-changelog

#2246 Avoid warnings about use of ansible-core@devel branch
  tox.ini
Labels: skip-changelog

#2249 Improve argument_specs matching pattern
  src/ansiblelint/config.py
Labels: bug

#2251 Add ability to use use sub-rule matches on skip or warn lists
  .ansible-lint
  src/ansiblelint/app.py
  src/ansiblelint/rules/yaml.md
Labels: bug

#2252 Upgrade jsonschema to 4.8.0
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
  src/ansiblelint/rules/schema.py
Labels: bug

#2245 Add initial support for rule profiles
  .github/workflows/tox.yml
  docs/index.md
  docs/profiles.md
  docs/rules_table_generator_ext.py
  mypy.ini
  setup.cfg
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/generate_docs.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/__init__.py
  test/test_profiles.py
Labels: feature
