Repository ansible/ansible-lint, pull requests merged in 2022-06, with the labels that each got.

#2192 Update schemas
  src/ansiblelint/schemas/ansible-lint-config.json
  test/eco/hardening.result
Labels: bug

#2187 Don't yield only-builtins on nested tasks like block
  src/ansiblelint/rules/only_builtins.py
Labels: bug

#2193 Update dependencies
  .pre-commit-config.yaml
  requirements.txt
Labels: bug

#2199 Ensure we require ansible-compat>=2.1.0
  setup.cfg
Labels: bug

#2180 Modify VariableHasSpacesRule to check for spaces around filters
  examples/playbooks/var-spacing.yml
  examples/playbooks/vars/var-spacing.yml
  src/ansiblelint/rules/var_spacing.md
  src/ansiblelint/rules/var_spacing.py
  test/eco/bootstrap.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/zuul-jobs.result
Labels: enhancement

#2197 Update eco pipeline
  .config/dictionary.txt
  test/eco/CODENOTIFY
  test/eco/bootstrap.result
  test/eco/cisco.nxos.result
  test/eco/debops.result
  test/eco/docker-rootless.result
  test/eco/hardening.result
  test/eco/zuul-jobs.result
  test/test_eco.py
Labels: skip-changelog

#2201 Mark load-failure violation as unskippable
  src/ansiblelint/_internal/rules.py
  test/eco/colsystem.result
Labels: bug

#2202 Avoid load-failure with nested task imports
  .github/workflows/tox.yml
  src/ansiblelint/utils.py
  test/eco/hardening.result
  test/test_file_path_evaluation.py
Labels: bug

#2206 Updated schemas
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/eco/debops.result
Labels: bug

#2211 Move test code for `partial-become` and `deprecated-local-action` into the rule file
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/partial_become.py
  test/rules/test_become_user_without_become.py
  test/rules/test_deprecated_local_action.py
Labels: skip-changelog

#2216 Add test for no-loop-var prefix rule
  .github/workflows/tox.yml
  examples/roles/loop_var_prefix/tasks/fail.yml
  examples/roles/loop_var_prefix/tasks/pass.yml
  src/ansiblelint/rules/no_loop_var_prefix.py
Labels: skip-changelog, test
