Repository ansible/ansible-lint, pull requests merged in 2022-12, with the labels that each got.

#2762 Fix eco pipeline
  test/test_eco.py
  tox.ini
Labels: skip-changelog

#2763 Update pip-tools
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  requirements.txt
  tox.ini
Labels: skip-changelog

#2760 Deprecate running under py38
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .readthedocs.yml
  mypy.ini
  src/ansiblelint/__main__.py
  test/test_profiles.py
Labels: bug

#2759 Refactor risky-octal and improve its messaging
  examples/playbooks/rule-risky-octal-fail.yml
  examples/playbooks/rule-risky-octal-pass.yml
  src/ansiblelint/rules/risky_octal.md
  src/ansiblelint/rules/risky_octal.py
  test/rules/test_octal_permissions.py
Labels: bug

#2764 Improve new bug form
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip-changelog

#2743 Removed dead code and add few no cover
  .github/workflows/tox.yml
  .gitignore
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/config.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
  src/ansiblelint/version.py
  test/test_internal_rules.py
  tox.ini
Labels: skip-changelog

#2740 Allow a prefix in subtasks names
  .ansible-lint
  .config/dictionary.txt
  .github/workflows/tox.yml
  examples/playbooks/tasks/include-in-block-inner.yml
  examples/playbooks/tasks/name-prefix-fail.yml
  examples/playbooks/tasks/nestedincludes.yml
  examples/playbooks/tasks/passing_task.yml
  examples/playbooks/tasks/simple_task.yml
  examples/roles/include_in_the_place/tasks/included_file.yml
  examples/roles/include_relative/tasks/included_file.yml
  examples/roles/loop_var_prefix/tasks/fail.yml
  examples/roles/loop_var_prefix/tasks/pass.yml
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_file_path_evaluation.py
  test/test_task_includes.py
Labels: bug

#2766 Some linting fixes
  .darglint
  .flake8
  .pre-commit-config.yaml
  .vscode/settings.json
  requirements.txt
  src/ansiblelint/rules/jinja.py
Labels: skip-changelog

#2768 Packit tuning
  .packit.yaml
Labels: skip-changelog

#2767 Rename some tests
  examples/playbooks/rule-name-casing.yml
  examples/playbooks/rule-name-missing-fail.yml
  examples/playbooks/rule-name-missing-pass.yml
  examples/playbooks/rule-name-play-fail.yml
  examples/playbooks/rule-name-templated-fail.yml
  examples/playbooks/rule-partial-become-without-become-fail.yml
  examples/playbooks/rule-partial-become-without-become-pass.yml
  examples/playbooks/tasks/rule-name-prefix-fail.yml
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/partial_become.py
  test/test_yaml_utils.py
Labels: skip-changelog

#2774 schema: allow jinja in diff keyword
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/package.json
  test/schemas/src/rebuild.py
  test/schemas/test/playbooks/tasks/diff.yml
Labels: bug

#2775 Fix multiline jinja pattern in schema
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/negative_test/playbooks/environment.yml.md
  test/schemas/negative_test/playbooks/ignore_errors.yml.md
  test/schemas/negative_test/playbooks/invalid-serial.yml.md
  test/schemas/negative_test/playbooks/invalid_become.yml.md
  test/schemas/negative_test/playbooks/no_log_partial_template.yml.md
  test/schemas/negative_test/playbooks/no_log_string.yml.md
  test/schemas/negative_test/playbooks/tasks/args_string.yml.md
  test/schemas/negative_test/playbooks/tasks/become_method_untemplated.yml.md
  test/schemas/negative_test/playbooks/tasks/ignore_errors.yml.md
  test/schemas/negative_test/playbooks/tasks/no_log_string.yml.md
  test/schemas/negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  test/schemas/test/playbooks/full-jinja.yml
Labels: bug

#2776 Allow var_naming_pattern in linter config schema
  .ansible-lint
  requirements.txt
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: bug

#2770 Add meta-unsupported-ansible rule for checking requires_ansible values
  .github/workflows/tox.yml
  conftest.py
  examples/meta_runtime_version_checks/fail_0/meta/runtime.yml
  examples/meta_runtime_version_checks/fail_1/meta/runtime.yml
  examples/meta_runtime_version_checks/pass/meta/runtime.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/meta_unsupported_ansible.md
  src/ansiblelint/rules/meta_unsupported_ansible.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_rules_collection.py
Labels: enhancement

#2783 Add OracleLinux to supported platforms and include version 8.7 and 9.1
  src/ansiblelint/schemas/meta.json
Labels: bug

#2787 Build fixes
  .github/workflows/tox.yml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#2788 Remove flaky
  .pre-commit-config.yaml
  conftest.py
  mypy.ini
  requirements.txt
  setup.cfg
  tox.ini
Labels: skip-changelog

#2790 Fix redirected links
  examples/inventory/inventory.yml
  examples/roles/dependency_in_meta/meta/main.yml
  src/ansiblelint/rules/no_relative_paths.md
  src/ansiblelint/rules/risky_file_permissions.md
  src/ansiblelint/rules/run_once.md
  src/ansiblelint/rules/schema.md
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/schemas/inventory.json
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/vars.json
  test/schemas/negative_test/inventory/broken_dev_inventory.yml
  test/schemas/test/inventory/inventory.yml
  test/schemas/test/roles/meta-tags/meta/main.yml
Labels: bug

#2791 Update schema etags
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/main.py
Labels: skip-changelog

#2794 Add has_jinja and has_glob to text module
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/text.py
  test/test_text.py
Labels: bug

#2749 Add a rule to validate module options
  .ansible-lint
  .config/dictionary.txt
  .github/workflows/tox.yml
  docs/conf.py
  examples/playbooks/.ansible-lint-only-builtins-allow
  examples/playbooks/rule-args-module-fail-1.yml
  examples/playbooks/rule-args-module-pass-1.yml
  examples/playbooks/rule-only-builtins.yml
  examples/playbooks/rule-validate-module-options-pass-2.yml
  src/ansiblelint/rules/args.md
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/only_builtins.py
  test/test_examples.py
  test/test_rules_collection.py
  test/test_skip_inside_yaml.py
  test/test_skip_playbook_items.py
Labels: feature, new rule

#2799 Make more use of offline mode
  docs/usage.md
Labels: skip-changelog

#2797 Use JSON Schema to validate own config file
  .github/workflows/tox.yml
  .vscode/settings.json
  examples/playbooks/.ansible-lint-only-builtins-allow
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/schemas/main.py
  src/ansiblelint/yaml_utils.py
  test/test_boot.py
Labels: bug

#2800 Avoid false positive with name[casing]
  .gitignore
  examples/playbooks/tasks/rule-name-prefix-fail.yml
  pytest.ini
  src/ansiblelint/rules/name.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#2806 Restore classic behavior of offline mode
  requirements.txt
  setup.cfg
Labels: bug

#2813 Fix args validation with setup module
  examples/playbooks/rule-args-module-fail-1.yml
  src/ansiblelint/rules/args.py
Labels: bug

#2818 Update changelog schema etag
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/main.py
Labels: bug

#2817 Update schema to accept a list for 'listen'
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/test/playbooks/run.yml
Labels: bug

#2821 Avoid running lookup filters while evaluating jinja2
  .github/workflows/tox.yml
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#2819 Fix test 'eco'
  test/test_eco.py
Labels: skip-changelog

#2792 Add caching for test collections
  .ansible-lint
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  ansible.cfg
  conftest.py
  examples/playbooks/collections/.gitignore
  examples/playbooks/collections/requirements.yml
  requirements.yml
  test/test_profiles.py
  tools/install-reqs.sh
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog

#2834 Complete schema for Antsibull changelogs
  examples/changelogs/changelog.yaml
  src/ansiblelint/config.py
  src/ansiblelint/schemas/changelog.json
  test/schemas/.mocharc.json
  test/schemas/negative_test/changelogs/invalid-date/changelogs/changelog.yaml
  test/schemas/negative_test/changelogs/invalid-date/changelogs/changelog.yaml.md
  test/schemas/negative_test/changelogs/invalid-plugin-namespace/changelogs/changelog.yaml
  test/schemas/negative_test/changelogs/invalid-plugin-namespace/changelogs/changelog.yaml.md
  test/schemas/negative_test/changelogs/list/changelogs/changelog.yaml
  test/schemas/negative_test/changelogs/list/changelogs/changelog.yaml.md
  test/schemas/negative_test/changelogs/no-semver/changelogs/changelog.yaml
  test/schemas/negative_test/changelogs/no-semver/changelogs/changelog.yaml.md
  test/schemas/negative_test/changelogs/unknown-keys/changelogs/changelog.yaml
  test/schemas/negative_test/changelogs/unknown-keys/changelogs/changelog.yaml.md
  test/schemas/test/changelog.yml
  test/schemas/test/changelogs/maximal/changelog.yaml
  test/schemas/test/changelogs/minimal/changelog.yaml
  test/schemas/test/changelogs/minimal/changelog.yml
  test/test_schemas.py
Labels: bug

#2839 Use dynamic matrix
  .github/workflows/tox.yml
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#2842 src/ansiblelint/schemas/meta.json: add openSUSE 15.5
  src/ansiblelint/schemas/meta.json
Labels: bug

#2840 Fix line number on var-naming error for 'register'
  examples/playbooks/rule-var-naming-fail.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#2823 Update documentation of `run_once` rule
  src/ansiblelint/rules/run_once.md
Labels: bug

#2836 name[template]: only trigger on word characters after the template
  examples/playbooks/rule-name-templated-fail.yml
  src/ansiblelint/rules/name.py
Labels: bug

#2847 Add the missing github_branch meta field
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/meta.json
Labels: bug

#2849 Use standalone extra files
  .config/requirements-docs.txt
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  .readthedocs.yml
  cspell.config.yaml
  pyproject.toml
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: skip-changelog

#2851 Update dependabot config
  .github/dependabot.yml
Labels: skip-changelog

#2852 Avoid TypeError NoneType with lookups
  .github/workflows/tox.yml
  examples/playbooks/find_children.yml
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug
