Repository ansible/ansible-lint, pull requests merged in 2022-11, with the labels that each got.

#2647 Fix offline mode
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: bug

#2657 Refactor tests
  test/test_examples.py
Labels: skip-changelog

#2676 Fix broken test
  src/ansiblelint/rules/var_naming.py
  test/test_utils.py
Labels: bug

#2679 Avoid pip constraints with py38
  tox.ini
Labels: skip-changelog

#2692 Update schemas
  src/ansiblelint/schemas/meta.json
Labels: bug

#2691 Perform mocking before installing dependencies
  src/ansiblelint/app.py
Labels: bug

#2668 Make SARIF output specification compliant
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_sarif.py
Labels: bug

#2680 Refactored some tests
  examples/playbooks/rule-fqcn-fail.yml
  examples/playbooks/rule-fqcn-pass.yml
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/testing/__init__.py
Labels: skip-changelog, bug

#2689 Print fatal matches first in GitHub Actions
  src/ansiblelint/app.py
Labels: bug

#2670 Updated repository urls
  .config/ansible-lint.spec
  .flake8
  .github/CONTRIBUTING.md
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .pre-commit-hooks.yaml
  README.md
  docs/README.md
  docs/configuring.md
  docs/installing.md
  examples/roles/template_lookup/tasks/main.yml
  pytest.ini
  setup.cfg
  src/ansiblelint/cli.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/utils.py
Labels: skip-changelog, bug

#2660 Disable cspell allowCompoundWords
  .config/dictionary.txt
  cspell.config.yaml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2695 Updated test dependencies
  requirements.txt
Labels: skip-changelog

#2698 Updated schemas
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: bug

#2701 Revert accidental change included in #2670
  setup.cfg
Labels: skip-changelog, bug

#2696 Fix WSL testing
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#2702 Update schemas and the refresh logic
  .pre-commit-config.yaml
  conftest.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/meta.json
  tox.ini
Labels: skip-changelog

#2694 Require ansible-compat>=2.2.5
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: bug

#2666 Docs: lint profiles
  docs/index.md
  docs/using-profiles.md
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/generate_docs.py
Labels: bug, documentation

#2685 Improve documentation on custom rules
  docs/custom-rules.md
Labels: bug

#2675 Docs: configuration content edits
  .ansible-lint
  docs/configuring.md
Labels: bug

#2704 Bump minimal requirements
  .github/workflows/tox.yml
  setup.cfg
Labels: bug

#2656 Refactor get_app
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
Labels: bug

#2708 Clarify progressive mode documentation
  .ansible-lint
  src/ansiblelint/cli.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: bug

#2682 Docs: usage content edits
  docs/usage.md
Labels: bug

#2707 Improve installation documentation
  docs/installing.md
Labels: bug

#2714 Avoid version checking when version info is absent
  src/ansiblelint/config.py
  src/ansiblelint/version.py
Labels: bug

#2706 Respect warn_list and skip_list
  .github/workflows/tox.yml
  examples/roles/invalid-name/tasks/main.yaml
  src/ansiblelint/app.py
  test/test_cli_role_paths.py
Labels: bug

#2712 Prevent installation on Windows
  setup.cfg
Labels: bug

#2716 Reduce test dependency on galaxy server
  examples/reqs_v1/requirements.yml
  examples/reqs_v2/requirements.yml
  requirements.yml
Labels: skip-changelog

#2718 Update url in docs
  src/ansiblelint/rules/fqcn.md
Labels: bug

#2721 Decouple profile listing from profile selecting on CLI
  .config/dictionary.txt
  docs/using-profiles.md
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
Labels: bug

#2720 Allow profile to be set in config file
  .ansible-lint
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/testing/__init__.py
Labels: bug

#2715 Update packit
  .config/dictionary.txt
  .packit.yaml
Labels: skip-changelog

#2722 Increse timeout for venv creation
  .github/workflows/tox.yml
Labels: skip-changelog

#2719 Fix only builtins fail test
  src/ansiblelint/rules/only_builtins.py
Labels: bug

#2723 Expand ~ in PATH and warn user
  src/ansiblelint/__main__.py
Labels: bug

#2724 Avoid Object of type PosixPath is not JSON serializable with jinja2
  .config/dictionary.txt
  examples/playbooks/rule-jinja-valid.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2734 Correct packaging metadata
  setup.cfg
Labels: bug

#2733 Fix deannotate function
  .github/workflows/tox.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: bug

#2732 Allow additional modules in only-builtins
  .ansible-lint
  examples/playbooks/.ansible-lint-only-builtins-allow
  examples/playbooks/rule-only-builtins.yml
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: bug

#2727 Treat ansible.legacy the same way ansible.builtin
  src/ansiblelint/rules/only_builtins.py
Labels: bug

#2739 Refactor only-builtins to have less code duplication
  src/ansiblelint/rules/only_builtins.py
Labels: bug

#2737 Avoid parallel run of schema refresh tests
  .github/workflows/tox.yml
  src/ansiblelint/schemas/main.py
  test/test_schemas.py
Labels: skip-changelog

#2742 Improve tox passenv
  .config/dictionary.txt
  tox.ini
Labels: skip-changelog

#2745 Improve RPM Packaging
  .config/ansible-lint.spec
  .packit.yaml
  setup.cfg
Labels: bug

#2752 Upgrade linters and fix reported issues
  .flake8
  .pre-commit-config.yaml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/schema.md
  src/ansiblelint/text.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#2754 GHA combine all tox jobs under a single build matrix
  .github/workflows/codeql.yml
  .github/workflows/tox.yml
  tools/test-setup.sh
  tox.ini
Labels: skip-changelog

#2746 Fix badge linking to rules
  README.md
Labels: bug

#2761 Restore offline mode functionality
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: bug
