Repository ansible/ansible-lint, pull requests merged in 2022-01, with the labels that each got.

#1797 Make code compatible with rich 11
  src/ansiblelint/generate_docs.py
Labels: bug

#1800 chore: fix linting issue caused by newer rich
  .pre-commit-config.yaml
  constraints.txt
  src/ansiblelint/generate_docs.py
Labels: skip-changelog

#1798 Bump test dependencies
  constraints.txt
Labels: skip-changelog

#1799 gha: disable fail fast for unittests
  .github/workflows/tox.yml
Labels: skip-changelog

#1786 Allow rpm --nodeps command-instead-of-module
  src/ansiblelint/rules/CommandsInsteadOfModulesRule.py
Labels: bug

#1802 Revert "Mark the `eco` job as allowed to fail"
  .github/workflows/tox.yml
Labels: skip-changelog

#1807 fix typo
  src/ansiblelint/runner.py
Labels: skip-changelog

#1806 MatchError's should include the filename
  src/ansiblelint/rules/BecomeUserWithoutBecomeRule.py
  src/ansiblelint/rules/MetaChangeFromDefaultRule.py
  src/ansiblelint/rules/MetaTagValidRule.py
  src/ansiblelint/rules/MetaVideoLinksRule.py
  src/ansiblelint/rules/NoFormattingInWhenRule.py
  src/ansiblelint/rules/NoSameOwnerRule.py
  src/ansiblelint/rules/RoleLoopVarPrefix.py
  src/ansiblelint/rules/VariableNamingRule.py
  src/ansiblelint/utils.py
Labels: enhancement

#1808 standardize skip_utils usage in rules/__init__.py
  src/ansiblelint/rules/__init__.py
Labels: skip-changelog

#1809 Recursively extract tasks from blocks
  src/ansiblelint/rules/CommandHasChangesCheckRule.py
  src/ansiblelint/utils.py
  test/TestSkipInsideYaml.py
  test/TestUtils.py
Labels: bug

#1810 Refactor coverage implementation
  .github/workflows/tox.yml
  codecov.yml
  constraints.txt
  pyproject.toml
  setup.cfg
  tox.ini
Labels: skip-changelog

#1813 Restore use of pytest-cov
  constraints.txt
  setup.cfg
  tox.ini
Labels: skip-changelog

#1819 Allow noqa to be used in more lintable kinds
  src/ansiblelint/skip_utils.py
  test/test_skiputils.py
Labels: bug

#1824 Add utils.nested_items_path and Deprecate utils.nested_items
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  src/ansiblelint/rules/ComparisonToLiteralBoolRule.py
  src/ansiblelint/rules/NoTabsRule.py
  src/ansiblelint/rules/VariableHasSpacesRule.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/TestUtils.py
  test/test_yaml_utils.py
Labels: enhancement, refactoring

#1823 Add utility function to initialize ansible Templar
  docs/conf.py
  src/ansiblelint/utils.py
Labels: skip-changelog, refactoring

#1827 Move ansiblelint.testing.RunFromText import into test code
  src/ansiblelint/rules/ComparisonToEmptyStringRule.py
  src/ansiblelint/rules/FQCNBuiltinsRule.py
  src/ansiblelint/rules/IgnoreErrorsRule.py
  src/ansiblelint/rules/MissingFilePermissionsRule.py
  src/ansiblelint/rules/NoLogPasswordsRule.py
Labels: bug

#1826 Extract list logic to reduce complexity of __main__.main()
  src/ansiblelint/__main__.py
Labels: skip-changelog, refactoring

#1834 Allow rules to request original raw task data
  examples/playbooks/ematcher-rule.yml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/__init__.py
  test/TestLintRule.py
  test/TestRulesCollection.py
  test/rules/RawTaskRule.py
  test/rules/__init__.py
Labels: enhancement
