Repository ansible/ansible-lint, pull requests merged in 2022-04, with the labels that each got.

#2059 Fix loading ansible-lint.yml in git projects
  src/ansiblelint/cli.py
Labels: bug

#2058 Propagate error message to user on systemexit
  src/ansiblelint/__main__.py
  src/ansiblelint/utils.py
Labels: bug

#2063 Apply var-spacing tests to vars files
  .github/workflows/tox.yml
  examples/playbooks/vars/var-spacing.yml
  src/ansiblelint/rules/var_spacing.py
  test/eco/debops.result
  test/eco/hardening.result
  test/eco/zuul-jobs.result
Labels: bug

#2080 chore: remove summary line from eco pipeline output
  test/eco/colsystem.result
  test/eco/debops.result
  test/eco/hardening.result
  test/eco/mysql.result
  test/eco/zuul-jobs.result
  test/test_eco.py
Labels: skip-changelog

#2060 Add only-builtins rule to check compatibility with core
  .github/workflows/tox.yml
  requirements.yml
  src/ansiblelint/rules/only_builtins.py
Labels: feature, new rule

#2083 chore: bump test dependencies
  docs/requirements.txt
  requirements.txt
Labels: skip-changelog

#2084 chore: consolidate docs requirements
  .pre-commit-config.yaml
  .readthedocs.yml
  docs/requirements.in
  docs/requirements.txt
  requirements.txt
  setup.cfg
  tox.ini
Labels: skip-changelog

#2086 Update package metadata for setuptools
  setup.cfg
Labels: bug

#2087 Update test and typing deps and remove special code paths for py < 3.8
  requirements.txt
  setup.cfg
  src/ansiblelint/constants.py
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_base.py
Labels: bug

#2088 Delete now superfluous filterwarnings
  pytest.ini
Labels: skip-changelog
