Repository ansible/ansible-lint, pull requests merged in 2022-10, with the labels that each got.

#2527 Add no-shorthand rule as experimental
  .github/workflows/tox.yml
  examples/playbooks/contains_secrets.transformed.yml
  examples/playbooks/contains_secrets.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/playbook-parent.yml
  examples/playbooks/rule-no-shorthand-fail.yml
  examples/playbooks/rule-no-shorthand-pass.yml
  examples/playbooks/test_skip_inside_yaml.yml
  examples/playbooks/unicode.transformed.yml
  examples/playbooks/unicode.yml
  examples/roles/test-role/tasks/main.yml
  examples/roles/test-role/tasks/world.yml
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/no_shorthand.md
  src/ansiblelint/rules/no_shorthand.py
  test/test_examples.py
  test/test_import_include_role.py
  test/test_rules_collection.py
  test/test_skip_import_playbook.py
  test/test_skip_inside_yaml.py
Labels: enhancement

#2529 Refactor parsing of ansible syntax check
  docs/conf.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/_internal/warning.md
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/syntax_check.py
  test/test_profiles.py
  test/test_rules_collection.py
  test/test_utils.py
Labels: bug

#2531 Avoid extra space when building task names
  src/ansiblelint/constants.py
  src/ansiblelint/utils.py
Labels: bug

#2533 Implement strict mode
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
Labels: bug

#2535 Switch to gh-action-pypi-publish@release/v1
  .github/workflows/release.yml
Labels: skip-changelog

#2540 Fix project directory detection with config inside .config
  .github/workflows/tox.yml
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: bug

#2541 no-shorthand: Avoid false positive with raw
  src/ansiblelint/_internal/warning.md
  src/ansiblelint/rules/no_shorthand.md
  src/ansiblelint/rules/no_shorthand.py
Labels: bug

#2542 no-shorthand: Avoid false positive with raw
  examples/playbooks/rule-no-shorthand-fail.yml
  examples/playbooks/rule-no-shorthand-pass.yml
  src/ansiblelint/rules/no_shorthand.md
  src/ansiblelint/rules/no_shorthand.py
Labels: bug

#2544 Allow fqcn with more than 2 dots
  src/ansiblelint/rules/fqcn.py
Labels: bug

#2546 Docs: Add MD for no-prompting rule
  src/ansiblelint/rules/no_prompting.md
Labels: bug

#2548 Rename no-shorthand to no-free-form
  examples/playbooks/rule-no-free-form-fail.yml
  examples/playbooks/rule-no-free-form-pass.yml
  examples/playbooks/test_skip_inside_yaml.yml
  examples/roles/test-role/tasks/world.yml
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/no_free_form.md
  src/ansiblelint/rules/no_free_form.py
  test/test_import_include_role.py
  test/test_skip_import_playbook.py
Labels: bug

#2551 Docs: Add MD for no-relative-paths rule
  src/ansiblelint/rules/no_relative_paths.md
  src/ansiblelint/rules/no_relative_paths.py
Labels: bug

#2556 Update ansible-navigator schema
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: skip-changelog

#2555 Docs: Add MD for only-builtins rule
  src/ansiblelint/rules/only_builtins.md
Labels: bug

#2553 Docs: no-relative-path rule doc edits
  src/ansiblelint/rules/no_relative_paths.md
Labels: skip-changelog

#2552 Docs: Add MD for no-same-owner rule
  src/ansiblelint/rules/no_same_owner.md
  src/ansiblelint/rules/no_same_owner.py
Labels: bug

#2562 Update schema
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: skip-changelog

#2560 Docs: Add MD for partial-become rule
  src/ansiblelint/rules/partial_become.md
Labels: bug

#2563 Update test dependencies
  .pre-commit-config.yaml
  requirements.txt
  tox.ini
Labels: skip-changelog

#2565 Avoid ansible@devel console noise
  src/ansiblelint/__main__.py
Labels: skip-changelog

#2564 Fixed regex for pipefail rule
  src/ansiblelint/rules/risky_shell_pipe.py
Labels: bug

#2566 Refactor the rendering of errors and warnings
  src/ansiblelint/color.py
  src/ansiblelint/errors.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/rules/yaml_rule.py
  test/test_cli_role_paths.py
  test/test_utils.py
Labels: bug

#2567 Changed success/failure message
  examples/playbooks/task-has-name-success.yml
  src/ansiblelint/app.py
  src/ansiblelint/rules/only_builtins.py
Labels: bug

#2574 Docs: Add MD for risky-octal rule
  src/ansiblelint/rules/risky_octal.md
Labels: bug

#2578 Include help url with JSON output format
  src/ansiblelint/formatters/__init__.py
Labels: bug

#2577 Docs: Add MD for risky shell pipe
  src/ansiblelint/rules/risky_shell_pipe.md
Labels: bug

#2580 Avoid warnings with empty role meta files
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_video_links.py
Labels: bug

#2583 Docs: Add MD for role name rule
  .config/dictionary.txt
  src/ansiblelint/rules/role_name.md
Labels: bug

#2585 Ensure all rich tags are closed
  src/ansiblelint/app.py
  src/ansiblelint/formatters/__init__.py
Labels: bug

#2586 Soften no-free-form occurences
  .config/dictionary.txt
  examples/playbooks/rule-no-free-form-pass.yml
  src/ansiblelint/rules/no_free_form.py
Labels: bug

#2587 Fix rules selection by profile
  src/ansiblelint/rules/__init__.py
  test/test_profiles.py
Labels: bug

#2588 Avoid jinja[invalid] with vars on task
  examples/playbooks/rule-jinja-valid.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#2589 Improve errors with invalid yaml files
  src/ansiblelint/utils.py
Labels: bug

#2595 Fix: typo for test severity valid.
  test/test_rule_properties.py
Labels: skip-changelog

#2591 Fix role-name correct code example
  src/ansiblelint/rules/role_name.md
Labels: bug

#2594 Docs: Add MD for var-naming
  src/ansiblelint/rules/var_naming.md
Labels: bug

#2596 Add win_command/win_shell to no-free-form modules
  src/ansiblelint/rules/no_free_form.py
Labels: bug

#2600 Fix config file outside project_dir bug
  src/ansiblelint/cli.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
Labels: bug

#2601 Fix strict mode
  .github/workflows/tox.yml
  examples/playbooks/strict-mode.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/rules/only_builtins.py
  test/test_strict.py
Labels: bug

#2603 Allow toggling strict in the config file
  .ansible-lint
  .github/workflows/tox.yml
  src/ansiblelint/cli.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/fixtures/strict.yml
  test/test_commandline_invocations_same_as_config.py
Labels: bug

#2604 Refactor fqcn to recommend use of canonical names
  examples/playbooks/test_skip_inside_yaml.yml
  examples/roles/role_for_no_same_owner/tasks/pass.yml
  src/ansiblelint/rules/fqcn.md
  src/ansiblelint/rules/fqcn.py
Labels: bug

#2617 Enable GHA caching for galaxy
  .github/workflows/tox.yml
Labels: skip-changelog

#2616 Fix merging of command line options with configuration
  src/ansiblelint/cli.py
  test/test_utils.py
Labels: bug

#2618 Update test dependencies
  requirements.txt
  setup.cfg
Labels: skip-changelog

#2619 Detect ScannerError while searching for skipped rules
  src/ansiblelint/skip_utils.py
Labels: bug

#2615 Add warning message about outdated linter version
  .config/dictionary.txt
  .pre-commit-config.yaml
  .pylintrc
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/config.py
  test/test_strict.py
Labels: bug

#2621 Save vscode configuration
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
Labels: skip-changelog

#2624 Prevent pip exception with version check
  src/ansiblelint/config.py
Labels: bug

#2610 Docs: wrap loop var tag
  src/ansiblelint/rules/loop_var_prefix.md
Labels: bug

#2625 Fix package name in pip upgrade instructions
  src/ansiblelint/config.py
Labels: bug

#2626 Add experimental rule for run_once
  .github/workflows/tox.yml
  examples/playbooks/run-once-fail.yml
  examples/playbooks/run-once-pass.yml
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/run_once.md
  src/ansiblelint/rules/run_once.py
  test/test_rules_collection.py
Labels: bug

#2630 Avoid upgrade recommendation for bleeding edge users
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
Labels: bug

#2635 Adapt tests for 2.15 change in behavior
  test/test_utils.py
Labels: skip-changelog

#2636 Refactor eco testing
  test/test_eco.py
Labels: skip-changelog

#2634 Do not emit fqcn[action-core] when ansible.legacy is used for builtin modules
  src/ansiblelint/rules/fqcn.py
Labels: bug

#2637 Avoid altering severity based on level on codeclimate output
  src/ansiblelint/formatters/__init__.py
Labels: bug

#2632 Test get_version_warning
  .github/workflows/tox.yml
  mypy.ini
  requirements.txt
  setup.cfg
  test/test_main.py
Labels: skip-changelog

#2532 role-name[path]: Now detects use of paths when including roles
  examples/roles/subfolder/other_role/tasks/main.yml
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/role_name.md
  src/ansiblelint/rules/role_name.py
Labels: bug

#2638 Fix progressive mode exit code
  src/ansiblelint/app.py
Labels: bug

#2641 Fix pip version check
  src/ansiblelint/config.py
Labels: bug

#2642 Delay app initialization
  src/ansiblelint/__main__.py
  test/test_examples.py
Labels: bug

#2643 Fix offline mode
  .pre-commit-config.yaml
  conftest.py
  requirements.txt
  setup.cfg
  src/ansiblelint/testing/__init__.py
  test/test_examples.py
Labels: bug
