Repository ansible/ansible-lint, pull requests merged in 2023-04, with the labels that each got.

#3236 Update navigator schema
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: bug

#3237 Document that no-changed-when also applies to handlers
  src/ansiblelint/rules/no_changed_when.md
Labels: bug

#3238 Update dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3243 Rename arg-spec schema file to clarify it applies to roles only
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.md
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/role-arg-spec.json
  test/test_file_utils.py
Labels: bug

#3244 Refactor tests for meta rule
  examples/roles/meta_categories_as_list/meta/main.yml
  examples/roles/meta_no_tags_galaxy_info/meta/main.yml
  examples/roles/meta_no_tags_valid/meta/main.yml
  examples/roles/meta_tags_no_list/meta/main.yml
  examples/roles/meta_tags_not_a_string/meta/main.yml
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#3252 Fix docs building
  .config/requirements-docs.txt
  .config/requirements.txt
  mkdocs.yml
Labels: skip-changelog

#3247 Updated 'kind' message if file kind is unknown
  src/ansiblelint/file_utils.py
Labels: bug

#3250 Ensure playbook path is absolute
  .config/requirements-test.txt
  .config/requirements.txt
  src/ansiblelint/rules/args.py
  src/ansiblelint/utils.py
Labels: bug

#3254 Refactored deprecated-local-action tests
  .github/workflows/tox.yml
  examples/playbooks/rule-deprecated-local-action-fail.yml
  src/ansiblelint/rules/deprecated_local_action.md
  src/ansiblelint/rules/deprecated_local_action.py
Labels: skip-changelog

#3249 Update dependencies
  .config/requirements.txt
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3256 Refactor tests
  .github/workflows/tox.yml
  examples/roles/fixture_1/tasks/main.yml
  test/test_skip_inside_yaml.py
Labels: skip-changelog

#3262 Ignore unknown sections under changes key on changelogs
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/changelog.json
  test/schemas/test/changelogs/maximal/changelog.yaml
Labels: bug

#3263 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
  test/schemas/src/schema.spec.ts
Labels: skip-changelog

#3265 Refactor literal-compare tests
  .github/workflows/tox.yml
  examples/playbooks/rule_literal_compare_fail.yml
  examples/playbooks/rule_literal_compare_pass.yml
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/schemas/__store__.json
  test/rules/test_literal_compare.py
Labels: skip-changelog

#3266 Refactor meta-incorrect tests
  .github/workflows/tox.yml
  examples/roles/meta_incorrect_fail/meta/main.yml
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_video_links.py
  test/rules/test_meta_change_from_default.py
Labels: skip-changelog

#3267 Remove meta-no-info rule due to being covered by schema[meta]
  .github/workflows/tox.yml
  docs/profiles.md
  docs/redirects.yml
  docs/rules/index.md
  docs/rules/meta-no-info.md
  examples/roles/meta_noqa/meta/main.yml
  mkdocs.yml
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/meta_no_info.md
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/rules/test_meta_no_info.py
  test/schemas/negative_test/.ansible-lint.md
  test/test_rules_collection.py
Labels: bug

#3268 name[casing]: Add transform to automatically fix this during --write
  .github/workflows/tox.yml
  examples/playbooks/name-case.transformed.yml
  examples/playbooks/name-case.yml
  src/ansiblelint/rules/name.py
  test/test_transformer.py
Labels: bug

#3269 Minor fixes for no-handler rule
  .github/workflows/tox.yml
  examples/playbooks/no_handler_fail.yml
  examples/playbooks/no_handler_pass.yml
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/schemas/__store__.json
  test/rules/test_use_handler_rather_than_when_changed.py
Labels: bug

#3270 Refactor no-relative-paths tests
  examples/playbooks/no_relative_paths_fail.yml
  examples/playbooks/no_relative_paths_pass.yml
  examples/roles/fixture_1/tasks/main.yml
  src/ansiblelint/rules/no_relative_paths.py
  test/rules/test_no_relative_paths.py
Labels: bug

#3271 Refactor tests
  examples/yamllint/line-length.yml
  src/ansiblelint/rules/yaml_rule.py
  test/rules/test_line_too_long.py
Labels: bug

#3272 Ensure that syntax-check also runs on roles
  .config/requirements-test.txt
  .config/requirements.txt
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
Labels: skip-changelog, bug

#3276 Enable ruff linter
  .pre-commit-config.yaml
  .vscode/extensions.json
  pyproject.toml
  src/ansiblelint/__init__.py
  src/ansiblelint/app.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
  test/conftest.py
  test/test_transform_mixin.py
Labels: bug

#3278 Enable and fix PT checks on ruff
  .flake8
  pyproject.toml
  src/ansiblelint/testing/fixtures.py
Labels: bug

#3280 Use temporary playbooks to check role syntax
  .config/dictionary.txt
  .gitignore
  src/ansiblelint/rules/syntax_check.py
Labels: bug

#3274 Update schema to add some of the missing rules
  src/ansiblelint/schemas/ansible-lint-config.json
  test/schemas/negative_test/.ansible-lint.md
Labels: bug

#3289 Fix Schema validation for variables in tasks/vars directory
  .github/workflows/tox.yml
  examples/playbooks/tasks/vars/bug-3289.yml
  src/ansiblelint/config.py
  test/test_file_utils.py
Labels: bug

#3288 Send GHA annotations to stderr
  src/ansiblelint/app.py
  test/test_cli_role_paths.py
Labels: bug

#3292 Remove flake8 and pyupgrade
  .config/requirements-test.txt
  .config/requirements.txt
  .flake8
  .pre-commit-config.yaml
  conftest.py
  docs/contributing.md
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/schemas/__main__.py
  test/schemas/src/rebuild.py
  test/schemas/test/molecule/cluster/molecule.yml
  test/schemas/test/molecule/default/molecule.yml
  test/schemas/test/molecule/vagrant/molecule.yml
Labels: bug

#3295 Refactor project root directory detection code
  .config/dictionary.txt
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: bug

#3296 Update dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
Labels: skip-changelog

#3298 Workaround for coverage bug
  tox.ini
Labels: skip-changelog

#3297 Change logging to use rich output
  src/ansiblelint/__main__.py
  test/test_file_utils.py
Labels: bug

#3299 Ensure profile rules do not have experimental or opt-in tag
  .github/workflows/tox.yml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/sanity.py
  test/test_config.py
Labels: bug

#3302 Ensure non zero exit code when no files are linted
  .github/workflows/tox.yml
  src/ansiblelint/app.py
  src/ansiblelint/constants.py
  test/test_app.py
  tools/test-hook.sh
  tox.ini
Labels: bug

#3303 Require at least one known subfolder for roles
  .config/dictionary.txt
  src/ansiblelint/file_utils.py
  src/ansiblelint/utils.py
  test/fixtures/verbosity-tests/tasks/main.yml
  test/test_runner.py
  test/test_verbosity.py
Labels: enhancement

#3305 Avoid running args rule if we encounter a windows module
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
  tools/install-reqs.sh
Labels: bug

#3306 Improve tests related to vault processing
  .github/workflows/tox.yml
  examples/playbooks/vars/vault_full.yml
  examples/playbooks/vars/vault_partial.yml
  src/ansiblelint/rules/schema.py
  test/test_examples.py
Labels: bug

#3312 Fix config path detection logic
  examples/roles/test-role/molecule/default/include-import-role.yml
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  test/test_cli_role_paths.py
  test/test_file_utils.py
Labels: bug

#3313 Document how to avoid vault related errors
  docs/usage.md
Labels: bug, enhancement

#3314 Improve description of task names
  src/ansiblelint/utils.py
Labels: bug

#3315 Ensure that JSON output does not contain newlines
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
Labels: bug

#3316 Add ability to auto-fix fcqn rule violations
  .config/dictionary.txt
  .github/workflows/tox.yml
  examples/playbooks/fqcn.transformed.yml
  examples/playbooks/fqcn.yml
  src/ansiblelint/rules/fqcn.py
  test/test_transformer.py
  tools/install-reqs.sh
Labels: enhancement

#3317 Solve some ruff violations
  pyproject.toml
  src/ansiblelint/yaml_utils.py
  test/test_profiles.py
  test/test_rules_collection.py
  test/test_with_skip_tagid.py
Labels: skip-changelog

#3323 Avoid using obsolete rule names
  examples/playbooks/noqa-nested.yml
  examples/playbooks/playbook-imported.yml
  examples/playbooks/tasks/directory with spaces/main.yml
  examples/roles/role_with_task_inclusions/tasks/imported_tasks.yml
  examples/roles/role_with_task_inclusions/tasks/included_tasks.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/name.py
Labels: skip-changelog

#3326 Enforce use of lineno variable name inside the library
  pyproject.toml
  src/ansiblelint/errors.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/runner.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_examples.py
  test/test_formatter.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_rules_collection.py
  test/test_yaml_utils.py
Labels: enhancement

#3327 Remove useless . from additional_dependencies in pre-commit hook
  .pre-commit-hooks.yaml
Labels: bug

#3329 Remove exclude of .github from ansible-lint
  .ansible-lint
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/redirects.yml
  .github/workflows/release.yml
Labels: skip-changelog

#3330 Update deps
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3337 Allow running test under unsupported architectures
  conftest.py
Labels: skip-changelog

#3340 Improve code formatting on save with vscode
  .vscode/settings.json
  pyproject.toml
Labels: skip-changelog

#3342 Remove `ISC` from ruff ignores
  pyproject.toml
  src/ansiblelint/cli.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  test/rules/fixtures/ematcher.py
  test/rules/fixtures/unset_variable_matcher.py
  test/test_main.py
Labels: bug

#3332 Remove `G` from ruff ignores
  pyproject.toml
  src/ansiblelint/logger.py
  src/ansiblelint/skip_utils.py
Labels: bug

#3346 Remove `RUF` from ruff ignores
  pyproject.toml
  src/ansiblelint/_mockings.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_cli.py
Labels: bug

#3348 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3353 Add Fedora 38 to meta.json schema file
  src/ansiblelint/schemas/meta.json
Labels: bug

#3355 Mock jinja filters to prevent templating errors
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
Labels: bug

#3356 Remove `EM` from ruff ignores
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#3350 Remove progressive mode
  .ansible-lint
  .github/workflows/tox.yml
  .gitignore
  docs/usage.md
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_progressive.py
  tox.ini
Labels: enhancement

#3345 Make MatchError a dataclass
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_formatter.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_matcherrror.py
Labels: bug

#3363 ruff: fix S rule
  conftest.py
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#3358 Find "changed" not only in first "when" condition
  examples/playbooks/no_handler_fail.yml
  src/ansiblelint/rules/no_handler.py
Labels: bug

#3364 ruff: Address T and RET
  conftest.py
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/__store__.json
  test/schemas/src/rebuild.py
Labels: bug

#3362 Add initial handling of submodules to contribution docs
  docs/contributing.md
Labels: bug, documentation

#3366 ruff: Address INP and PLW
  pyproject.toml
  src/ansiblelint/color.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/testing/fixtures.py
  test/test_strict.py
Labels: bug

#3368 ruff: Address BLE
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/config.py
  src/ansiblelint/utils.py
  src/ansiblelint/version.py
Labels: bug

#3367 ruff: Address EXE
  pyproject.toml
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/modules/test_module_2.py
  test/local-content/test-roles-failed-complete/roles/role1/library/test_module_1_failed_complete.py
  test/local-content/test-roles-failed-complete/roles/role3/library/test_module_3_failed_complete.py
  test/local-content/test-roles-failed/roles/role1/library/test_module_1_failed.py
  test/local-content/test-roles-failed/roles/role3/library/test_module_3_failed.py
  test/local-content/test-roles-success/roles/role1/library/test_module_1_success.py
  test/local-content/test-roles-success/roles/role3/library/test_module_3_success.py
Labels: bug

#3375 Use native Path class
  src/ansiblelint/file_utils.py
Labels: skip-changelog

#3373 ruff: Address `SIM`
  pyproject.toml
  src/ansiblelint/_mockings.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_same_owner.py
  test/schemas/src/rebuild.py
Labels: bug

#3372 ruff: Address SLF
  pyproject.toml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_formatter_base.py
Labels: bug

#3376 ruff: Address ARG001
  pyproject.toml
  src/ansiblelint/color.py
  src/ansiblelint/utils.py
  test/test_file_utils.py
  test/test_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#3377 ruff: Address B
  conftest.py
  pyproject.toml
  src/ansiblelint/_vendor/__init__.py
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_cli.py
  test/test_transformer.py
Labels: bug

#3380 ruff: Address PGH
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/color.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/utils.py
  src/ansiblelint/version.py
  test/test_file_utils.py
  test/test_formatter.py
  test/test_formatter_base.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_matcherrror.py
  test/test_utils.py
Labels: bug

#3381 ruff: Address `D`
  pyproject.toml
  src/ansiblelint/_vendor/__init__.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_transformer.py
Labels: skip-changelog

#3383 Make cwd use pathlib
  conftest.py
  src/ansiblelint/__main__.py
  src/ansiblelint/file_utils.py
  test/conftest.py
  test/test_file_utils.py
Labels: bug
