Repository ansible/ansible-lint, pull requests merged in 2023-05, with the labels that each got.

#3387 Remove resolvelib from requirements lock
  .config/dictionary.txt
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: bug

#3388 Fix changelog schema for connection plugins
  src/ansiblelint/schemas/changelog.json
Labels: bug

#3394 Correct docs on navigator schema location
  src/ansiblelint/rules/schema.md
Labels: bug

#3392 Avoid dropping comments on YAML transformation
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  examples/playbooks/vars/strings.transformed.yml
  examples/playbooks/vars/strings.yml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  tox.ini
Labels: skip-changelog, bug

#3390 More pathlib adoption
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_mockings.py
  src/ansiblelint/_vendor/__init__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/yaml_utils.py
  test/schemas/src/rebuild.py
  test/test_app.py
  test/test_cli.py
  test/test_cli_role_paths.py
  test/test_eco.py
  test/test_file_utils.py
  test/test_formatter_sarif.py
  test/test_list_rules.py
  test/test_loaders.py
  test/test_main.py
  test/test_rules_collection.py
  test/test_runner.py
  test/test_schemas.py
  test/test_transformer.py
  test/test_verbosity.py
Labels: bug

#3396 More pathlib conversion
  pyproject.toml
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/testing/fixtures.py
  test/rules/test_deprecated_module.py
  test/test_utils.py
Labels: skip-changelog

#3397 More pathlib conversion
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/utils.py
  test/test_main.py
  test/test_utils.py
Labels: skip-changelog

#3389 ruff: Address FBT002
  pyproject.toml
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#3399 Avoid exception when trying to load invalid text files
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/broken/encoding.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  test/test_load_failure.py
Labels: bug

#3400 Refactor eco testing
  .github/workflows/tox.yml
  pyproject.toml
  src/ansiblelint/app.py
  test/test_eco.py
  tools/test-eco.sh
  tox.ini
Labels: skip-changelog

#3401 Fix exclude patterns logic
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/utils.py
  test/test_cli.py
  test/test_runner.py
  test/test_utils.py
Labels: skip-changelog, bug

#3406 Require ruamel.yaml>=0.17.24
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  examples/playbooks/vars/strings.transformed.yml
Labels: bug

#3403 Change matchtask to receive a Task instance
  docs/custom-rules.md
  examples/rules/task_has_tag.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/latest.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/rules/fixtures/raw_task.py
  tox.ini
Labels: bug

#3402 Fix missing required arguments issue from args rule
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
Labels: bug

#3410 Update dependencies
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3324 Capture python warnings and report some of them as matches
  .github/workflows/tox.yml
  examples/playbooks/capture-warning.yml
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  test/test_skiputils.py
Labels: bug, enhancement

#3405 Add Amazon Linux 2023 as a supported platform
  src/ansiblelint/schemas/meta.json
Labels: bug

#3413 Find and lint imported playbooks
  .github/workflows/tox.yml
  examples/site.yml
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: bug

#3414 Make task_in_list receive a lintable
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/utils.py
  test/test_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#3423 Fix exception when using reformatting on scalars
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/playbooks/vars/empty.transformed.yml
  examples/playbooks/vars/empty.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/transformer.py
  src/ansiblelint/yaml_utils.py
  test/test_transformer.py
Labels: bug

#3422 Upgrade var-naming rule to include role name prefix
  .github/workflows/tox.yml
  examples/playbooks/rule-var-naming-fail.yml
  examples/playbooks/vars/rule_var_naming_fail.yml
  examples/roles/var_naming_pattern/tasks/main.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3429 Fail-fast before running tests if repository was not fully cloned
  tox.ini
Labels: skip-changelog

#3432 Suggest correct alternative for `with_filetree`
  src/ansiblelint/rules/schema.py
Labels: bug

#3433 Relax ruamel-yaml requirements
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
Labels: bug

#3449 Update lock file to use ansible-core 2.15.0
  .config/requirements-lock.txt
  .config/requirements.txt
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: bug

#3455 Adding 2.16 to the list of allowed ansible-core versions in meta-runtime rule
  src/ansiblelint/rules/meta_runtime.md
  src/ansiblelint/rules/meta_runtime.py
Labels: enhancement

#3431 Ensure that we also lint files from git submodules
  .pre-commit-config.yaml
  src/ansiblelint/file_utils.py
  src/ansiblelint/schemas/__store__.json
  test/test_main.py
  test/test_mockings.py
  test/test_utils.py
Labels: bug

#3460 var-naming now prevents use of Ansible reserved names
  examples/playbooks/vars/rule_var_naming_fail.yml
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/runner.py
Labels: bug

#3458 Fix for var-naming rule to not break on include_tasks and vars
  .github/workflows/tox.yml
  examples/playbooks/tasks/included-task-with-vars.yml
  examples/roles/var_naming_pattern/tasks/include_task_with_vars.yml
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#3463 Add Oracle Enterprise Linux 7.*
  src/ansiblelint/schemas/meta.json
Labels: bug

#3462 Enable var-name rule to detect read-only variables
  examples/playbooks/vars/rule_var_naming_fail.yml
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3464 Allow rules to expose all tags they can produce
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/latest.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#3467 Ensure we return error if argument gives are not present
  .github/workflows/tox.yml
  src/ansiblelint/_internal/load-failure.md
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/ansible-lint-config.json
  test/schemas/negative_test/.ansible-lint.md
  test/test_runner.py
Labels: bug

#3468 Do not ever exclude files given as arguments
  .github/workflows/tox.yml
  examples/playbooks/deep/empty.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
  test/test_runner.py
Labels: bug

#3470 Update test dependencies
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/rules/fqcn.py
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: bug

#3473 Check for included role prefix instead of current one
  examples/roles/var_naming_pattern/tasks/include_task_with_vars.yml
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3476 Add Github Marketplace Action
  README.md
  action.yml
  docs/installing.md
  src/ansiblelint/schemas/__store__.json
Labels: bug

#3480 Add support for ansible-builder v3 schema
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/execution-environment.json
  test/schemas/test/execution-environment-v3.yml
Labels: bug

#3486 Also run action tagger on release
  .github/workflows/release.yml
Labels: skip-changelog

#3484 Add missing become_method plugins to the schema
  .config/dictionary.txt
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/negative_test/playbooks/tasks/become_method_invalid.yml
  test/schemas/negative_test/playbooks/tasks/become_method_invalid.yml.md
  test/schemas/negative_test/playbooks/tasks/become_method_untemplated.yml
  test/schemas/negative_test/playbooks/tasks/become_method_untemplated.yml.md
Labels: bug

#3495 Update ruff
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#3496 Update formatter to avoid reporting paths with ..
  src/ansiblelint/formatters/__init__.py
Labels: bug

#3494 Hide pip error if not present
  src/ansiblelint/config.py
Labels: bug

#3497 Update dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3500 Fix role_name_ prefix include_role var name error
  .github/workflows/tox.yml
  examples/test_collection/README.md
  examples/test_collection/galaxy.yml
  examples/test_collection/roles/my_role/tasks/main.yml
  examples/test_collection/roles/my_role2/tasks/main.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3506 Use latest ruamel-yaml for testing
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
Labels: skip-changelog, bug

#3504 Relax McCabe complexity configuration
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_mockings.py
  src/ansiblelint/app.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#3502 fqcn[deep]: detect deep plugins
  .github/workflows/tox.yml
  examples/collection/plugins/modules/alpha.py
  examples/collection/plugins/modules/deep/beta.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/fqcn.md
  src/ansiblelint/rules/fqcn.py
Labels: enhancement

#3499 Check validity of 'become_method' values from code
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/playbooks/rule-schema-become-method-fail.yml
  examples/playbooks/rule-schema-become-method-pass.yml
  src/ansiblelint/rules/schema.py
Labels: bug

#3507 Reimplement file exclusion logic
  .config/dictionary.txt
  .config/requirements.in
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
  test/test_runner.py
  test/test_utils.py
Labels: bug

#3511 Fix tag workflow on release
  .github/workflows/release.yml
Labels: skip-changelog

#3512 Trick action to avoid failing without requirements.txt files
  action.yml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
Labels: skip-changelog

#3514 Update dependencies
  .config/requirements-docs.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog, bug, security

#3517 Avoid dependency error from rich
  .config/requirements-lock.txt
  .config/requirements.txt
Labels: bug
