Repository ansible/ansible-lint, pull requests merged in 2023-06, with the labels that each got.

#3525 Avoid using get_app() from inside the rule
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/schema.py
Labels: bug

#3526 Ensure that rules collections use Runtime in offline mode
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/rules/__init__.py
Labels: bug

#3528 Temporary disable rpm building on pull-requests
  .packit.yaml
Labels: skip-changelog

#3529 Avoid failing test on SyntaxWarning
  test/test_profiles.py
Labels: skip-changelog

#3527 Handling of exclude paths with trailing slashs
  .config/requirements.in
  .github/workflows/tox.yml
  src/ansiblelint/file_utils.py
  test/test_utils.py
Labels: bug

#3538 exclude .github directory
  src/ansiblelint/cli.py
Labels: bug

#3536 Fix action name
  README.md
Labels: bug

#3548 Rename marketplace action
  action.yml
Labels: bug

#3546 Make refresh_schemas handle firewalls that cut the file transfer midway
  src/ansiblelint/schemas/__main__.py
Labels: bug

#3550 Avoid false positive with var-naming[no-role-prefix]
  examples/test_collection/roles/my_role/tasks/main.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3547 Revert "exclude .github directory"
  src/ansiblelint/cli.py
Labels: skip-changelog

#3549 Update dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/utils.py
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3551 Avoid adding pip related messages if installation method is different
  src/ansiblelint/config.py
Labels: bug

#3545 Make profile information on summary line more clear
  src/ansiblelint/app.py
Labels: bug

#3552 Fix exclude logic bug that can cause cause partial linting
  src/ansiblelint/runner.py
Labels: bug

#3556 Change RuleCollection to use offline mode if options are not given
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/__init__.py
Labels: skip-changelog

#3557 Install dependencies only once when using xdist
  .config/dictionary.txt
  conftest.py
Labels: skip-changelog

#3563 Avoid app reinitialization during syntax-check
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#3554 Preload test dependencies
  .github/workflows/tox.yml
  requirements.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/testing/fixtures.py
  test/test_profiles.py
  tools/install-reqs.sh
Labels: skip-changelog

#3568 Refactored syntax-checking
  examples/playbooks/extra_vars.yml
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  test/rules/test_syntax_check.py
Labels: bug

#3580 Avoid testing errors with outdated setuptools
  pyproject.toml
  tox.ini
Labels: skip-changelog

#3577 Make mocking use options
  src/ansiblelint/__main__.py
  src/ansiblelint/_mockings.py
  src/ansiblelint/app.py
  test/test_mockings.py
Labels: skip-changelog

#3581 Avoid running test setup for help commands
  conftest.py
  src/ansiblelint/testing/fixtures.py
Labels: skip-changelog

#3582 Avoid concurrency issues installing dependencies in parallel
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/test_examples.py
Labels: skip-changelog

#3586 Add NetBSD as a recognized platform
  src/ansiblelint/schemas/meta.json
Labels: bug

#3587 Fixed error when sarif file option is provided
  .github/workflows/tox.yml
  src/ansiblelint/app.py
  test/test_formatter_sarif.py
Labels: bug

#3585 Address parallel install errors with ansible-galaxy on GHA
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
  tox.ini
Labels: skip-changelog

#3588 Address ruff `PTH107`
  test/test_formatter_sarif.py
Labels: skip-changelog

#3575 Update deps
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3576 Add action and args properties to task class
  examples/playbooks/rule-args-module-fail.yml
  examples/playbooks/rule-risky-file-permissions-fail.yml
  examples/playbooks/rule-risky-file-permissions-pass.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/utils.py
Labels: bug

#3589 Update test deps
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/skip_utils.py
Labels: skip-changelog

#3572 Adopt standalone utils functions into Runner
  .pre-commit-config.yaml
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: skip-changelog

#3513 Allow use as a reusable github action
  .github/workflows/tox.yml
  action.yml
Labels: skip-changelog, bug

#3590 chore/release
  action.yml
Labels: skip-changelog

#3592 Fix installation of dependencies when run as an action
  action.yml
Labels: skip-changelog

#3593 Correct action example in readme
  README.md
Labels: skip-changelog

#3156 Add rule to check the number of tasks
  .github/workflows/tox.yml
  docs/rules/complexity.md
  docs/rules/index.md
  examples/playbooks/rule-complexity-fail.yml
  examples/playbooks/rule-complexity-pass.yml
  mkdocs.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/complexity.md
  src/ansiblelint/rules/complexity.py
  test/test_rules_collection.py
  test/test_runner.py
  test/test_transformer.py
Labels: enhancement

#3597 Update dependencies and ruff fixes
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
  src/ansiblelint/yaml_utils.py
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog
