Repository ansible/ansible-lint, pull requests merged in 2023-01, with the labels that each got.

#2856 Avoid checking var-names on non ansible files
  .config/dictionary.txt
  .github/workflows/tox.yml
  examples/Taskfile.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#2858 Disable version check when running as a pre-commit hook
  src/ansiblelint/app.py
Labels: bug

#2860 Make git a runtime dependency
  .config/ansible-lint.spec
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  test/test_main.py
Labels: bug

#2854 Remove binary files from lock extra
  .config/dictionary.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#2865 Docs: issue #2864 update urls
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/no_handler.md
  src/ansiblelint/rules/no_handler.py
Labels: bug

#2873 schema: detect invalid space in meta runtime
  examples/playbooks/collections/requirements.yml
  src/ansiblelint/schemas/meta-runtime.json
  test/schemas/negative_test/meta/runtime.yml
  test/schemas/negative_test/meta/runtime.yml.md
Labels: bug

#2877 Update etags
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#2832 Add no-changelog check to galaxy rule
  .github/workflows/tox.yml
  examples/collection/CHANGELOG.rst
  examples/meta/changelogs/changelog.yaml
  examples/no_changelog/galaxy.yml
  src/ansiblelint/rules/galaxy.md
  src/ansiblelint/rules/galaxy.py
Labels: enhancement

#2886 Remove lock special extra from pip-compile
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#2887 Improve test collection downloading
  tools/install-reqs.sh
Labels: skip-changelog

#2895 Fix infinite hang on schema refresh by adding timeout parameter
  .github/workflows/tox.yml
  src/ansiblelint/schemas/main.py
  test/test_schemas.py
Labels: bug

#2896 Clarify effects of --offline flag
  .ansible-lint
  src/ansiblelint/cli.py
Labels: bug

#2890 Avoid dubious ownership errors with newer versions of git
  src/ansiblelint/__main__.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  test/test_progressive.py
  test/test_utils.py
Labels: bug

#2897 Fix 'location' attribute for CodeclimateJSONFormatter
  .github/workflows/tox.yml
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_json.py
Labels: bug

#2898 Upgraded linters
  .pre-commit-config.yaml
  plugins/modules/fake_module.py
  src/ansiblelint/utils.py
  test/test_ansiblelintrule.py
  test/test_matcherrror.py
  test/test_skiputils.py
  test/test_utils.py
Labels: skip-changelog

#2899 Update test dependencies
  .config/requirements.txt
Labels: skip-changelog

#2903 Pass ssh agent during testing
  tox.ini
Labels: skip-changelog

#2900 Improve coverage
  .github/workflows/tox.yml
  .vscode/extensions.json
  conftest.py
  examples/playbooks/play-without-extension
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/color.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/version.py
  tox.ini
Labels: skip-changelog

#2905 Remove opt-in and experimental tags from galaxy rule
  src/ansiblelint/rules/galaxy.py
Labels: enhancement

#2906 Remove opt-in and experimental tags from metadata rule
  src/ansiblelint/rules/meta_unsupported_ansible.py
Labels: enhancement

#2901 Fix typo in installing.md
  docs/installing.md
Labels: bug

#2902 Added tests for text.py
  .github/workflows/tox.yml
  test/test_text.py
Labels: enhancement, test

#2911 Configure vscode to reformat on save
  .vscode/settings.json
Labels: skip-changelog

#2910 Fix galaxy[no-changelog] testing
  examples/no_changelog/galaxy.yml
  src/ansiblelint/rules/galaxy.py
Labels: skip-changelog

#2913 Fix print leak with meta-unsupported-ansible
  .pre-commit-config.yaml
  docs/conf.py
  src/ansiblelint/__main__.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/meta_unsupported_ansible.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/main.py
  test/fixtures/test_regenerate_formatting_fixtures.py
  test/schemas/src/rebuild.py
  test/test_list_rules.py
Labels: bug

#2914 Fix github archives metadata
  .git_archival.txt
Labels: bug

#2919 Change treatment of files that fail to load structured data
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
Labels: bug

#2912 Determine if passed arguments are playbooks or not
  .config/dictionary.txt
  .github/workflows/tox.yml
  examples/.config/molecule/config.yml
  examples/other/guess-1.yml
  examples/playbooks/rulebook.yml
  examples/roles/foo.yml
  examples/rulebooks/rulebook.yml
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/schemas/main.py
  src/ansiblelint/utils.py
  test/local-content/test-collection.yml
  test/schemas/test/molecule/cluster/base.yml
  test/schemas/test/molecule/cluster/converge.yml
  test/schemas/test/molecule/cluster/foobar.yml
  test/test_file_utils.py
  test/test_formatter.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_matcherrror.py
  test/test_yaml_utils.py
Labels: enhancement

#2920 Fix spacing in option help strings
  src/ansiblelint/cli.py
Labels: bug

#2918 Improve installation and support instructions
  docs/installing.md
Labels: skip-changelog

#2825 Extend fqcn rule to complain on `collections` keyword
  examples/playbooks/rule-fqcn-fail.yml
  src/ansiblelint/rules/fqcn.md
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/schemas/__store__.json
Labels: feature

#2925 Allow warnings to be skipped
  .github/workflows/tox.yml
  src/ansiblelint/__main__.py
  test/test_with_skip_tagid.py
Labels: bug

#2929 Ignore args rule finding if value for choice has jinja template
  examples/playbooks/rule-args-module-fail-1.yml
  examples/playbooks/rule-args-module-pass-1.yml
  src/ansiblelint/rules/args.py
Labels: bug

#2933 Improving test coverage
  .github/workflows/tox.yml
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
Labels: skip-changelog, enhancement, test

#2928 Fixing OpenWrt name; Adding OpenWrt 22.03
  src/ansiblelint/schemas/meta.json
Labels: bug

#2939 Update schema cache
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#2938 Remove rich markdown header override
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/color.py
Labels: skip-changelog, bug

#2954 Fix typo in doc site name
  mkdocs.yml
Labels: bug

#2952 Correct run-once rule identifier and related examples
  examples/playbooks/run-once-fail.yml
  src/ansiblelint/rules/run_once.md
  src/ansiblelint/rules/run_once.py
Labels: bug

#2948 Remove zuul-jobs and tripleo-ansible from eco pipelines
  test/test_eco.py
Labels: skip-changelog

#2956 Rename warning[raw-non-string] to no-free-form[raw-non-string]
  src/ansiblelint/rules/no_free_form.md
  src/ansiblelint/rules/no_free_form.py
Labels: bug

#2957 Update deps
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#2958 Enable devel testing
  .github/workflows/tox.yml
Labels: skip-changelog
