Repository ansible/ansible-lint, pull requests merged in 2023-03, with the labels that each got.

#3097 Fix for skipped rules key in yaml rule
  .github/workflows/tox.yml
  examples/yamllint/skipped-rule.yml
  src/ansiblelint/rules/yaml_rule.py
Labels: bug

#3104 Update test deps
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3064 Make git errors fatal when strict mode is active
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/logger.py
Labels: skip-changelog

#3109 Added support for raw booleans when using complex_conditional
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/negative_test/playbooks/when.yml
  test/schemas/negative_test/playbooks/when.yml.md
  test/schemas/test/playbooks/when.yml
Labels: bug

#3112 Suppress deprecation warning caused by ruamel.yaml with newer setuptools
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#3111 Ensure SPDX license list is in sync
  .config/requirements-test.txt
  .config/requirements.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/galaxy.json
  test/schemas/data/licenses.json
  test/test_schemas.py
Labels: bug

#3115 Added coverage for missing line
  .github/workflows/tox.yml
  src/ansiblelint/rules/name.py
Labels: skip-changelog, test

#3116 Removed unused code
  src/ansiblelint/rules/var_naming.py
Labels: bug, test

#3117 Allow schema refresh to run without installing app
  .pre-commit-config.yaml
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__init__.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/main.py
Labels: bug

#3103 Add rulebook schema
  .config/dictionary.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/changelogs/changelog.yaml
  examples/rulebooks/rulebook-fail.yml
  examples/rulebooks/rulebook-pass.yml
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
  test/schemas/src/schema.spec.ts
  test/test_file_utils.py
  test/test_schemas.py
Labels: bug

#3120 Correct logic for upgrading dependencies
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#3119 Remove duplicate deprecated-command-syntax rule
  .config/dictionary.txt
  .github/workflows/tox.yml
  docs/profiles.md
  docs/redirects.yml
  docs/rules/deprecated-command-syntax.md
  docs/rules/index.md
  docs/usage.md
  examples/playbooks/rule-deprecated-command-syntax.yml
  examples/playbooks/skiptasks.yml
  examples/playbooks/test_skip_inside_yaml.yml
  mkdocs.yml
  src/ansiblelint/constants.py
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/deprecated_command_syntax.md
  src/ansiblelint/rules/deprecated_command_syntax.py
  src/ansiblelint/rules/no_free_form.md
  src/ansiblelint/schemas/ansible-lint-config.json
  test/schemas/negative_test/.ansible-lint.md
  test/test_rules_collection.py
  test/test_skip_inside_yaml.py
Labels: bug

#3113 Generalize args rule exception handling
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
  test/test_skip_inside_yaml.py
Labels: bug

#3118 Adding 2.9 ignore allow-list for sanity rule
  .pre-commit-config.yaml
  examples/sanity_ignores/tests/sanity/ignore-2.13.txt
  examples/sanity_ignores/tests/sanity/ignore-2.14.txt
  examples/sanity_ignores/tests/sanity/ignore-2.9.txt
  src/ansiblelint/rules/sanity.md
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#3122 Run homebrew in separated pipeline
  .github/workflows/release.yml
Labels: skip-changelog

#3123 Refactor command-instead-of-module fixtures in standalone examples
  .github/workflows/tox.yml
  examples/playbooks/rule-command-instead-of-module-fail.yml
  examples/playbooks/rule-command-instead-of-module-pass.yml
  src/ansiblelint/rules/command_instead_of_module.py
Labels: skip-changelog

#3125 Refactor processing of module args
  docs/custom-rules.md
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: skip-changelog

#3127 Avoid undefined errors from jinja rule
  examples/playbooks/rule-jinja-fail.yml
  examples/playbooks/rule-jinja-pass.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3126 Improve testing of args rule
  examples/playbooks/rule-args-module-pass.yml
  tools/install-reqs.sh
Labels: skip-changelog

#3129 Remove deprecated nested_items
  .github/workflows/tox.yml
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#3132 Avoid skipping an args rule test
  src/ansiblelint/rules/args.py
Labels: skip-changelog

#3131 Ensure ignored matches are reports as minor in codeclimate output
  src/ansiblelint/errors.py
  test/test_formatter_json.py
Labels: bug

#3137 Update schema '$id'
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/arg_specs.json
  src/ansiblelint/schemas/changelog.json
  src/ansiblelint/schemas/execution-environment.json
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/inventory.json
  src/ansiblelint/schemas/meta-runtime.json
  src/ansiblelint/schemas/molecule.json
  src/ansiblelint/schemas/requirements.json
  src/ansiblelint/schemas/rulebook.json
  src/ansiblelint/schemas/vars.json
Labels: bug

#3141 Bump test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog, bug

#3142 Documentation maintenance
  docs/google04e29a42ae6e6cbc.html
  docs/redirects.yml
  mkdocs.yml
Labels: skip-changelog

#3144 Document skip_ansible_lint does not work with yamllint rule
  .github/workflows/tox.yml
  examples/playbooks/rule-yaml-fail.yml
  examples/playbooks/rule-yaml-pass.yml
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/rules/yaml_rule.py
Labels: bug

#3146 Change schema $id to be a valid URL
  .pre-commit-config.yaml
  src/ansiblelint/schemas/README.md
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/src/rebuild.py
Labels: bug

#3147 Allow 'use' parameter with service module (args)
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
Labels: bug

#3149 Avoid 'Unrecognized type' errors with jinja rule
  .config/dictionary.txt
  examples/playbooks/rule-jinja-pass.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3150 Avoid "unable to evaluate string as dictionary" with args rule
  src/ansiblelint/rules/args.py
Labels: bug

#3157 Avoid test ... require a dictionary error with jinja rule
  examples/playbooks/rule-jinja-pass.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3158 Fixed args rule error for synchronize module
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
Labels: bug

#3162 Implement galaxy[no-runtime] check for meta/runtime.yml file
  .github/workflows/tox.yml
  examples/collection/galaxy.yml
  examples/collection/meta/runtime.yml
  examples/galaxy_no_required_tags/fail/meta/runtime.yml
  examples/galaxy_no_required_tags/pass/meta/runtime.yml
  examples/meta/meta/runtime.yml
  examples/no_changelog/meta/runtime.yml
  src/ansiblelint/rules/galaxy.md
  src/ansiblelint/rules/galaxy.py
  test/schemas/test/meta/runtime.yml
Labels: bug

#3166 Ignore risky-shell-pipe with pwsh
  .config/dictionary.txt
  examples/playbooks/rule-risky-shell-pipe-pass.yml
  src/ansiblelint/rules/risky_shell_pipe.md
  src/ansiblelint/rules/risky_shell_pipe.py
Labels: bug

#3168 Avoid duplicate GHA pipeline runs
  .github/workflows/tox.yml
Labels: skip-changelog

#3175 docs: fix link for rule galaxy[no-runtime]
  src/ansiblelint/rules/galaxy.md
Labels: bug

#3176 Fix "helpUri" assignment for SARIF output
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_sarif.py
Labels: bug

#3185 Fix tilde interpolation in PATH
  src/ansiblelint/__main__.py
Labels: bug

#3190 Switch to mkdocs-ansible
  .config/requirements-docs.txt
  .config/requirements-lock.txt
  .config/requirements.txt
  docs/configuring.md
  mkdocs.yml
Labels: skip-changelog, bug

#3194 Update test dependencies
  .config/requirements-docs.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  src/ansiblelint/schemas/galaxy.json
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3195 Refactor task iterator to return an object
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/yaml_utils.py
Labels: bug

#3205 Allow templated boolean for any_errors_fatal
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
Labels: bug

#3208 Update dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/schemas/__store__.json
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3210 Refactor command-instead-of-shell fixtures in standalone examples
  examples/playbooks/rule-command-instead-of-shell-fail.yml
  examples/playbooks/rule-command-instead-of-shell-pass.yml
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: skip-changelog

#3187 docs: Provide more information about the dangers of run_once
  src/ansiblelint/rules/run_once.md
Labels: bug

#3207 Document fix for literal_compare `== False`
  src/ansiblelint/rules/literal_compare.md
Labels: bug

#3211 Refactor tests
  examples/playbooks/rule-key-order-pass.yml
  src/ansiblelint/rules/key_order.py
Labels: skip-changelog

#3217 Updated dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3224 Fix link for usage.md (Linting playbooks and roles)
  docs/usage.md
Labels: bug

#3230 Update no-handler rule to accept 'not changed'
  src/ansiblelint/rules/no_handler.py
Labels: bug
