Repository ansible/ansible-lint, pull requests merged in 2023-10, with the labels that each got.

#3800 Update some platform versions in meta.json
  src/ansiblelint/schemas/meta.json
Labels: bug

#3806 Fix wget command arguments in github action
  action.yml
Labels: bug

#3309 Allow linting plugin EXAMPLES as playbooks
  .config/dictionary.txt
  .github/workflows/tox.yml
  plugins/modules/fake_module.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  test/test_file_utils.py
Labels: enhancement

#3808 Fix actions-tagger arguments
  .github/workflows/release.yml
Labels: bug

#3814 Update SPDX license list
  .config/dictionary.txt
  .config/requirements-test.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/galaxy.json
  test/test_schemas.py
Labels: bug

#3812 Remove bump-homebrew-formula configuration
  .github/workflows/release.yml
Labels: skip-changelog

#3813 Add support for python 3.12
  .github/workflows/tox.yml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
Labels: bug

#3817 Avoid false-positive test failure with schema updates
  src/ansiblelint/schemas/__main__.py
  test/test_schemas.py
Labels: skip-changelog

#3821 Update linters
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/runner.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/local-content/collections/ansible_collections/testns/test_collection/plugins/filter/test_filter.py
  test/local-content/test-roles-failed-complete/roles/role2/test_plugins/b_failed_complete.py
  test/rules/test_inline_env_var.py
  test/test_examples.py
  test/test_formatter_base.py
Labels: skip-changelog

#3827 Reduce use of options global variable
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml_rule.py
  test/test_ansiblelintrule.py
  test/test_cli.py
  test/test_mockings.py
  test/test_rules_collection.py
  test/test_schemas.py
  test/test_transformer.py
Labels: skip-changelog

#3815 Add play level autofix for key-order rule
  .github/workflows/tox.yml
  examples/playbooks/transform-key-order-play.transformed.yml
  examples/playbooks/transform-key-order-play.yml
  src/ansiblelint/rules/key_order.py
  test/test_transformer.py
Labels: bug

#3824 Fix SARIF-formatter severity levels
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_sarif.py
Labels: bug

#3823 Support complex requirements in argument_specs.yml
  src/ansiblelint/schemas/role-arg-spec.json
  test/schemas/test/roles/foo/meta/argument_specs.yml
Labels: bug

#3833 Document environment variables
  src/ansiblelint/cli.py
  src/ansiblelint/constants.py
Labels: bug

#3819 Avoid creating temporary YAML files inside source tree
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_file_utils.py
  test/test_utils.py
Labels: bug

#3835 Add environment variable for skipping schema update
  src/ansiblelint/__main__.py
  src/ansiblelint/constants.py
Labels: bug

#3837 Temporary avoid auto-fixing YAML files not owned by ansible
  .github/workflows/tox.yml
  examples/.github/workflows/sample.yml
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/transformer.py
  test/test_transformer.py
Labels: bug

#3841 Add some platforms to `meta.json`
  src/ansiblelint/schemas/meta.json
Labels: bug

#3844 Hide stacktrace when loading invalid yaml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/playbooks/invalid-transform.yml
  src/ansiblelint/yaml_utils.py
  test/test_transformer.py
Labels: bug

#3838 Avoid false positives for handler in roles handlers directory
  .github/workflows/tox.yml
  examples/roles/role_with_handler/handlers/main.yml
  examples/roles/role_with_handler/tasks/main.yml
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/utils.py
Labels: bug

#3845 Update supported Ubuntu versions in `meta.json`
  src/ansiblelint/schemas/meta.json
Labels: bug

#3843 Add support for Rocky
  src/ansiblelint/schemas/meta.json
Labels: bug

#3852 Improve test function names
  .config/requirements-test.txt
  .config/requirements.txt
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__store__.json
  test/test_file_path_evaluation.py
  test/test_formatter_base.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_main.py
  test/test_matcherrror.py
  test/test_runner.py
  test/test_skiputils.py
  test/test_transform_mixin.py
Labels: skip-changelog

#3855 Fix bug with auto-fix ending too soon
  src/ansiblelint/transformer.py
Labels: bug

#3856 Document pre-commit access to ansible community bundle
  .config/dictionary.txt
  docs/_autofix_rules.md
  docs/configuring.md
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/rules/yaml_rule.py
  tools/generate_docs.py
Labels: bug

#3857 Avoid exception caused by accidental unloading of core rules
  .config/dictionary.txt
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/__init__.py
  test/test_profiles.py
Labels: bug

#3869 Support `ruamel-yaml >= 0.18.2`
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: bug

#3870 Update linters
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/utils.py
Labels: skip-changelog

#3873 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3874 Avoid creating new load method in our custom formatter
  pyproject.toml
  src/ansiblelint/transformer.py
  src/ansiblelint/yaml_utils.py
  test/conftest.py
  test/test_yaml_utils.py
Labels: bug

#3877 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog
