Repository ansible/ansible-lint, pull requests merged in 2023-09, with the labels that each got.

#3704 Add missing word to risky-shell-pipe docs
  src/ansiblelint/rules/risky_shell_pipe.md
Labels: bug

#3702 Avoid no-handlers false positives
  examples/playbooks/no_handler_pass.yml
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/utils.py
Labels: bug

#3705 Add auto-fixing implementation for key-order[task] rule
  .github/workflows/tox.yml
  examples/playbooks/transform-key-order.transformed.yml
  examples/playbooks/transform-key-order.yml
  src/ansiblelint/rules/key_order.py
  test/test_transformer.py
Labels: enhancement

#3709 Avoid deprecated-bare-vars false positive with file paths
  examples/playbooks/rule-deprecated-bare-vars-fail.yml
  examples/playbooks/rule-deprecated-bare-vars-pass.yml
  src/ansiblelint/rules/deprecated_bare_vars.py
Labels: bug

#3716 Allow installation of pre-release collection version as dependencies
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: bug

#3719 Update transform for `key-order` rule
  src/ansiblelint/rules/key_order.py
Labels: bug

#3723 Require ansible-compat>=4.1.10
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: bug

#3721 Add auto-fixing implementation for `no-jinja-when` rule
  .github/workflows/tox.yml
  examples/playbooks/transform-no-jinja-when.transformed.yml
  examples/playbooks/transform-no-jinja-when.yml
  src/ansiblelint/rules/no_jinja_when.py
  test/test_transformer.py
Labels: enhancement

#3734 Support only_upgrade
  examples/playbooks/package-check-failure.yml
  examples/playbooks/package-check-success.yml
  src/ansiblelint/rules/package_latest.md
  src/ansiblelint/rules/package_latest.py
  test/rules/test_package_latest.py
Labels: bug

#3745 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/__main__.py
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: skip-changelog

#3743 Fix transform exception with local_action with old syntax
  .github/workflows/tox.yml
  examples/playbooks/tasks/local_action.transformed.yml
  examples/playbooks/tasks/local_action.yml
  src/ansiblelint/rules/deprecated_local_action.py
Labels: bug

#3730 Properly avoid `pipx` venv path to be included in altered path warning
  src/ansiblelint/__main__.py
Labels: bug

#3746 Fix docs typo
  docs/usage.md
Labels: bug

#3747 Avoid IndexError exception with jinja transform
  .github/workflows/tox.yml
  examples/playbooks/rule-jinja-before.transformed.yml
  examples/playbooks/rule-jinja-before.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3748 Rename --write option to --fix
  .ansible-lint
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/rules/__init__.py
  test/test_cli.py
Labels: enhancement

#3749 Respect cgroup CPU limits when running inside containers
  src/ansiblelint/runner.py
Labels: enhancement

#3751 Clarify auto-fix arguments use
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/rules/__init__.py
  test/test_cli.py
Labels: bug

#3750 Fix the detection of role vars missing role prefix
  .github/workflows/tox.yml
  examples/roles/role_vars_prefix_detection/defaults/main.yml
  examples/roles/role_vars_prefix_detection/vars/main.yml
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3755 Meta runtime supported version update
  examples/meta_runtime_version_checks/pass/meta/runtime.yml
  src/ansiblelint/rules/meta_runtime.md
  src/ansiblelint/rules/meta_runtime.py
Labels: bug

#3758 Include level in SARIF results
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_sarif.py
Labels: bug

#3737 List all the fixable rules in CLI via `--list-rules`
  .github/workflows/tox.yml
  src/ansiblelint/generate_docs.py
  test/test_list_rules.py
Labels: bug

#3770 Expose rules that have autofix capability in docs
  docs/autofix.md
  mkdocs.yml
  src/ansiblelint/rules/command_instead_of_shell.md
Labels: bug

#3776 Update rulebook schema (name is now required)
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
Labels: bug

#3766 Sanity Rule Ignore Additions and Updates
  examples/sanity_ignores/tests/sanity/ignore-2.13.txt
  examples/sanity_ignores/tests/sanity/ignore-2.15.txt
  examples/sanity_ignores/tests/sanity/ignore-2.9.txt
  src/ansiblelint/rules/sanity.md
  src/ansiblelint/rules/sanity.py
Labels: bug

#3773 Avoid false error caused by TypeError with jinja rule
  examples/playbooks/rule-jinja-pass.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3774 Prune reported errors after autofix
  .github/workflows/tox.yml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/config.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/runner.py
  src/ansiblelint/transformer.py
  test/test_formatter_base.py
  test/test_transformer.py
Labels: bug

#3779 Add pipeline for testing with prereleased dependencies
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#3782 Allow retagging on release
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#3783 Correct regression with use of --fix
  src/ansiblelint/cli.py
Labels: bug

#3784 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3789 Accept underline prefix when checking var-naming
  examples/playbooks/role_vars_prefix_detection.yml
  examples/roles/var_naming_pattern/tasks/include_task_with_vars.yml
  src/ansiblelint/rules/var_naming.md
  src/ansiblelint/rules/var_naming.py
Labels: bug

#3791 Document autofix ability for rules that supports it
  mkdocs.yml
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/command_instead_of_shell.md
  src/ansiblelint/rules/deprecated_local_action.md
  src/ansiblelint/rules/fqcn.md
  src/ansiblelint/rules/jinja.md
  src/ansiblelint/rules/key_order.md
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/no_free_form.md
  src/ansiblelint/rules/no_jinja_when.md
  src/ansiblelint/rules/no_log_password.md
  src/ansiblelint/rules/partial_become.md
  tools/generate_docs.py
Labels: bug

#3793 Enable useless-supression with pylint
  pyproject.toml
Labels: skip-changelog

#3785 Make the autofix rule list dynamic in documentation
  docs/_autofix_rules.md
  docs/autofix.md
  mkdocs.yml
  tools/generate_docs.py
Labels: bug

#3797 Correct listing of autofix rules in documentation
  docs/autofix.md
Labels: bug

#3798 Do not use github action path for running ansible lint
  README.md
  action.yml
Labels: bug
