Repository ansible/ansible-lint, pull requests merged in 2023-12, with the labels that each got.

#3922 Fix auto capitalization for name[prefix] rule
  .github/workflows/tox.yml
  examples/roles/name_prefix/tasks/test.transformed.yml
  examples/roles/name_prefix/tasks/test.yml
  src/ansiblelint/rules/name.py
  test/test_transformer.py
Labels: bug

#3929 Fix backward compatibility
  .config/requirements-lock.txt
Labels: bug

#3934 docs: fix grammatical issue in philosophy Q&A section
  docs/philosophy.md
Labels: patch

#3946 Documentation improvement
  .ansible-lint-ignore
  .config/dictionary.txt
  .readthedocs.yml
  README.md
  docs/installing.md
  mkdocs.yml
  pyproject.toml
  src/ansiblelint/app.py
  src/ansiblelint/constants.py
  test/test_internal_rules.py
  test/test_loaders.py
  tox.ini
Labels: bug

#3945 Improve transformation for `no-free-form` rule
  examples/playbooks/transform-no-free-form.transformed.yml
  examples/playbooks/transform-no-free-form.yml
  src/ansiblelint/rules/no_free_form.py
  test/test_transformer.py
Labels: bug

#3955 GHA: Do not ignore upload failures
  .github/workflows/tox.yml
Labels: skip-changelog

#3956 gha: disable latest tag
  .github/workflows/release.yml
Labels: skip-changelog

#3949 Ignore set-property for systemd command
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#3959 Remove dependency on newer requests library
  .config/requirements.in
Labels: bug
