Repository ansible/ansible-lint, pull requests merged in 2023-08, with the labels that each got.

#3637 Improve profile information on summary line
  src/ansiblelint/app.py
Labels: bug

#3631 fixes dead marketplace link
  docs/installing.md
Labels: bug

#3653 Document `yaml[line-length]` rule
  src/ansiblelint/rules/yaml.md
Labels: bug

#3664 Update ansible-compat used for testing
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: bug

#3654 Adapt tests in preparation for newer compat
  examples/.collection/CHANGELOG.rst
  examples/.collection/galaxy.yml
  examples/.collection/meta/runtime.yml
  examples/.collection/plugins/modules/alpha.py
  examples/.collection/plugins/modules/deep/beta.py
  examples/.invalid_dependencies/CHANGELOG.rst
  examples/.invalid_dependencies/galaxy.yml
  examples/.invalid_dependencies/meta/runtime.yml
  examples/.no_changelog/galaxy.yml
  examples/.no_changelog/meta/runtime.yml
  examples/.no_collection_version/changelogs/changelog.yaml
  examples/.no_collection_version/galaxy.yml
  examples/.test_collection/README.md
  examples/.test_collection/galaxy.yml
  examples/.test_collection/roles/my_role/tasks/main.yml
  examples/.test_collection/roles/my_role2/tasks/main.yml
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/var_naming.py
  test/test_file_utils.py
Labels: skip-changelog, bug

#3641 Ensure that single space between tasks is preserved when using --write
  .github/workflows/tox.yml
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-4.yml
  test/fixtures/formatting-after/fmt-5.yml
  test/fixtures/formatting-before/fmt-4.yml
  test/fixtures/formatting-before/fmt-5.yml
  test/fixtures/formatting-prettier/fmt-4.yml
  test/fixtures/formatting-prettier/fmt-5.yml
  test/test_yaml_utils.py
Labels: bug

#3623 Update `version_added` for complexity rule
  src/ansiblelint/rules/complexity.py
Labels: bug

#3642 Clarify loop-var-prefix rule and code snippet
  src/ansiblelint/rules/loop_var_prefix.md
Labels: bug

#3675 Transform functionality for command_instead_of_shell
  .github/workflows/tox.yml
  examples/playbooks/transform_command_instead_of_shell.transformed.yml
  examples/playbooks/transform_command_instead_of_shell.yml
  src/ansiblelint/rules/command_instead_of_shell.py
  test/test_transformer.py
Labels: enhancement

#3602 Limit the maximum block depth
  .ansible-lint
  examples/playbooks/rule-complexity-fail.yml
  examples/playbooks/rule-complexity-pass.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/complexity.md
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: enhancement

#3676 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3681 Update rulebook schema
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
Labels: bug

#3684 Include links to documentation for schema validation errors
  .readthedocs.yml
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/execution-environment.json
  src/ansiblelint/schemas/galaxy.json
  src/ansiblelint/schemas/inventory.json
  src/ansiblelint/schemas/main.py
  src/ansiblelint/schemas/meta.json
  src/ansiblelint/schemas/molecule.json
  src/ansiblelint/schemas/requirements.json
  src/ansiblelint/schemas/role-arg-spec.json
  src/ansiblelint/schemas/vars.json
Labels: bug

#3697 Avoid false positive with var-name rule on roles
  examples/playbooks/var-naming/rule-var-naming-fail.yml
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
Labels: bug

#3699 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/rules/name.py
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: skip-changelog

#3700 Test transformer with block indentation indicators
  .github/workflows/tox.yml
  examples/playbooks/transform-block-indentation-indicator.transformed.yml
  examples/playbooks/transform-block-indentation-indicator.yml
  test/test_transformer.py
Labels: skip-changelog

#3701 Make schema validation messages more explicit
  examples/rulebooks/rulebook-fail.yml
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/main.py
Labels: enhancement

#3691 Add auto-fixing implementation for `jinja[spacing]` rule
  .github/workflows/tox.yml
  examples/playbooks/transform-jinja.transformed.yml
  examples/playbooks/transform-jinja.yml
  src/ansiblelint/errors.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/jinja.py
  test/test_transformer.py
Labels: enhancement
