Repository ansible/ansible-lint, pull requests merged in 2023-02, with the labels that each got.

#2967 Update schemas
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
Labels: skip-changelog

#2960 Add support for Ansible 2.15 (#2960
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  src/ansiblelint/app.py
  test/test_utils.py
Labels: bug

#2963 Improved coverage for empty string compare and galaxy rules
  .github/workflows/tox.yml
  examples/no_collection_version/galaxy.yml
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/galaxy.py
Labels: bug, test

#2926 Do not install collection locally in offline mode (#2926)Fixes https://github.com/ansible/ansible-lint/issues/2922
  src/ansiblelint/app.py
Labels: bug

#2940 Change the way rules are listed from command line (#2940
  .config/dictionary.txt
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/generate_docs.py
  test/test_list_rules.py
  test/test_rules_collection.py
Labels: bug

#2876 Avoid caching on role_name regex (#2876)Co-authored-by: Sorin Sbarnea <ssbarnea@redhat.com>Co-authored-by: Sorin Sbarnea <ssbarnea@redhat.com>
  src/ansiblelint/rules/role_name.py
Labels: bug

#2971 Allow noqa comments without colons (#2971
  docs/usage.md
  examples/playbooks/noqa-nested.yml
  examples/playbooks/noqa.yml
  examples/playbooks/run-once-fail.yml
  examples/playbooks/test_skip_inside_yaml.yml
  examples/roles/meta_noqa/meta/main.yml
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/skip_utils.py
  test/rules/test_line_too_long.py
  test/test_import_include_role.py
  test/test_skip_import_playbook.py
  test/test_skip_inside_yaml.py
  test/test_skip_playbook_items.py
  test/test_skiputils.py
Labels: bug

#2973 Fix install-reqs.sh logic
  examples/playbooks/collections/.gitignore
  examples/playbooks/collections/requirements.yml
  tools/install-reqs.sh
Labels: skip-changelog

#2974 Fix exception related to include_tasks (#2974
  .github/workflows/tox.yml
  a.ansi
  examples/playbooks/tasks/bug-2875.yml
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#2975 Make no-jinja-when also detect list conditions
  examples/playbooks/jinja2-when-failure.yml
  examples/playbooks/jinja2-when-success.yml
  examples/playbooks/rule-no-jinja-when-fail.yml
  examples/playbooks/rule-no-jinja-when-pass.yml
  src/ansiblelint/rules/no_jinja_when.py
  test/rules/test_no_jinja_when.py
Labels: bug

#2982 Bump ansible-lint homebrew formula on release
  .github/workflows/release.yml
Labels: skip-changelog

#2985 Updated galaxy rule imports and improved code coverage (#2985)Co-authored-by: Ajinkya Udgirkar <audgirka@redhat.com> Fixes https://github.com/ansible/ansible-lint/issues/2979
  src/ansiblelint/rules/galaxy.py
Labels: bug

#2991 IDE settings update
  .config/dictionary.txt
  .config/requirements-test.txt
  .config/requirements.txt
  .vscode/settings.json
  pyproject.toml
Labels: skip-changelog

#2993 Keep jinja2 leading spaces
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#2996 Bump cryptography to 39.0.1
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
Labels: bug

#2995 Improving coverage for meta_no_tags
  .github/workflows/tox.yml
  src/ansiblelint/rules/meta_no_tags.py
Labels: skip-changelog, test

#3001 Avoid stack trace caused by bad filename matching pattern
  src/ansiblelint/rules/syntax_check.py
Labels: bug

#3000 Rename meta-unsupported-ansible to meta-runtime and correct its logic
  .github/workflows/tox.yml
  docs/profiles.md
  docs/rules/index.md
  docs/rules/meta-runtime.md
  docs/rules/meta-unsupported-ansible.md
  examples/meta_runtime_version_checks/fail_0/meta/runtime.yml
  examples/meta_runtime_version_checks/fail_2/meta/runtime.yml
  examples/meta_runtime_version_checks/pass/meta/runtime.yml
  mkdocs.yml
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/meta_runtime.md
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/schemas/ansible-lint-config.json
  tox.ini
Labels: bug

#3007 Improved documentation building
  .config/dictionary.txt
  .config/requirements-docs.txt
  .config/requirements.txt
  docs/configuring.md
  docs/contributing.md
  docs/index.md
  docs/philosophy.md
  docs/profiles.md
  mkdocs.yml
  src/ansiblelint/_internal/warning.md
  src/ansiblelint/data/profiles.yml
  src/ansiblelint/rules/args.md
  src/ansiblelint/rules/latest.md
  src/ansiblelint/rules/meta_video_links.md
  test/rules/test_meta_video_links.py
Labels: bug

#3005 Fix playbook/rulebook detection
  .github/workflows/tox.yml
  src/ansiblelint/file_utils.py
  src/ansiblelint/testing/__init__.py
  test/test_skiputils.py
Labels: bug

#3006 Adding galaxy[tag] check for required tags
  .github/workflows/tox.yml
  examples/collection/galaxy.yml
  examples/galaxy_no_required_tags/fail/changelogs/changelog.yaml
  examples/galaxy_no_required_tags/fail/galaxy.yml
  examples/galaxy_no_required_tags/pass/changelogs/changelog.yaml
  examples/galaxy_no_required_tags/pass/galaxy.yml
  examples/meta/galaxy.yml
  examples/no_changelog/galaxy.yml
  examples/no_collection_version/changelogs/changelog.yaml
  examples/no_collection_version/galaxy.yml
  src/ansiblelint/rules/galaxy.md
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-lint-config.json
  test/test_progressive.py
Labels: bug

#3009 Use XDG_CACHE_HOME instead of XDG_CONFIG_CACHE
  src/ansiblelint/config.py
Labels: bug

#3014 Increase the test coverage
  .github/workflows/tox.yml
  pyproject.toml
  src/ansiblelint/_mockings.py
  src/ansiblelint/errors.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/main.py
  src/ansiblelint/testing/__init__.py
  test/test_constants.py
  test/test_main.py
  test/test_mockings.py
  test/test_schemas.py
  tox.ini
Labels: bug

#3016 Clean testing code
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
  test/conftest.py
  test/fixtures/test_regenerate_formatting_fixtures.py
  test/test_yaml_utils.py
Labels: skip-changelog

#3004 Load rule ignores from external text file
  .ansible-lint
  .ansible-lint-ignore
  .github/workflows/tox.yml
  docs/configuring.md
  docs/usage.md
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/loaders.py
  test/test_app.py
  test/test_loaders.py
Labels: feature

#2983 Ensure that rule import failures are not ignored
  src/ansiblelint/rules/__init__.py
Labels: bug

#3019 Move empty-playbook to syntax-check
  src/ansiblelint/_internal/warning.md
  src/ansiblelint/config.py
  src/ansiblelint/rules/syntax_check.md
  src/ansiblelint/rules/syntax_check.py
  test/test_utils.py
  test/test_with_skip_tagid.py
Labels: bug

#3021 Fixes no-tabs issue with fqcn actions
  examples/playbooks/rule-no-tabs.yml
  src/ansiblelint/rules/no_tabs.py
Labels: bug

#3022 Test coverage for meta_incorrect, no_jinja_when rules
  .github/workflows/tox.yml
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/no_jinja_when.py
  test/rules/test_meta_change_from_default.py
Labels: skip-changelog, test

#3020 Mark syntax-check as unskippable
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  test/test_app.py
  test/test_with_skip_tagid.py
Labels: bug

#3023 Update test dependencies
  .config/requirements-lock.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3024 Recognize systemctl kill as a valid command
  .config/dictionary.txt
  .github/workflows/tox.yml
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#3029 Allow {% in schema full-jinja check
  .ansible-lint
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/negative_test/playbooks/environment.yml.md
  test/schemas/negative_test/playbooks/ignore_errors.yml.md
  test/schemas/negative_test/playbooks/invalid-serial.yml.md
  test/schemas/negative_test/playbooks/invalid_become.yml.md
  test/schemas/negative_test/playbooks/no_log_partial_template.yml.md
  test/schemas/negative_test/playbooks/no_log_string.yml.md
  test/schemas/negative_test/playbooks/tasks/args_string.yml.md
  test/schemas/negative_test/playbooks/tasks/become_method_untemplated.yml.md
  test/schemas/negative_test/playbooks/tasks/ignore_errors.yml.md
  test/schemas/negative_test/playbooks/tasks/no_log_string.yml.md
  test/schemas/negative_test/playbooks/tasks/with_items_untemplated_string.yml.md
  test/schemas/test/playbooks/full-jinja.yml
Labels: bug

#3027 Improve coverage for use bare variables deprecated rule
  examples/playbooks/rule-deprecated-bare-vars-fail.yml
  examples/playbooks/rule-deprecated-bare-vars-pass.yml
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/schemas/__store__.json
  test/rules/test_use_bare_variables.py
Labels: skip-changelog, test

#3028 Improve coverage for deprecated command syntax rule
  .github/workflows/tox.yml
  src/ansiblelint/rules/deprecated_command_syntax.py
Labels: skip-changelog, test

#3033 Add full coverage to no-prompting rule
  examples/playbooks/rule-no-prompting.yml
  src/ansiblelint/rules/no_prompting.py
Labels: skip-changelog, test

#3034 Recognize role-name[path] also inside roles block
  .github/workflows/tox.yml
  examples/playbooks/rule-role-name-path.yml
  examples/roles/subfolder/1st_role/tasks/main.yml
  examples/roles/subfolder/2nd_role/tasks/main.yml
  examples/roles/subfolder/3rd_role/tasks/main.yml
  src/ansiblelint/rules/role_name.py
Labels: bug

#3030 Allow only use of quoted octals
  .config/dictionary.txt
  .yamllint
  examples/playbooks/rule-args-module-pass-1.yml
  examples/playbooks/rule-avoid-implicit-fail.yml
  examples/playbooks/rule-avoid-implicit-pass.yml
  examples/playbooks/rule-fqcn-fail.yml
  examples/playbooks/rule-no-handler-fail.yml
  examples/playbooks/rule-no-handler-pass.yml
  examples/playbooks/rule-risky-file-permissions-pass.yml
  examples/playbooks/rule-risky-octal-pass.yml
  examples/playbooks/rule-validate-module-options-pass-2.yml
  src/ansiblelint/rules/risky_octal.md
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-2.yml
  test/fixtures/formatting-prettier/fmt-2.yml
Labels: bug, enhancement

#3035 Enable syntax-check on roles
  .github/workflows/tox.yml
  examples/roles/invalid_due_syntax/tasks/main.yml
  src/ansiblelint/rules/syntax_check.py
  test/test_utils.py
Labels: bug

#3036 Add full coverage to meta_video_links rule
  .github/workflows/tox.yml
  test/rules/test_meta_video_links.py
Labels: skip-changelog, test

#3038 Add full coverage to no_relative_paths rule
  test/rules/test_no_relative_paths.py
Labels: skip-changelog, test

#3037 Removed experimental flag from multiple rules
  examples/playbooks/strict-mode.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/var_naming.py
  test/test_strict.py
Labels: feature

#3039 Improve jinja2 rule error handling
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/role_name.py
Labels: bug

#3040 Ignore known problematic modules from args rule
  src/ansiblelint/rules/args.py
Labels: bug

#3042 Improve documentation on var-naming
  src/ansiblelint/rules/var_naming.md
Labels: bug

#3043 profiles: include all rules when listing all rules or tags
  src/ansiblelint/rules/__init__.py
Labels: bug

#3044 Improve jinja error line number identification
  examples/playbooks/rule-jinja-invalid.yml
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/yaml_utils.py
Labels: bug

#3046 Fix ignore file generation
  src/ansiblelint/app.py
Labels: bug

#3050 Improve no-changed-when rule
  .github/workflows/tox.yml
  examples/playbooks/rule-no-changed-when-fail.yml
  examples/playbooks/rule-no-changed-when-pass.yml
  examples/playbooks/rule-no-free-form-pass.yml
  src/ansiblelint/rules/no_changed_when.md
  src/ansiblelint/rules/no_changed_when.py
Labels: bug

#3051 Remove support for python 3.8
  .pre-commit-config.yaml
  conftest.py
  docs/contributing.md
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/logger.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/meta_no_info.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/testing/fixtures.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/conftest.py
  test/test_profiles.py
  test/test_transform_mixin.py
  test/test_transformer.py
  test/test_utils.py
  tox.ini
Labels: bug, enhancement

#3053 Allow /dev/null to be passed as config file
  .github/workflows/tox.yml
  src/ansiblelint/cli.py
  test/test_cli.py
Labels: bug

#3054 Document output formats
  docs/usage.md
  src/ansiblelint/formatters/__init__.py
  tox.ini
Labels: bug

#3055 Avoid 'is undefined' error with jinja rule
  examples/playbooks/rule-jinja-valid.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3056 Avoid 'not defined' with jinja rule
  examples/playbooks/rule-jinja-valid.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3057 Change CodeClimate severity to expose error or warning levels
  src/ansiblelint/formatters/__init__.py
  test/test_formatter_json.py
Labels: bug

#3059 Avoid reformatting of strings with line feeds and no jinja
  .github/workflows/tox.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#3060 Avoid jinja rule triggering with mutually exclusive arguments
  examples/playbooks/rule-args-module-fail.yml
  examples/playbooks/rule-args-module-pass.yml
  src/ansiblelint/rules/args.py
Labels: bug

#3063 Update test deps
  .config/requirements-docs.txt
  .config/requirements.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#3070 Variable Naming Rule - Added coverage for missing lines
  .github/workflows/tox.yml
  src/ansiblelint/rules/var_naming.py
Labels: skip-changelog, test

#3073 Added coverage for no-same-owner rule
  examples/roles/role_for_no_same_owner/tasks/fail.yml
  src/ansiblelint/rules/no_same_owner.py
Labels: skip-changelog, test

#3074 added coverage for missing lines for no-tabs rule
  examples/playbooks/rule-no-tabs.yml
  src/ansiblelint/rules/no_tabs.py
Labels: skip-changelog, test

#3071 fix exclude-path test
  test/test_cli.py
Labels: bug

#3075 Improved ignore file handling
  .ansible-lint
  .config/dictionary.txt
  .github/workflows/tox.yml
  docs/configuring.md
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/loaders.py
  test/test_loaders.py
Labels: bug

#3078 Remove "mode: preserve" from risky file perms doc, add copy example
  src/ansiblelint/rules/risky_file_permissions.md
Labels: bug

#3083 src/ansiblelint/schemas/meta.json: add SLES15SP5
  src/ansiblelint/schemas/meta.json
Labels: skip-changelog

#3094 Removed lines not required for code coverage (meta-no-info rule)
  src/ansiblelint/rules/meta_no_info.py
Labels: bug, test

#3089 Simplify logic for meta-runtime rule
  src/ansiblelint/rules/meta_runtime.py
Labels: bug, test

#3095 Added coverage for missing line for no-free-form rule
  examples/playbooks/rule-no-free-form-fail.yml
  src/ansiblelint/rules/no_free_form.py
Labels: skip-changelog, test

#3091 Added test coverage for missing lines empty-string-compare rule
  examples/playbooks/rule-empty-string-compare-fail.yml
  examples/playbooks/rule-empty-string-compare-pass.yml
  src/ansiblelint/rules/empty_string_compare.py
Labels: skip-changelog, test

#3088 Adding coverage for yaml rule
  src/ansiblelint/rules/yaml_rule.py
Labels: skip-changelog, test

#3096 Improved coverage for missing line for rule no-log-password
  .github/workflows/tox.yml
  src/ansiblelint/rules/no_log_password.py
Labels: skip-changelog, test

#3100 Allow manifest field on galaxy file schema
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/galaxy.json
  test/schemas/negative_test/galaxy_1/galaxy.yml
  test/schemas/negative_test/galaxy_1/galaxy.yml.md
  test/schemas/test/galaxy.yml
Labels: bug
