Repository ansible/ansible-lint, pull requests merged in 2024-04, with the labels that each got.

#4087 add systemctl get-default as acceptable command
  examples/playbooks/rule-command-instead-of-module-pass.yml
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#4089 Bump minimal version of black being required
  .config/requirements.in
Labels: bug, security

#4080 Use python3 executable
  .github/workflows/release.yml
  test/schemas/src/schema.spec.ts
Labels: skip-changelog

#4097 Update spdx license list
  .config/constraints.txt
  .config/requirements-test.in
  .pre-commit-config.yaml
  src/ansiblelint/schemas/galaxy.json
  test/test_schemas.py
Labels: skip-changelog

#4098 Update test to pass with ansible-core devel branch
  test/fixtures/broken-ansible.cfg/ansible.cfg
  test/test_main.py
Labels: skip-changelog

#4096 Update deps
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  src/ansiblelint/rules/__init__.py
Labels: skip-changelog

#4068 Raise exception while accessing rules by index
  src/ansiblelint/rules/__init__.py
Labels: bug

#4111 Add AstraLinux platform identification
  src/ansiblelint/schemas/meta.json
Labels: bug

#4106 Add mkdcos macro for adt installation
  docs/installing.md
  mkdocs.yml
Labels: skip-changelog

#4113 Don't NameError if there is no notify keyword to update
  examples/playbooks/name-case.transformed.yml
  examples/playbooks/name-case.yml
  src/ansiblelint/rules/name.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#4116 Fix KeyError on `key-order` rule with blocks
  .github/workflows/tox.yml
  examples/playbooks/transform-key-order-block.transformed.yml
  examples/playbooks/transform-key-order-block.yml
  src/ansiblelint/yaml_utils.py
  test/test_transformer.py
Labels: bug

#4117 Allow jinja2 expression for choices field (#4043)
  src/ansiblelint/schemas/role-arg-spec.json
Labels: bug

#4107 Fix yaml rules being included regardless of tags
  .github/workflows/tox.yml
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/schemas/__store__.json
  test/test_with_skip_tagid.py
Labels: bug

#4103 Fix #3938: don't assume working_directory is github.workspace
  action.yml
Labels: bug

#4127 Update schema tests
  test/schemas/.mocharc.json
  test/schemas/package-lock.json
  test/schemas/package.json
  test/schemas/src/schema.spec.ts
  test/schemas/tsconfig.json
Labels: skip-changelog

#4108 Don't inject CWD parent into PATH
  src/ansiblelint/__main__.py
Labels: bug

#4128 gha: use new repo name for reusable actions
  .github/workflows/push.yml
  examples/.github/workflows/sample.yml
  examples/yamllint/.github/workflows/ci.yml
Labels: bug

#4120 Make `ignore_unreachable` accept jinja templates
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  src/ansiblelint/schemas/tasks.json
  test/schemas/negative_test/playbooks/ignore-unreachable.yml
  test/schemas/negative_test/playbooks/ignore-unreachable.yml.md
  test/schemas/test/playbooks/ignore-unreachable.yml
Labels: bug
