Repository ansible/ansible-lint, pull requests merged in 2024-03, with the labels that each got.

#4058 Fix docs build
  .config/constraints.txt
  docs/usage.md
Labels: skip-changelog

#4051 Support for upcoming Ubuntu 24.04 and Fedora 40
  src/ansiblelint/schemas/meta.json
Labels: bug

#4054 [role-name] Handle string role dependencies
  examples/roles/role_with_deps_paths/meta/main.yml
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/schemas/meta.json
  test/schemas/negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml
  test/schemas/negative_test/roles/role_with_bad_deps_in_meta/meta/main.yml.md
  test/schemas/test/roles/foo/meta/main.yml
Labels: bug

#4055 Set global `cache_dir_lock`
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#4063 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#4064 Inherit secrets in ack pipeline
  .github/workflows/ack.yml
Labels: skip-changelog

#4071 Suggest adt installation
  docs/installing.md
Labels: skip-changelog, documentation

#4077 Adding EDA tag to the required galaxy.yml tags
  src/ansiblelint/rules/galaxy.py
Labels: bug
