Repository ansible/ansible-lint, pull requests merged in 2024-05, with the labels that each got.

#4130 Add lower requirements and testing
  .config/constraints.txt
  .config/dictionary.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  src/ansiblelint/schemas/__store__.json
  tox.ini
Labels: bug

#4019 Support examples for role entrypoints
  src/ansiblelint/schemas/role-arg-spec.json
  test/schemas/test/roles/foo/meta/argument_specs.yml
Labels: bug, upstream

#4131 Recognize adjacent plugins
  .github/workflows/tox.yml
  examples/playbooks/action_plugins/some_action.py
  examples/playbooks/adj_action.yml
  examples/playbooks/example.yml
  examples/playbooks/filter_plugins/some_filter.py
  examples/playbooks/test_skip_inside_yaml.yml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/utils.py
  test/test_adjacent_plugins.py
  test/test_skip_inside_yaml.py
Labels: bug

#4134 Document valid locations for requirements.yml in the docs
  src/ansiblelint/rules/syntax_check.md
Labels: bug

#4133 Continue linting other files when one has syntax-check errors
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/rules/test_syntax_check.py
  test/test_examples.py
  test/test_import_tasks.py
  test/test_runner.py
Labels: bug

#4139 Prevent execution with incompatible yamllint configuration
  .github/workflows/tox.yml
  .vscode/settings.json
  .yamllint
  examples/yamllint/incompatible-config/.yamllint
  src/ansiblelint/data/.yamllint
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: major

#4140 Address ruff TRY
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/main.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
Labels: skip-changelog

#4141 Make import_playbook recognize playbooks from within collections
  .config/constraints.txt
  .config/dictionary.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  examples/.test_collection/.ansible-lint
  examples/playbooks/test_import_playbook.yml
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_import_playbook.py
Labels: bug

#4145 Avoid reformatting hexadecimal integers
  .github/release-drafter.yml
  .github/workflows/tox.yml
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-hex.yml
  test/fixtures/formatting-before/fmt-hex.yml
  test/fixtures/formatting-prettier/fmt-hex.yml
  test/test_yaml_utils.py
Labels: bug

#4146 Allow tabs inside jinja strings
  examples/playbooks/rule-no-tabs.yml
  src/ansiblelint/rules/no_tabs.py
Labels: bug

#4148 Improve feedback for `fix`, avoid a traceback with transform
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  src/ansiblelint/transformer.py
  test/test_transformer.py
Labels: bug

#4147 Allow tabs in win_lineinfile
  examples/playbooks/rule-no-tabs.yml
  requirements.yml
  src/ansiblelint/_mockings.py
  src/ansiblelint/rules/no_tabs.py
Labels: bug

#4143 Add subdirectories to be part of the task prefix
  .github/workflows/tox.yml
  examples/playbooks/tasks/main.yml
  examples/playbooks/tasks/partial_prefix/foo.yml
  examples/playbooks/tasks/partial_prefix/main.yml
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
  test/test_file_path_evaluation.py
Labels: enhancement

#4149 Raise name[casing] violation for notify task param
  .github/workflows/tox.yml
  examples/playbooks/become.yml
  examples/playbooks/name_case_notify_fail.yml
  src/ansiblelint/rules/name.py
  test/test_transformer.py
Labels: bug

#4156 Avoid key exception during transform
  src/ansiblelint/rules/key_order.py
Labels: bug

#4158 Allow running with incompatible yamllint config
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: bug

#4159 Make linter aware of its own requirements
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  src/ansiblelint/app.py
  src/ansiblelint/requirements.py
  test/test_requirements.py
  test/test_yaml_utils.py
Labels: bug

#4155 Refactor codecov to perform a single upload and use oidc authentication
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#4182 Allow inventory to be used for playbook order key
  src/ansiblelint/schemas/ansible.json
  src/ansiblelint/schemas/playbook.json
  test/schemas/test/playbooks/order.yml
Labels: bug

#4167 Don't quote strings that start with 0 when running ansible-lint --fix.
  src/ansiblelint/yaml_utils.py
  test/fixtures/formatting-after/fmt-2.yml
  test/fixtures/formatting-before/fmt-2.yml
  test/fixtures/formatting-prettier/fmt-2.yml
Labels: bug

#4144 Support for 2.15...updating linter.
  examples/meta_runtime_version_checks/fail_2/meta/runtime.yml
  examples/meta_runtime_version_checks/pass/meta/runtime.yml
  src/ansiblelint/rules/meta_runtime.md
  src/ansiblelint/rules/meta_runtime.py
Labels: bug

#4190 Avoid stacktrace with unsupported import_playbook syntax
  .github/workflows/tox.yml
  examples/playbooks/handlers/empty.yml
  examples/playbooks/test-include.yml
  examples/playbooks/test_import_playbook_invalid.yml
  src/ansiblelint/utils.py
  test/test_import_playbook.py
Labels: bug

#4191 Refactor tokenize function
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#4194 Update linters
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/app.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/utils.py
  test/test_lint_rule.py
Labels: skip-changelog

#4196 Don't raise name[casing] on handlers with special role syntax
  examples/playbooks/name_case_notify_fail.yml
  src/ansiblelint/rules/name.py
Labels: bug
