Repository ansible/ansible-lint, pull requests merged in 2024-06, with the labels that each got.

#4195 Avoid exception with conflicting action statements
  .github/workflows/tox.yml
  examples/playbooks/conflicting_action2.yml
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/rules/test_syntax_check.py
  test/test_utils.py
Labels: bug

#4170 Fix false positive reports in is_handler function
  src/ansiblelint/utils.py
Labels: bug

#4198 Correctly recognize path with spaces with tokenize
  .github/workflows/tox.yml
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#4199 Tune coverage settings
  pyproject.toml
Labels: skip-changelog

#4202 Remove filename from MatchError class
  .github/workflows/tox.yml
  .gitignore
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/errors.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_errors.py
Labels: skip-changelog

#4204 Avoid displaying upgrade warning when installation is not pip
  .github/workflows/tox.yml
  src/ansiblelint/config.py
  test/test_main.py
Labels: bug

#4184 Respect yamllint 'document_start' rule when autofixing yaml
  .github/workflows/tox.yml
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: bug

#4176 Pickup correct path component w/ANSIBLE_ROLES_PATH
  .github/workflows/tox.yml
  examples/roles/role_detection/base/bar/defaults/main.yml
  examples/roles/role_detection/foo/defaults/main.yml
  src/ansiblelint/file_utils.py
  test/test_cli_role_paths.py
Labels: bug

#4161 Improve logic of find_children
  .github/workflows/tox.yml
  examples/playbooks/common-include-1.yml
  examples/playbooks/common-include-wrong-syntax.yml
  examples/playbooks/common-include-wrong-syntax2.yml
  examples/playbooks/common-include-wrong-syntax3.yml
  examples/playbooks/include.yml
  examples/roles/include_wrong_syntax/tasks/main.yml
  examples/roles/var_naming_pattern/tasks/include_task_with_vars.yml
  playbook.yml
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_runner.py
  test/test_yaml_utils.py
Labels: bug

#4205 Revert notify related checks, errors, transforms for listen and tests
  .github/workflows/tox.yml
  examples/playbooks/become.yml
  examples/playbooks/name_case_notify_fail.yml
  src/ansiblelint/rules/name.py
  test/test_transformer.py
Labels: bug

#4203 Adding logic for configuring supported ansible versions
  .ansible-lint
  .github/workflows/tox.yml
  examples/broken_supported_ansible_also/.ansible-lint
  examples/meta_runtime_version_checks/pass/meta/runtime.yml
  examples/meta_runtime_version_checks/pass_0/meta/runtime.yml
  examples/meta_runtime_version_checks/pass_1/meta/runtime.yml
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/rules/meta_runtime.md
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/ansible-lint-config.json
Labels: enhancement

#4209 Update Contributing docs and add tox as test optional-dependency
  .config/constraints.txt
  .config/requirements-test.in
  .gitignore
  docs/contributing.md
  src/ansiblelint/schemas/__store__.json
  tools/test-hook.sh
  tox.ini
Labels: bug

#4207 Avoid using warn for command/shell actions
  docs/usage.md
  examples/playbooks/skiptasks.yml
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/inline_env_var.py
  test/rules/test_inline_env_var.py
Labels: bug

#4215 Fix cmd args with no-free-form transformer
  examples/playbooks/transform-no-free-form.transformed.yml
  examples/playbooks/transform-no-free-form.yml
  src/ansiblelint/rules/no_free_form.py
  test/test_transformer.py
Labels: bug

#4224 Configure devel to use py311
  .github/workflows/tox.yml
Labels: skip-changelog

#4216 Fix relative imports in args rule
  .config/dictionary.txt
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  ansible.cfg
  collections/ansible_collections/local/testcollection/README.md
  collections/ansible_collections/local/testcollection/galaxy.yml
  collections/ansible_collections/local/testcollection/plugins/module_utils/__init__.py
  collections/ansible_collections/local/testcollection/plugins/module_utils/py.typed
  collections/ansible_collections/local/testcollection/plugins/modules/__init__.py
  collections/ansible_collections/local/testcollection/plugins/modules/module_with_relative_import.py
  examples/playbooks/module_relative_import.yml
  src/ansiblelint/rules/args.py
  test/rules/test_args.py
Labels: bug

#4226 Fixup YAML utils comment
  src/ansiblelint/yaml_utils.py
Labels: skip-changelog

#4213 Fix working directory when used as an github action
  action.yml
Labels: bug
