Repository ansible/ansible-lint, pull requests merged in 2024-02, with the labels that each got.

#4004 Make File Permissions Mode a String
  src/ansiblelint/rules/risky_file_permissions.md
Labels: skip-changelog

#4011 Configure codecov for ansible-lint
  .github/workflows/tox.yml
  codecov.yml
Labels: skip-changelog

#4009 Drop support for Python 3.9
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/tox.yml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  test/test_schemas.py
  tox.ini
Labels: skip-changelog

#4014 Update dependencies to include new mkdocs-ansible branding
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
Labels: skip-changelog, dependencies

#4016 Improve github workflows
  .github/workflows/tox.yml
Labels: skip-changelog

#4018 Add attributes for role argument specs
  src/ansiblelint/schemas/role-arg-spec.json
  test/schemas/test/roles/foo/meta/argument_specs.yml
Labels: bug

#4025 accept yum history and info as valid commands
  examples/playbooks/rule-command-instead-of-module-pass.yml
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#4038 Update task name in `notify` for a task against `name[casing]` error
  examples/playbooks/name-case.transformed.yml
  examples/playbooks/name-case.yml
  src/ansiblelint/rules/name.py
  src/ansiblelint/schemas/__store__.json
  test/test_transformer.py
  test/test_yaml_utils.py
Labels: bug

#4041 Add OpenWRT 23.05 to valid versions
  src/ansiblelint/schemas/meta.json
Labels: bug

#4049 Update documentation for syntax-check[unknown-module]
  src/ansiblelint/rules/syntax_check.md
Labels: bug
