Repository ansible/ansible-lint, pull requests merged in 2024-09, with the labels that each got.

#4303 chore: Update ansible-compat version
  .config/requirements.in
  .pre-commit-config.yaml
Labels: patch

#4301 fix: Add reset-failed state in executable_options
  examples/playbooks/rule-command-instead-of-module-pass.yml
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#4314 Fix upload-artifact action to work with v4.4 and newer
  .github/workflows/tox.yml
Labels: bug

#4309 Community comms
  README.md
  docs/contributing.md
  mkdocs.yml
Labels: skip-changelog

#4299 fix: Adding missing EE option skip_pip_install
  src/ansiblelint/schemas/execution-environment.json
Labels: bug

#4320 Fix for ignoring test / directories by fqcn[deep] rule
  .github/workflows/tox.yml
  examples/.collection/plugins/modules/tests/gamma.py
  src/ansiblelint/rules/fqcn.py
Labels: bug

#4322 Docs: remove IRC/ML/google.groups remnants
  docs/contributing.md
Labels: patch, documentation

#4336 Require ansible-compat>=24.9.1
  .config/constraints.txt
  .config/requirements.in
Labels: bug

#4339 Move PYTEST_REQPASS to tox.ini to allow its update from forks
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#4315 Handle bare exception case from nested jinja2 vars
  examples/playbooks/jinja-nested-vars.yml
  src/ansiblelint/rules/jinja.py
  tox.ini
Labels: bug

#4340 Correct use of working directory with ansible-lint github action
  .github/workflows/tox.yml
  README.md
  action.yml
  docs/installing.md
  src/ansiblelint/schemas/__store__.json
Labels: bug

#4291 Remove requirement of options field in argument_specs.yaml
  src/ansiblelint/schemas/role-arg-spec.json
  test/schemas/test/roles/description-only/meta/main.yml
Labels: bug

#4307 Fix missing MatchErrors due to hash collisions
  examples/playbooks/vars/rule_var_naming_fails_files/bar.yml
  examples/playbooks/vars/rule_var_naming_fails_files/foo.yml
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/utils.py
  tox.ini
Labels: bug

#4342 Fix github action
  action.yml
Labels: bug

#4346 Update schema for missing `tags` property to builder v3 `options`
  src/ansiblelint/schemas/execution-environment.json
  test/schemas/test/execution-environment-v3.yml
Labels: bug
