Repository ansible/ansible-lint, pull requests merged in 2024-11, with the labels that each got.

#4383 Update test dependencies
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  src/ansiblelint/schemas/galaxy.json
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: skip-changelog

#4384 Avoid github annotations from test-action job
  .github/workflows/tox.yml
Labels: skip-changelog

#4382 Start using uv for testing
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog

#4380 Fixing the issue "Unfinished sentence in docs/profiles.md #4358"
  docs/profiles.md
Labels: bug, documentation

#4388 Add support for py313
  .github/workflows/tox.yml
  pyproject.toml
Labels: enhancement

#4391 Replace pip-tools with uv
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: skip-changelog

#4392 Add Fedora 41 as a platform in the metadata schema
  src/ansiblelint/schemas/meta.json
Labels: bug

#4400 Remove self type and update pre-commit hooks
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/__init__.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/skip_utils.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_utils.py
  tools/generate_docs.py
Labels: skip-changelog

#4401 Update TaskHasTag example rule used in custom-rules.md
  docs/custom-rules.md
Labels: bug

#4403 Include ! as a shell word. closes #4386
  examples/playbooks/rule-command-instead-of-shell-pass.yml
  src/ansiblelint/rules/command_instead_of_shell.py
Labels: bug

#4411 Pyright type fixes (partial)
  plugins/modules/fake_module.py
  src/ansiblelint/__main__.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__main__.py
  src/ansiblelint/schemas/main.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_schemas.py
  test/test_yaml_utils.py
Labels: skip-changelog

#4406 Fix exception with 'skipped' test
  examples/playbooks/rule-jinja-pass.yml
  src/ansiblelint/rules/jinja.py
Labels: bug

#4421 Activate and address some ruff violations (preview)
  .gitignore
  .taplo.toml
  pyproject.toml
  src/ansiblelint/app.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/loaders.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/yaml_rule.py
  src/ansiblelint/runner.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/rules/fixtures/__init__.py
  test/schemas/src/rebuild.py
  test/test_formatter_sarif.py
  test/test_main.py
Labels: bug

#4410 Prepare for pyright hook enablement
  .pre-commit-config.yaml
  .taplo.toml
  .vscode/settings.json
  conftest.py
  pyproject.toml
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  tox.ini
Labels: bug

#4424 More type fixes
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#4425 Remove dead code and prevent regressions
  .config/vulture_whitelist.py
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  package-lock.json
  package.json
  pyproject.toml
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/constants.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/test_skip_import_playbook.py
  test/test_vulture.py
Labels: bug

#4427 Update ruff to 0.8.0
  .pre-commit-config.yaml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/runner.py
  src/ansiblelint/text.py
  src/ansiblelint/transformer.py
  src/ansiblelint/utils.py
  test/test_rules_collection.py
Labels: skip-changelog

#4428 More mypy fixes
  examples/playbooks/action_plugins/some_action.py
  pyproject.toml
  src/ansiblelint/app.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/skip_utils.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_skiputils.py
Labels: skip-changelog
