Repository ansible/ansible-lint, pull requests merged in 2024-07, with the labels that each got.

#4252 Linting fixes for command_instead_of* rules (ruff:D102)
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
Labels: bug

#4246 Make the documentation not use a very old version of ansible-lint by default
  docs/installing.md
Labels: skip-changelog, documentation

#4243 Remove leftover Sphinx command directives
  docs/contributing.md
Labels: bug, documentation

#4230 Ignore var-naming[pattern] to foreign role vars
  .github/workflows/tox.yml
  collections/ansible_collections/local/testcollection/roles/bug4095/tasks/main.yml
  examples/playbooks/bug-4095.yml
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/text.py
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#4266 Fix incorrect documentation of playbook and roles linting
  docs/usage.md
Labels: skip-changelog, documentation

#4271 chore: Update .sonarcloud.properties
  .sonarcloud.properties
Labels: skip-changelog

#4272 chore: Update .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: skip-changelog

#4276 Improve --version behavior to handle remote disconnect
  .github/workflows/tox.yml
  src/ansiblelint/config.py
  test/test_main.py
Labels: bug
