Repository ansible/ansible-lint, pull requests merged in 2024-12, with the labels that each got.

#4431 Normalize version field for rules
  src/ansiblelint/_internal/rules.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/avoid_implicit.py
  src/ansiblelint/rules/command_instead_of_module.py
  src/ansiblelint/rules/command_instead_of_shell.py
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/rules/deprecated_bare_vars.py
  src/ansiblelint/rules/deprecated_local_action.py
  src/ansiblelint/rules/deprecated_module.py
  src/ansiblelint/rules/empty_string_compare.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/galaxy_version_incorrect.py
  src/ansiblelint/rules/ignore_errors.py
  src/ansiblelint/rules/inline_env_var.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/latest.py
  src/ansiblelint/rules/literal_compare.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_no_tags.py
  src/ansiblelint/rules/meta_runtime.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_changed_when.py
  src/ansiblelint/rules/no_free_form.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_log_password.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_relative_paths.py
  src/ansiblelint/rules/no_same_owner.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/only_builtins.py
  src/ansiblelint/rules/package_latest.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/playbook_extension.py
  src/ansiblelint/rules/risky_file_permissions.py
  src/ansiblelint/rules/risky_octal.py
  src/ansiblelint/rules/risky_shell_pipe.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/run_once.py
  src/ansiblelint/rules/sanity.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/rules/yaml.md
  src/ansiblelint/rules/yaml_rule.py
Labels: bug

#4432 Remove formatting options for listing rules
  src/ansiblelint/__main__.py
  src/ansiblelint/cli.py
  src/ansiblelint/generate_docs.py
  test/test_rules_collection.py
  tools/generate_docs.py
Labels: minor

#4429 Add Astra Linux Platform to platform items
  src/ansiblelint/schemas/meta.json
Labels: bug

#4433 Rename color module to output
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/output.py
Labels: refactoring, minor

#4436 Ignore some direnv/uv local temp files
  .config/dictionary.txt
  .gitignore
Labels: skip-changelog

#4437 gha: use ubuntu-24.04 runners
  .github/workflows/redirects.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .readthedocs.yml
  README.md
  docs/installing.md
Labels: skip-changelog

#4439 Fix RTD redirects pipeline
  docs/redirects.yml
Labels: skip-changelog

#4440 Update ruff to 0.8.1
  .pre-commit-config.yaml
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/transformer.py
  src/ansiblelint/yaml_utils.py
  test/test_yaml_utils.py
Labels: skip-changelog

#4396 Refactor code to avoid use of rich library
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .config/vulture_whitelist.py
  .github/lower-constraints.txt
  .pre-commit-config.yaml
  .sonarlint/connectedMode.json
  .vscode/settings.json
  cspell.config.yaml
  pyproject.toml
  src/ansiblelint/__main__.py
  src/ansiblelint/app.py
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/formatters/__init__.py
  src/ansiblelint/generate_docs.py
  src/ansiblelint/output.py
  src/ansiblelint/schemas/__store__.json
  test/test_cli_role_paths.py
  test/test_profiles.py
Labels: major

#4441 Workaround for codecov-action bug with oidc
  .github/workflows/tox.yml
Labels: skip-changelog

#4393 Accommodate specified inventory files
  examples/playbooks/test_using_inventory.yml
  inventories/bad_inventory
  inventories/bar
  inventories/baz
  inventories/foo
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/runner.py
  test/test_app.py
  tox.ini
Labels: bug

#4422 Added additional galaxy[tags] checks
  examples/galaxy_tags/galaxy_count_tags/changelogs/changelog.yaml
  examples/galaxy_tags/galaxy_count_tags/galaxy.yml
  examples/galaxy_tags/galaxy_count_tags/meta/runtime.yml
  examples/galaxy_tags/galaxy_invalid_format_tags/changelogs/changelog.yaml
  examples/galaxy_tags/galaxy_invalid_format_tags/galaxy.yml
  examples/galaxy_tags/galaxy_invalid_format_tags/meta/runtime.yml
  examples/galaxy_tags/galaxy_invalid_length_tags/changelogs/changelog.yaml
  examples/galaxy_tags/galaxy_invalid_length_tags/galaxy.yml
  examples/galaxy_tags/galaxy_invalid_length_tags/meta/runtime.yml
  examples/galaxy_tags/galaxy_no_required_tags/changelogs/changelog.yaml
  examples/galaxy_tags/galaxy_no_required_tags/galaxy.yml
  examples/galaxy_tags/galaxy_no_required_tags/meta/runtime.yml
  examples/galaxy_tags/pass/changelogs/changelog.yaml
  examples/galaxy_tags/pass/galaxy.yml
  examples/galaxy_tags/pass/meta/runtime.yml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/galaxy.md
  src/ansiblelint/rules/galaxy.py
  tox.ini
Labels: enhancement

#4447 Do inventory parsing non-multithreaded
  src/ansiblelint/runner.py
  test/test_app.py
  tox.ini
Labels: bug

#4450 Revert "Accommodate specified inventory files (#4393)"
  examples/playbooks/test_using_inventory.yml
  inventories/bad_inventory
  inventories/bar
  inventories/baz
  inventories/foo
  src/ansiblelint/cli.py
  src/ansiblelint/config.py
  src/ansiblelint/runner.py
  test/test_app.py
  tox.ini
Labels: bug

#4256 Add write_exclude_list config option
  src/ansiblelint/config.py
  src/ansiblelint/schemas/ansible-lint-config.json
  src/ansiblelint/transformer.py
  test/test_transformer.py
  tox.ini
Labels: enhancement, needs-tests
