Repository ansible/ansible-lint, pull requests merged in 2025-05, with the labels that each got.

#4598 Update documentation to reflect creator-ee deprecation
  docs/installing.md
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator.json
Labels: bug

#4597 Enable junit.xml reporting to codecov.io
  .gitignore
  pyproject.toml
  tools/report-coverage
  tox.ini
Labels: patch

#4601 Add merge_group handler for tox workflow
  .github/workflows/tox.yml
Labels: patch

#4605 Make test_broken_ansible_cfg test pass with ansible devel branch
  test/test_main.py
Labels: skip-changelog

#4591 schema/meta: support SLES 15SP6
  src/ansiblelint/schemas/meta.json
Labels: bug

#4581 replace unmaintained creator-ee with community-ansible-dev-tools
  docs/installing.md
Labels: skip-changelog

#4618 Bump ruamel to 0.18.11
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements-test.in
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
  examples/playbooks/vars/strings.transformed.yml
  pyproject.toml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: dependencies, chore
