Repository ansible/ansible-lint, pull requests merged in 2025-06, with the labels that each got.

#4622 Adopt coactions/upload-artifact
  .github/workflows/tox.yml
Labels: chore

#4617 chore: Adding support for OpenWrt 24.10
  src/ansiblelint/schemas/meta.json
Labels: chore

#4627 Improve diagnostic message when failing to load yaml files
  .pre-commit-config.yaml
  examples/broken/load-failure-invalid.yml
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/utils.py
  test/test_runner.py
  tox.ini
Labels: bug

#4630 Test alternative configuration for merge_group
  .github/workflows/tox.yml
  src/ansiblelint/schemas/__store__.json
Labels: chore

#4633 Enable ack workflow to trigger on merge_groups
  .github/workflows/ack.yml
Labels: chore

#4580 Make utils.is_playbook support fqcn import_playbook
  src/ansiblelint/utils.py
  test/test_utils.py
Labels: bug

#4587 Fix inline-env-var false positive when expand_argument_vars is used
  src/ansiblelint/rules/inline_env_var.py
  test/rules/test_inline_env_var.py
Labels: bug

#4590 docs(no-log-password): point out the opt-in nature of the rule
  src/ansiblelint/rules/no_log_password.md
Labels: skip-changelog, documentation

#4628 Adding rule to require unique task names
  examples/playbooks/lots_of_warnings.yml
  examples/playbooks/rule-args-module-fail.yml
  examples/playbooks/rule-command-instead-of-module-pass.yml
  examples/playbooks/rule-no-tabs.yml
  examples/playbooks/rule-risky-shell-pipe-pass.yml
  examples/playbooks/rule_literal_compare_fail.yml
  examples/playbooks/rule_literal_compare_pass.yml
  examples/playbooks/transform-jinja.transformed.yml
  examples/playbooks/transform-jinja.yml
  examples/playbooks/transform-no-free-form.transformed.yml
  examples/playbooks/transform-no-free-form.yml
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/name.py
Labels: enhancement

#4593 Don't pass deprecated disable_lookups to template function
  src/ansiblelint/utils.py
Labels: bug

#4566 Address too many values to unpack when there's subdirectories for roles
  collections/ansible_collections/local/testcollection/playbooks/playbook_bug4452.yml
  collections/ansible_collections/local/testcollection/roles/level1/level2/role_level3/tasks/main.yml
  collections/ansible_collections/local/testcollection/roles/subdirectory/bug4452/tasks/main.yml
  examples/playbooks/import_role_fqcn.yml
  src/ansiblelint/utils.py
  test/test_utils.py
  tox.ini
Labels: bug

#4614 Add skip option to ansible-lint-ignore file
  docs/configuring.md
  src/ansiblelint/__main__.py
  src/ansiblelint/loaders.py
  test/test_loaders.py
  tox.ini
Labels: enhancement

#4636 Remove use of PYTEST_REQPASS
  .config/dictionary.txt
  .config/requirements-test.in
  tox.ini
Labels: dependencies, chore

#4641 Update format of license in packaging metadata
  pyproject.toml
  tox.ini
Labels: bug

#4658 Update test deps
  .config/requirements-lock.txt
  .pre-commit-config.yaml
Labels: dependencies, chore

#4661 Fix typos in --list-tags help text
  src/ansiblelint/rules/__init__.py
Labels: bug

#4653 Add schema check for validating pattern specification file
  examples/patterns/correct_pattern/meta/pattern.json
  examples/patterns/incorrect_pattern/meta/pattern.json
  src/ansiblelint/config.py
  src/ansiblelint/rules/schema.md
  src/ansiblelint/rules/schema.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/pattern.json
  test/schemas/negative_test/patterns/sample_pattern/meta/pattern.json
  test/schemas/src/schema.spec.ts
  test/schemas/test/patterns/sample_pattern/meta/pattern.json
Labels: enhancement

#4668 Improve cspell configuration
  .config/dictionary.txt
  .pre-commit-config.yaml
  cspell.config.yaml
  examples/playbooks/rule-no-free-form-fail.yml
  examples/playbooks/rule-no-free-form-pass.yml
  examples/playbooks/transform-no-free-form.transformed.yml
  examples/playbooks/transform-no-free-form.yml
  mkdocs.yml
  src/ansiblelint/config.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/name.md
  src/ansiblelint/rules/no_free_form.md
  src/ansiblelint/schemas/__store__.json
  test/test_formatter.py
  test/test_loaders.py
Labels: chore
