Repository ansible/ansible-lint, pull requests merged in 2025-02, with the labels that each got.

#4507 Linter maintenance
  .config/constraints.txt
  .config/dictionary.txt
  .config/requirements-lock.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  cspell.config.yaml
  pyproject.toml
  src/ansiblelint/runner.py
  test/schemas/package-lock.json
  test/schemas/package.json
  tox.ini
Labels: skip-changelog

#4506 Improve output with broken multiline playbooks
  src/ansiblelint/__main__.py
  src/ansiblelint/file_utils.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/skip_utils.py
  test/rules/test_syntax_check.py
  test/test_import_tasks.py
Labels: bug

#4512 Require ansible-compat>=25.1.2
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: bug, dependencies

#4514 Avoid unnecessary warning when meta/runtime.yml is null
  src/ansiblelint/rules/meta_runtime.py
Labels: bug

#4518 Add .ansible to the implicit ignore list
  src/ansiblelint/file_utils.py
Labels: bug

#4519 Add git clean to allowed executable options
  examples/playbooks/rule-command-instead-of-module-pass.yml
  src/ansiblelint/rules/command_instead_of_module.py
Labels: bug

#4526 Allow use with readonly virtualenvs
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
Labels: bug, dependencies

#4527 Bump test dependencies
  .config/constraints.txt
  .pre-commit-config.yaml
  pyproject.toml
  test/schemas/package-lock.json
  test/schemas/package.json
  test/test_skiputils.py
Labels: skip-changelog, dependencies

#4531 Add 2025 to WindowsPlatformModel
  src/ansiblelint/schemas/meta.json
Labels: bug
