Repository ansible/ansible-lint, pull requests merged in 2025-04, with the labels that each got.

#4569 Require ansible-core 2.16.11
  .config/constraints.txt
  .config/requirements-test.in
  .config/requirements.in
  .github/lower-constraints.txt
  pyproject.toml
Labels: minor

#4564 Refactor line number identification
  .pre-commit-config.yaml
  conftest.py
  examples/.no_collection_version/galaxy.yml
  pyproject.toml
  src/ansiblelint/constants.py
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/rules/complexity.py
  src/ansiblelint/rules/fqcn.py
  src/ansiblelint/rules/galaxy.py
  src/ansiblelint/rules/galaxy_version_incorrect.py
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/key_order.py
  src/ansiblelint/rules/loop_var_prefix.py
  src/ansiblelint/rules/meta_incorrect.py
  src/ansiblelint/rules/meta_video_links.py
  src/ansiblelint/rules/name.py
  src/ansiblelint/rules/no_handler.py
  src/ansiblelint/rules/no_jinja_when.py
  src/ansiblelint/rules/no_prompting.py
  src/ansiblelint/rules/no_tabs.py
  src/ansiblelint/rules/partial_become.py
  src/ansiblelint/rules/role_name.py
  src/ansiblelint/rules/schema.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/rules/var_naming.py
  src/ansiblelint/types.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/rules/test_syntax_check.py
  test/test_app.py
  test/test_main.py
  test/test_utils.py
  test/test_vulture.py
Labels: bug

#4571 Finish support for data tagging from ansible 2.19
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/rules/syntax_check.py
  src/ansiblelint/types.py
  src/ansiblelint/utils.py
  test/test_utils.py
  tox.ini
Labels: bug, dependencies

#4572 chore(schema): add missing ubuntu codenames
  src/ansiblelint/schemas/meta.json
Labels: bug

#4576 Package Latest: Use DNF for Examples
  src/ansiblelint/rules/package_latest.md
Labels: bug, documentation

#4595 Fix type issue affecting builds
  .pre-commit-config.yaml
  src/ansiblelint/requirements.py
  tox.ini
Labels: bug
