Repository ansible/ansible-lint, pull requests merged in 2025-08, with the labels that each got.

#4712 Lint failure in ansible.utils: src must be an absolute path fix
  src/ansiblelint/utils.py
Labels: bug

#4724 Fix mypy and pyright type checking errors
  pyproject.toml
  src/ansiblelint/rules/jinja.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
  src/ansiblelint/skip_utils.py
  src/ansiblelint/types.py
  src/ansiblelint/utils.py
  src/ansiblelint/yaml_utils.py
  test/test_skiputils.py
  test/test_utils.py
Labels: chore

#4722 Fix first-run collection discovery by enabling plugin loader after prepare_environment
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  src/ansiblelint/app.py
  src/ansiblelint/runner.py
  src/ansiblelint/schemas/galaxy.json
  test/schemas/negative_test/changelogs/invalid-date/changelogs/changelog.yaml.md
  test/schemas/negative_test/changelogs/invalid-plugin-namespace/changelogs/changelog.yaml.md
  test/schemas/negative_test/playbooks/import_playbook.yml.md
  test/schemas/package-lock.json
  test/schemas/package.json
  test/test_utils.py
Labels: bug

#4734 Update deps
  .config/constraints.txt
  .config/requirements-lock.txt
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/rulebook.json
Labels: bug, dependencies

#4727 Update supported Ubuntu platforms
  src/ansiblelint/schemas/meta.json
Labels: bug

#4742 whole test cases where template error is being generated and we are i…
  src/ansiblelint/rules/jinja.py
  test/test_jinja_ansible_tagged_str.py
Labels: bug, test
