Repository ansible/ansible-lint, pull requests merged in 2025-01, with the labels that each got.

#4462 Avoid ruamel.yaml 0.18.7-0.18.8 due to regression
  .config/constraints.txt
  .config/requirements.in
  .pre-commit-config.yaml
  src/ansiblelint/errors.py
  src/ansiblelint/rules/args.py
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/main.py
  src/ansiblelint/testing/__init__.py
  src/ansiblelint/utils.py
  test/schemas/package-lock.json
  test/schemas/package.json
  test/test_cli.py
  test/test_transformer.py
Labels: bug

#4463 Catch ansible-compat initialization warnings
  src/ansiblelint/__main__.py
Labels: bug

#4464 Add EL 10 as a platform in the metadata schema
  src/ansiblelint/schemas/meta.json
Labels: bug

#4480 Update schema etag
  src/ansiblelint/schemas/__store__.json
Labels: skip-changelog

#4483 Require ansible-core>=2.16
  .ansible-lint
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
Labels: bug

#4485 Fix constraints with uv and update min requirements
  .config/requirements.in
  .github/lower-constraints.txt
  tox.ini
Labels: bug

#4478 Refactor use of app instance
  .vault_pass
  ansible.cfg
  src/ansiblelint/rules/__init__.py
  src/ansiblelint/runner.py
  src/ansiblelint/utils.py
  test/test_formatter.py
  test/test_formatter_json.py
  test/test_formatter_sarif.py
  test/test_schemas.py
Labels: bug

#4479 Update requires_ansible default require >=2.16
  src/ansiblelint/config.py
  src/ansiblelint/rules/meta_runtime.md
Labels: minor

#4475 Move octal example code next to octals definition
  src/ansiblelint/rules/yaml.md
Labels: bug

#4379 Fix WARN on empty/template meta/main.yaml
  src/ansiblelint/rules/role_name.py
Labels: bug, needs-tests

#4486 Make testing of calls outside an activated venv more resilient
  test/test_main.py
Labels: skip-changelog

#4487 Remove dependency hack that prevents installation on Windows
  .config/requirements.in
Labels: bug

#4488 Improve path injection logic to resolve symlinked directories
  src/ansiblelint/__main__.py
  test/test_main.py
Labels: skip-changelog

#4490 Fix output terminal colors error for black on black
  src/ansiblelint/output.py
Labels: bug

#4491 Add documentation about how to use private repositories with the github action
  docs/installing.md
Labels: minor

#4495 Update compat and pre-commit versions
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .github/lower-constraints.txt
  .pre-commit-config.yaml
  src/ansiblelint/schemas/__store__.json
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: bug

#4499 Update ansible-compat to `v25.1.1`
  .config/constraints.txt
  .config/requirements-lock.txt
  .pre-commit-config.yaml
  test/schemas/package-lock.json
  test/schemas/package.json
Labels: bug

#4504 Allow linter to capture and display initialization warnings
  .gitignore
  src/ansiblelint/__main__.py
Labels: bug

#4500 Clarify partial-become rule description
  src/ansiblelint/rules/partial_become.py
Labels: bug

#4505 Avoid broken referencing dependency
  .config/constraints.txt
  .config/requirements-lock.txt
  .config/requirements.in
  .pre-commit-config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  src/ansiblelint/schemas/ansible-navigator-config.json
  tox.ini
Labels: bug
