Repository ansible/ansible-lint, pull requests merged in 2025-09, with the labels that each got.

#4743 Prevent false positive pattern detection in filenames containing "pattern.json"
  src/ansiblelint/file_utils.py
  src/ansiblelint/schemas/__store__.json
Labels: bug

#4752 chore: update hook configs
  .config/dictionary.txt
  cspell.config.yaml
  pyproject.toml
Labels: chore

#4720 fix: clarify error message related to --fix arguments
  src/ansiblelint/__main__.py
Labels: fix

#4760 Revert "fix: adopt uv.lock and dependency-groups (#4757)"
  .config/constraints.txt
  .config/requirements-docs.in
  .config/requirements-lock.txt
  .config/requirements-test.in
  .config/requirements.in
  .github/lower-constraints.txt
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  .vscode/extensions.json
  .vscode/settings.json
  cspell.config.yaml
  pyproject.toml
  src/ansiblelint/schemas/__store__.json
  test/test_schemas.py
  tools/test-setup.sh
  tox.ini
  uv.lock
Labels: fix
